/*
 * This file is generated by jOOQ.
*/
package com.sms.sis.db.tables;


import com.sms.sis.db.Keys;
import com.sms.sis.db.Sugarcrm_4_12;
import com.sms.sis.db.tables.records.AclRolesUsersRecord;

import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AclRolesUsers extends TableImpl<AclRolesUsersRecord> {

    private static final long serialVersionUID = -546695045;

    /**
     * The reference instance of <code>sugarcrm_4_12.acl_roles_users</code>
     */
    public static final AclRolesUsers ACL_ROLES_USERS = new AclRolesUsers();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<AclRolesUsersRecord> getRecordType() {
        return AclRolesUsersRecord.class;
    }

    /**
     * The column <code>sugarcrm_4_12.acl_roles_users.id</code>.
     */
    public final TableField<AclRolesUsersRecord, String> ID = createField("id", org.jooq.impl.SQLDataType.VARCHAR.length(36).nullable(false), this, "");

    /**
     * The column <code>sugarcrm_4_12.acl_roles_users.role_id</code>.
     */
    public final TableField<AclRolesUsersRecord, String> ROLE_ID = createField("role_id", org.jooq.impl.SQLDataType.VARCHAR.length(36), this, "");

    /**
     * The column <code>sugarcrm_4_12.acl_roles_users.user_id</code>.
     */
    public final TableField<AclRolesUsersRecord, String> USER_ID = createField("user_id", org.jooq.impl.SQLDataType.VARCHAR.length(36), this, "");

    /**
     * The column <code>sugarcrm_4_12.acl_roles_users.date_modified</code>.
     */
    public final TableField<AclRolesUsersRecord, Timestamp> DATE_MODIFIED = createField("date_modified", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

    /**
     * The column <code>sugarcrm_4_12.acl_roles_users.deleted</code>.
     */
    public final TableField<AclRolesUsersRecord, Byte> DELETED = createField("deleted", org.jooq.impl.SQLDataType.TINYINT.defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.TINYINT)), this, "");

    /**
     * Create a <code>sugarcrm_4_12.acl_roles_users</code> table reference
     */
    public AclRolesUsers() {
        this("acl_roles_users", null);
    }

    /**
     * Create an aliased <code>sugarcrm_4_12.acl_roles_users</code> table reference
     */
    public AclRolesUsers(String alias) {
        this(alias, ACL_ROLES_USERS);
    }

    private AclRolesUsers(String alias, Table<AclRolesUsersRecord> aliased) {
        this(alias, aliased, null);
    }

    private AclRolesUsers(String alias, Table<AclRolesUsersRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Sugarcrm_4_12.SUGARCRM_4_12;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<AclRolesUsersRecord> getPrimaryKey() {
        return Keys.KEY_ACL_ROLES_USERS_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<AclRolesUsersRecord>> getKeys() {
        return Arrays.<UniqueKey<AclRolesUsersRecord>>asList(Keys.KEY_ACL_ROLES_USERS_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AclRolesUsers as(String alias) {
        return new AclRolesUsers(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public AclRolesUsers rename(String name) {
        return new AclRolesUsers(name, null);
    }
}
