/*
 * This file is generated by jOOQ.
*/
package com.sms.sis.db.tables;


import com.sms.sis.db.Sugarcrm_4_12;
import com.sms.sis.db.tables.records.AddressBookRecord;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AddressBook extends TableImpl<AddressBookRecord> {

    private static final long serialVersionUID = 705143872;

    /**
     * The reference instance of <code>sugarcrm_4_12.address_book</code>
     */
    public static final AddressBook ADDRESS_BOOK = new AddressBook();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<AddressBookRecord> getRecordType() {
        return AddressBookRecord.class;
    }

    /**
     * The column <code>sugarcrm_4_12.address_book.assigned_user_id</code>.
     */
    public final TableField<AddressBookRecord, String> ASSIGNED_USER_ID = createField("assigned_user_id", org.jooq.impl.SQLDataType.CHAR.length(36).nullable(false), this, "");

    /**
     * The column <code>sugarcrm_4_12.address_book.bean</code>.
     */
    public final TableField<AddressBookRecord, String> BEAN = createField("bean", org.jooq.impl.SQLDataType.VARCHAR.length(50), this, "");

    /**
     * The column <code>sugarcrm_4_12.address_book.bean_id</code>.
     */
    public final TableField<AddressBookRecord, String> BEAN_ID = createField("bean_id", org.jooq.impl.SQLDataType.CHAR.length(36).nullable(false), this, "");

    /**
     * Create a <code>sugarcrm_4_12.address_book</code> table reference
     */
    public AddressBook() {
        this("address_book", null);
    }

    /**
     * Create an aliased <code>sugarcrm_4_12.address_book</code> table reference
     */
    public AddressBook(String alias) {
        this(alias, ADDRESS_BOOK);
    }

    private AddressBook(String alias, Table<AddressBookRecord> aliased) {
        this(alias, aliased, null);
    }

    private AddressBook(String alias, Table<AddressBookRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Sugarcrm_4_12.SUGARCRM_4_12;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AddressBook as(String alias) {
        return new AddressBook(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public AddressBook rename(String name) {
        return new AddressBook(name, null);
    }
}
