/*
 * This file is generated by jOOQ.
*/
package com.sms.sis.db.tables;


import com.sms.sis.db.Keys;
import com.sms.sis.db.Sugarcrm_4_12;
import com.sms.sis.db.tables.records.CasesRecord;

import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Cases extends TableImpl<CasesRecord> {

    private static final long serialVersionUID = -700969068;

    /**
     * The reference instance of <code>sugarcrm_4_12.cases</code>
     */
    public static final Cases CASES = new Cases();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<CasesRecord> getRecordType() {
        return CasesRecord.class;
    }

    /**
     * The column <code>sugarcrm_4_12.cases.id</code>.
     */
    public final TableField<CasesRecord, String> ID = createField("id", org.jooq.impl.SQLDataType.CHAR.length(36).nullable(false), this, "");

    /**
     * The column <code>sugarcrm_4_12.cases.name</code>.
     */
    public final TableField<CasesRecord, String> NAME = createField("name", org.jooq.impl.SQLDataType.VARCHAR.length(255), this, "");

    /**
     * The column <code>sugarcrm_4_12.cases.date_entered</code>.
     */
    public final TableField<CasesRecord, Timestamp> DATE_ENTERED = createField("date_entered", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

    /**
     * The column <code>sugarcrm_4_12.cases.date_modified</code>.
     */
    public final TableField<CasesRecord, Timestamp> DATE_MODIFIED = createField("date_modified", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

    /**
     * The column <code>sugarcrm_4_12.cases.modified_user_id</code>.
     */
    public final TableField<CasesRecord, String> MODIFIED_USER_ID = createField("modified_user_id", org.jooq.impl.SQLDataType.CHAR.length(36), this, "");

    /**
     * The column <code>sugarcrm_4_12.cases.created_by</code>.
     */
    public final TableField<CasesRecord, String> CREATED_BY = createField("created_by", org.jooq.impl.SQLDataType.CHAR.length(36), this, "");

    /**
     * The column <code>sugarcrm_4_12.cases.description</code>.
     */
    public final TableField<CasesRecord, String> DESCRIPTION = createField("description", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * The column <code>sugarcrm_4_12.cases.deleted</code>.
     */
    public final TableField<CasesRecord, Byte> DELETED = createField("deleted", org.jooq.impl.SQLDataType.TINYINT.defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.TINYINT)), this, "");

    /**
     * The column <code>sugarcrm_4_12.cases.assigned_user_id</code>.
     */
    public final TableField<CasesRecord, String> ASSIGNED_USER_ID = createField("assigned_user_id", org.jooq.impl.SQLDataType.CHAR.length(36), this, "");

    /**
     * The column <code>sugarcrm_4_12.cases.case_number</code>.
     */
    public final TableField<CasesRecord, Integer> CASE_NUMBER = createField("case_number", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>sugarcrm_4_12.cases.type</code>.
     */
    public final TableField<CasesRecord, String> TYPE = createField("type", org.jooq.impl.SQLDataType.VARCHAR.length(255), this, "");

    /**
     * The column <code>sugarcrm_4_12.cases.status</code>.
     */
    public final TableField<CasesRecord, String> STATUS = createField("status", org.jooq.impl.SQLDataType.VARCHAR.length(100), this, "");

    /**
     * The column <code>sugarcrm_4_12.cases.priority</code>.
     */
    public final TableField<CasesRecord, String> PRIORITY = createField("priority", org.jooq.impl.SQLDataType.VARCHAR.length(100), this, "");

    /**
     * The column <code>sugarcrm_4_12.cases.resolution</code>.
     */
    public final TableField<CasesRecord, String> RESOLUTION = createField("resolution", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * The column <code>sugarcrm_4_12.cases.work_log</code>.
     */
    public final TableField<CasesRecord, String> WORK_LOG = createField("work_log", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * The column <code>sugarcrm_4_12.cases.account_id</code>.
     */
    public final TableField<CasesRecord, String> ACCOUNT_ID = createField("account_id", org.jooq.impl.SQLDataType.CHAR.length(36), this, "");

    /**
     * Create a <code>sugarcrm_4_12.cases</code> table reference
     */
    public Cases() {
        this("cases", null);
    }

    /**
     * Create an aliased <code>sugarcrm_4_12.cases</code> table reference
     */
    public Cases(String alias) {
        this(alias, CASES);
    }

    private Cases(String alias, Table<CasesRecord> aliased) {
        this(alias, aliased, null);
    }

    private Cases(String alias, Table<CasesRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Sugarcrm_4_12.SUGARCRM_4_12;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<CasesRecord, Integer> getIdentity() {
        return Keys.IDENTITY_CASES;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<CasesRecord> getPrimaryKey() {
        return Keys.KEY_CASES_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<CasesRecord>> getKeys() {
        return Arrays.<UniqueKey<CasesRecord>>asList(Keys.KEY_CASES_PRIMARY, Keys.KEY_CASES_CASESNUMK);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Cases as(String alias) {
        return new Cases(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Cases rename(String name) {
        return new Cases(name, null);
    }
}
