/*
 * This file is generated by jOOQ.
*/
package com.sms.sis.db.tables;


import com.sms.sis.db.Sugarcrm_4_12;
import com.sms.sis.db.tables.records.CustomFieldsRecord;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CustomFields extends TableImpl<CustomFieldsRecord> {

    private static final long serialVersionUID = 1610264218;

    /**
     * The reference instance of <code>sugarcrm_4_12.custom_fields</code>
     */
    public static final CustomFields CUSTOM_FIELDS = new CustomFields();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<CustomFieldsRecord> getRecordType() {
        return CustomFieldsRecord.class;
    }

    /**
     * The column <code>sugarcrm_4_12.custom_fields.bean_id</code>.
     */
    public final TableField<CustomFieldsRecord, String> BEAN_ID = createField("bean_id", org.jooq.impl.SQLDataType.VARCHAR.length(36), this, "");

    /**
     * The column <code>sugarcrm_4_12.custom_fields.set_num</code>.
     */
    public final TableField<CustomFieldsRecord, Integer> SET_NUM = createField("set_num", org.jooq.impl.SQLDataType.INTEGER.defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>sugarcrm_4_12.custom_fields.field0</code>.
     */
    public final TableField<CustomFieldsRecord, String> FIELD0 = createField("field0", org.jooq.impl.SQLDataType.VARCHAR.length(255), this, "");

    /**
     * The column <code>sugarcrm_4_12.custom_fields.field1</code>.
     */
    public final TableField<CustomFieldsRecord, String> FIELD1 = createField("field1", org.jooq.impl.SQLDataType.VARCHAR.length(255), this, "");

    /**
     * The column <code>sugarcrm_4_12.custom_fields.field2</code>.
     */
    public final TableField<CustomFieldsRecord, String> FIELD2 = createField("field2", org.jooq.impl.SQLDataType.VARCHAR.length(255), this, "");

    /**
     * The column <code>sugarcrm_4_12.custom_fields.field3</code>.
     */
    public final TableField<CustomFieldsRecord, String> FIELD3 = createField("field3", org.jooq.impl.SQLDataType.VARCHAR.length(255), this, "");

    /**
     * The column <code>sugarcrm_4_12.custom_fields.field4</code>.
     */
    public final TableField<CustomFieldsRecord, String> FIELD4 = createField("field4", org.jooq.impl.SQLDataType.VARCHAR.length(255), this, "");

    /**
     * The column <code>sugarcrm_4_12.custom_fields.field5</code>.
     */
    public final TableField<CustomFieldsRecord, String> FIELD5 = createField("field5", org.jooq.impl.SQLDataType.VARCHAR.length(255), this, "");

    /**
     * The column <code>sugarcrm_4_12.custom_fields.field6</code>.
     */
    public final TableField<CustomFieldsRecord, String> FIELD6 = createField("field6", org.jooq.impl.SQLDataType.VARCHAR.length(255), this, "");

    /**
     * The column <code>sugarcrm_4_12.custom_fields.field7</code>.
     */
    public final TableField<CustomFieldsRecord, String> FIELD7 = createField("field7", org.jooq.impl.SQLDataType.VARCHAR.length(255), this, "");

    /**
     * The column <code>sugarcrm_4_12.custom_fields.field8</code>.
     */
    public final TableField<CustomFieldsRecord, String> FIELD8 = createField("field8", org.jooq.impl.SQLDataType.VARCHAR.length(255), this, "");

    /**
     * The column <code>sugarcrm_4_12.custom_fields.field9</code>.
     */
    public final TableField<CustomFieldsRecord, String> FIELD9 = createField("field9", org.jooq.impl.SQLDataType.VARCHAR.length(255), this, "");

    /**
     * The column <code>sugarcrm_4_12.custom_fields.deleted</code>.
     */
    public final TableField<CustomFieldsRecord, Byte> DELETED = createField("deleted", org.jooq.impl.SQLDataType.TINYINT.defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.TINYINT)), this, "");

    /**
     * Create a <code>sugarcrm_4_12.custom_fields</code> table reference
     */
    public CustomFields() {
        this("custom_fields", null);
    }

    /**
     * Create an aliased <code>sugarcrm_4_12.custom_fields</code> table reference
     */
    public CustomFields(String alias) {
        this(alias, CUSTOM_FIELDS);
    }

    private CustomFields(String alias, Table<CustomFieldsRecord> aliased) {
        this(alias, aliased, null);
    }

    private CustomFields(String alias, Table<CustomFieldsRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Sugarcrm_4_12.SUGARCRM_4_12;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CustomFields as(String alias) {
        return new CustomFields(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public CustomFields rename(String name) {
        return new CustomFields(name, null);
    }
}
