/*
 * This file is generated by jOOQ.
*/
package com.sms.sis.db.tables;


import com.sms.sis.db.Keys;
import com.sms.sis.db.Sugarcrm_4_12;
import com.sms.sis.db.tables.records.DocumentsRecord;

import java.sql.Date;
import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Documents extends TableImpl<DocumentsRecord> {

    private static final long serialVersionUID = 1980493628;

    /**
     * The reference instance of <code>sugarcrm_4_12.documents</code>
     */
    public static final Documents DOCUMENTS = new Documents();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<DocumentsRecord> getRecordType() {
        return DocumentsRecord.class;
    }

    /**
     * The column <code>sugarcrm_4_12.documents.id</code>.
     */
    public final TableField<DocumentsRecord, String> ID = createField("id", org.jooq.impl.SQLDataType.CHAR.length(36).nullable(false), this, "");

    /**
     * The column <code>sugarcrm_4_12.documents.date_entered</code>.
     */
    public final TableField<DocumentsRecord, Timestamp> DATE_ENTERED = createField("date_entered", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

    /**
     * The column <code>sugarcrm_4_12.documents.date_modified</code>.
     */
    public final TableField<DocumentsRecord, Timestamp> DATE_MODIFIED = createField("date_modified", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

    /**
     * The column <code>sugarcrm_4_12.documents.modified_user_id</code>.
     */
    public final TableField<DocumentsRecord, String> MODIFIED_USER_ID = createField("modified_user_id", org.jooq.impl.SQLDataType.CHAR.length(36), this, "");

    /**
     * The column <code>sugarcrm_4_12.documents.created_by</code>.
     */
    public final TableField<DocumentsRecord, String> CREATED_BY = createField("created_by", org.jooq.impl.SQLDataType.CHAR.length(36), this, "");

    /**
     * The column <code>sugarcrm_4_12.documents.description</code>.
     */
    public final TableField<DocumentsRecord, String> DESCRIPTION = createField("description", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * The column <code>sugarcrm_4_12.documents.deleted</code>.
     */
    public final TableField<DocumentsRecord, Byte> DELETED = createField("deleted", org.jooq.impl.SQLDataType.TINYINT.defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.TINYINT)), this, "");

    /**
     * The column <code>sugarcrm_4_12.documents.assigned_user_id</code>.
     */
    public final TableField<DocumentsRecord, String> ASSIGNED_USER_ID = createField("assigned_user_id", org.jooq.impl.SQLDataType.CHAR.length(36), this, "");

    /**
     * The column <code>sugarcrm_4_12.documents.document_name</code>.
     */
    public final TableField<DocumentsRecord, String> DOCUMENT_NAME = createField("document_name", org.jooq.impl.SQLDataType.VARCHAR.length(255), this, "");

    /**
     * The column <code>sugarcrm_4_12.documents.doc_id</code>.
     */
    public final TableField<DocumentsRecord, String> DOC_ID = createField("doc_id", org.jooq.impl.SQLDataType.VARCHAR.length(100), this, "");

    /**
     * The column <code>sugarcrm_4_12.documents.doc_type</code>.
     */
    public final TableField<DocumentsRecord, String> DOC_TYPE = createField("doc_type", org.jooq.impl.SQLDataType.VARCHAR.length(100).defaultValue(org.jooq.impl.DSL.inline("Sugar", org.jooq.impl.SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>sugarcrm_4_12.documents.doc_url</code>.
     */
    public final TableField<DocumentsRecord, String> DOC_URL = createField("doc_url", org.jooq.impl.SQLDataType.VARCHAR.length(255), this, "");

    /**
     * The column <code>sugarcrm_4_12.documents.active_date</code>.
     */
    public final TableField<DocumentsRecord, Date> ACTIVE_DATE = createField("active_date", org.jooq.impl.SQLDataType.DATE, this, "");

    /**
     * The column <code>sugarcrm_4_12.documents.exp_date</code>.
     */
    public final TableField<DocumentsRecord, Date> EXP_DATE = createField("exp_date", org.jooq.impl.SQLDataType.DATE, this, "");

    /**
     * The column <code>sugarcrm_4_12.documents.category_id</code>.
     */
    public final TableField<DocumentsRecord, String> CATEGORY_ID = createField("category_id", org.jooq.impl.SQLDataType.VARCHAR.length(100), this, "");

    /**
     * The column <code>sugarcrm_4_12.documents.subcategory_id</code>.
     */
    public final TableField<DocumentsRecord, String> SUBCATEGORY_ID = createField("subcategory_id", org.jooq.impl.SQLDataType.VARCHAR.length(100), this, "");

    /**
     * The column <code>sugarcrm_4_12.documents.status_id</code>.
     */
    public final TableField<DocumentsRecord, String> STATUS_ID = createField("status_id", org.jooq.impl.SQLDataType.VARCHAR.length(100), this, "");

    /**
     * The column <code>sugarcrm_4_12.documents.document_revision_id</code>.
     */
    public final TableField<DocumentsRecord, String> DOCUMENT_REVISION_ID = createField("document_revision_id", org.jooq.impl.SQLDataType.VARCHAR.length(36), this, "");

    /**
     * The column <code>sugarcrm_4_12.documents.related_doc_id</code>.
     */
    public final TableField<DocumentsRecord, String> RELATED_DOC_ID = createField("related_doc_id", org.jooq.impl.SQLDataType.CHAR.length(36), this, "");

    /**
     * The column <code>sugarcrm_4_12.documents.related_doc_rev_id</code>.
     */
    public final TableField<DocumentsRecord, String> RELATED_DOC_REV_ID = createField("related_doc_rev_id", org.jooq.impl.SQLDataType.CHAR.length(36), this, "");

    /**
     * The column <code>sugarcrm_4_12.documents.is_template</code>.
     */
    public final TableField<DocumentsRecord, Byte> IS_TEMPLATE = createField("is_template", org.jooq.impl.SQLDataType.TINYINT.defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.TINYINT)), this, "");

    /**
     * The column <code>sugarcrm_4_12.documents.template_type</code>.
     */
    public final TableField<DocumentsRecord, String> TEMPLATE_TYPE = createField("template_type", org.jooq.impl.SQLDataType.VARCHAR.length(100), this, "");

    /**
     * Create a <code>sugarcrm_4_12.documents</code> table reference
     */
    public Documents() {
        this("documents", null);
    }

    /**
     * Create an aliased <code>sugarcrm_4_12.documents</code> table reference
     */
    public Documents(String alias) {
        this(alias, DOCUMENTS);
    }

    private Documents(String alias, Table<DocumentsRecord> aliased) {
        this(alias, aliased, null);
    }

    private Documents(String alias, Table<DocumentsRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Sugarcrm_4_12.SUGARCRM_4_12;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<DocumentsRecord> getPrimaryKey() {
        return Keys.KEY_DOCUMENTS_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<DocumentsRecord>> getKeys() {
        return Arrays.<UniqueKey<DocumentsRecord>>asList(Keys.KEY_DOCUMENTS_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Documents as(String alias) {
        return new Documents(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Documents rename(String name) {
        return new Documents(name, null);
    }
}
