/*
 * This file is generated by jOOQ.
*/
package com.sms.sis.db.tables;


import com.sms.sis.db.Keys;
import com.sms.sis.db.Sugarcrm_4_12;
import com.sms.sis.db.tables.records.EmailmanRecord;

import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Emailman extends TableImpl<EmailmanRecord> {

    private static final long serialVersionUID = 856971443;

    /**
     * The reference instance of <code>sugarcrm_4_12.emailman</code>
     */
    public static final Emailman EMAILMAN = new Emailman();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<EmailmanRecord> getRecordType() {
        return EmailmanRecord.class;
    }

    /**
     * The column <code>sugarcrm_4_12.emailman.date_entered</code>.
     */
    public final TableField<EmailmanRecord, Timestamp> DATE_ENTERED = createField("date_entered", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

    /**
     * The column <code>sugarcrm_4_12.emailman.date_modified</code>.
     */
    public final TableField<EmailmanRecord, Timestamp> DATE_MODIFIED = createField("date_modified", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

    /**
     * The column <code>sugarcrm_4_12.emailman.user_id</code>.
     */
    public final TableField<EmailmanRecord, String> USER_ID = createField("user_id", org.jooq.impl.SQLDataType.CHAR.length(36), this, "");

    /**
     * The column <code>sugarcrm_4_12.emailman.id</code>.
     */
    public final TableField<EmailmanRecord, Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>sugarcrm_4_12.emailman.campaign_id</code>.
     */
    public final TableField<EmailmanRecord, String> CAMPAIGN_ID = createField("campaign_id", org.jooq.impl.SQLDataType.CHAR.length(36), this, "");

    /**
     * The column <code>sugarcrm_4_12.emailman.marketing_id</code>.
     */
    public final TableField<EmailmanRecord, String> MARKETING_ID = createField("marketing_id", org.jooq.impl.SQLDataType.CHAR.length(36), this, "");

    /**
     * The column <code>sugarcrm_4_12.emailman.list_id</code>.
     */
    public final TableField<EmailmanRecord, String> LIST_ID = createField("list_id", org.jooq.impl.SQLDataType.CHAR.length(36), this, "");

    /**
     * The column <code>sugarcrm_4_12.emailman.send_date_time</code>.
     */
    public final TableField<EmailmanRecord, Timestamp> SEND_DATE_TIME = createField("send_date_time", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

    /**
     * The column <code>sugarcrm_4_12.emailman.modified_user_id</code>.
     */
    public final TableField<EmailmanRecord, String> MODIFIED_USER_ID = createField("modified_user_id", org.jooq.impl.SQLDataType.CHAR.length(36), this, "");

    /**
     * The column <code>sugarcrm_4_12.emailman.in_queue</code>.
     */
    public final TableField<EmailmanRecord, Byte> IN_QUEUE = createField("in_queue", org.jooq.impl.SQLDataType.TINYINT.defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.TINYINT)), this, "");

    /**
     * The column <code>sugarcrm_4_12.emailman.in_queue_date</code>.
     */
    public final TableField<EmailmanRecord, Timestamp> IN_QUEUE_DATE = createField("in_queue_date", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

    /**
     * The column <code>sugarcrm_4_12.emailman.send_attempts</code>.
     */
    public final TableField<EmailmanRecord, Integer> SEND_ATTEMPTS = createField("send_attempts", org.jooq.impl.SQLDataType.INTEGER.defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>sugarcrm_4_12.emailman.deleted</code>.
     */
    public final TableField<EmailmanRecord, Byte> DELETED = createField("deleted", org.jooq.impl.SQLDataType.TINYINT.defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.TINYINT)), this, "");

    /**
     * The column <code>sugarcrm_4_12.emailman.related_id</code>.
     */
    public final TableField<EmailmanRecord, String> RELATED_ID = createField("related_id", org.jooq.impl.SQLDataType.CHAR.length(36), this, "");

    /**
     * The column <code>sugarcrm_4_12.emailman.related_type</code>.
     */
    public final TableField<EmailmanRecord, String> RELATED_TYPE = createField("related_type", org.jooq.impl.SQLDataType.VARCHAR.length(100), this, "");

    /**
     * Create a <code>sugarcrm_4_12.emailman</code> table reference
     */
    public Emailman() {
        this("emailman", null);
    }

    /**
     * Create an aliased <code>sugarcrm_4_12.emailman</code> table reference
     */
    public Emailman(String alias) {
        this(alias, EMAILMAN);
    }

    private Emailman(String alias, Table<EmailmanRecord> aliased) {
        this(alias, aliased, null);
    }

    private Emailman(String alias, Table<EmailmanRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Sugarcrm_4_12.SUGARCRM_4_12;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<EmailmanRecord, Integer> getIdentity() {
        return Keys.IDENTITY_EMAILMAN;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<EmailmanRecord> getPrimaryKey() {
        return Keys.KEY_EMAILMAN_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<EmailmanRecord>> getKeys() {
        return Arrays.<UniqueKey<EmailmanRecord>>asList(Keys.KEY_EMAILMAN_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Emailman as(String alias) {
        return new Emailman(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Emailman rename(String name) {
        return new Emailman(name, null);
    }
}
