/*
 * This file is generated by jOOQ.
*/
package com.sms.sis.db.tables;


import com.sms.sis.db.Keys;
import com.sms.sis.db.Sugarcrm_4_12;
import com.sms.sis.db.tables.records.EmailsEmailAddrRelRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class EmailsEmailAddrRel extends TableImpl<EmailsEmailAddrRelRecord> {

    private static final long serialVersionUID = -384460231;

    /**
     * The reference instance of <code>sugarcrm_4_12.emails_email_addr_rel</code>
     */
    public static final EmailsEmailAddrRel EMAILS_EMAIL_ADDR_REL = new EmailsEmailAddrRel();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<EmailsEmailAddrRelRecord> getRecordType() {
        return EmailsEmailAddrRelRecord.class;
    }

    /**
     * The column <code>sugarcrm_4_12.emails_email_addr_rel.id</code>.
     */
    public final TableField<EmailsEmailAddrRelRecord, String> ID = createField("id", org.jooq.impl.SQLDataType.CHAR.length(36).nullable(false), this, "");

    /**
     * The column <code>sugarcrm_4_12.emails_email_addr_rel.email_id</code>.
     */
    public final TableField<EmailsEmailAddrRelRecord, String> EMAIL_ID = createField("email_id", org.jooq.impl.SQLDataType.CHAR.length(36).nullable(false), this, "");

    /**
     * The column <code>sugarcrm_4_12.emails_email_addr_rel.address_type</code>.
     */
    public final TableField<EmailsEmailAddrRelRecord, String> ADDRESS_TYPE = createField("address_type", org.jooq.impl.SQLDataType.VARCHAR.length(4), this, "");

    /**
     * The column <code>sugarcrm_4_12.emails_email_addr_rel.email_address_id</code>.
     */
    public final TableField<EmailsEmailAddrRelRecord, String> EMAIL_ADDRESS_ID = createField("email_address_id", org.jooq.impl.SQLDataType.CHAR.length(36).nullable(false), this, "");

    /**
     * The column <code>sugarcrm_4_12.emails_email_addr_rel.deleted</code>.
     */
    public final TableField<EmailsEmailAddrRelRecord, Byte> DELETED = createField("deleted", org.jooq.impl.SQLDataType.TINYINT.defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.TINYINT)), this, "");

    /**
     * Create a <code>sugarcrm_4_12.emails_email_addr_rel</code> table reference
     */
    public EmailsEmailAddrRel() {
        this("emails_email_addr_rel", null);
    }

    /**
     * Create an aliased <code>sugarcrm_4_12.emails_email_addr_rel</code> table reference
     */
    public EmailsEmailAddrRel(String alias) {
        this(alias, EMAILS_EMAIL_ADDR_REL);
    }

    private EmailsEmailAddrRel(String alias, Table<EmailsEmailAddrRelRecord> aliased) {
        this(alias, aliased, null);
    }

    private EmailsEmailAddrRel(String alias, Table<EmailsEmailAddrRelRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Sugarcrm_4_12.SUGARCRM_4_12;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<EmailsEmailAddrRelRecord> getPrimaryKey() {
        return Keys.KEY_EMAILS_EMAIL_ADDR_REL_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<EmailsEmailAddrRelRecord>> getKeys() {
        return Arrays.<UniqueKey<EmailsEmailAddrRelRecord>>asList(Keys.KEY_EMAILS_EMAIL_ADDR_REL_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EmailsEmailAddrRel as(String alias) {
        return new EmailsEmailAddrRel(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public EmailsEmailAddrRel rename(String name) {
        return new EmailsEmailAddrRel(name, null);
    }
}
