/*
 * This file is generated by jOOQ.
*/
package com.sms.sis.db.tables;


import com.sms.sis.db.Keys;
import com.sms.sis.db.Sugarcrm_4_12;
import com.sms.sis.db.tables.records.EmailMarketingProspectListsRecord;

import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class EmailMarketingProspectLists extends TableImpl<EmailMarketingProspectListsRecord> {

    private static final long serialVersionUID = -1489588269;

    /**
     * The reference instance of <code>sugarcrm_4_12.email_marketing_prospect_lists</code>
     */
    public static final EmailMarketingProspectLists EMAIL_MARKETING_PROSPECT_LISTS = new EmailMarketingProspectLists();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<EmailMarketingProspectListsRecord> getRecordType() {
        return EmailMarketingProspectListsRecord.class;
    }

    /**
     * The column <code>sugarcrm_4_12.email_marketing_prospect_lists.id</code>.
     */
    public final TableField<EmailMarketingProspectListsRecord, String> ID = createField("id", org.jooq.impl.SQLDataType.VARCHAR.length(36).nullable(false), this, "");

    /**
     * The column <code>sugarcrm_4_12.email_marketing_prospect_lists.prospect_list_id</code>.
     */
    public final TableField<EmailMarketingProspectListsRecord, String> PROSPECT_LIST_ID = createField("prospect_list_id", org.jooq.impl.SQLDataType.VARCHAR.length(36), this, "");

    /**
     * The column <code>sugarcrm_4_12.email_marketing_prospect_lists.email_marketing_id</code>.
     */
    public final TableField<EmailMarketingProspectListsRecord, String> EMAIL_MARKETING_ID = createField("email_marketing_id", org.jooq.impl.SQLDataType.VARCHAR.length(36), this, "");

    /**
     * The column <code>sugarcrm_4_12.email_marketing_prospect_lists.date_modified</code>.
     */
    public final TableField<EmailMarketingProspectListsRecord, Timestamp> DATE_MODIFIED = createField("date_modified", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

    /**
     * The column <code>sugarcrm_4_12.email_marketing_prospect_lists.deleted</code>.
     */
    public final TableField<EmailMarketingProspectListsRecord, Byte> DELETED = createField("deleted", org.jooq.impl.SQLDataType.TINYINT.defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.TINYINT)), this, "");

    /**
     * Create a <code>sugarcrm_4_12.email_marketing_prospect_lists</code> table reference
     */
    public EmailMarketingProspectLists() {
        this("email_marketing_prospect_lists", null);
    }

    /**
     * Create an aliased <code>sugarcrm_4_12.email_marketing_prospect_lists</code> table reference
     */
    public EmailMarketingProspectLists(String alias) {
        this(alias, EMAIL_MARKETING_PROSPECT_LISTS);
    }

    private EmailMarketingProspectLists(String alias, Table<EmailMarketingProspectListsRecord> aliased) {
        this(alias, aliased, null);
    }

    private EmailMarketingProspectLists(String alias, Table<EmailMarketingProspectListsRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Sugarcrm_4_12.SUGARCRM_4_12;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<EmailMarketingProspectListsRecord> getPrimaryKey() {
        return Keys.KEY_EMAIL_MARKETING_PROSPECT_LISTS_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<EmailMarketingProspectListsRecord>> getKeys() {
        return Arrays.<UniqueKey<EmailMarketingProspectListsRecord>>asList(Keys.KEY_EMAIL_MARKETING_PROSPECT_LISTS_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EmailMarketingProspectLists as(String alias) {
        return new EmailMarketingProspectLists(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public EmailMarketingProspectLists rename(String name) {
        return new EmailMarketingProspectLists(name, null);
    }
}
