/*
 * This file is generated by jOOQ.
*/
package com.sms.sis.db.tables;


import com.sms.sis.db.Keys;
import com.sms.sis.db.Sugarcrm_4_12;
import com.sms.sis.db.tables.records.JobQueueRecord;

import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class JobQueue extends TableImpl<JobQueueRecord> {

    private static final long serialVersionUID = -1890757899;

    /**
     * The reference instance of <code>sugarcrm_4_12.job_queue</code>
     */
    public static final JobQueue JOB_QUEUE = new JobQueue();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<JobQueueRecord> getRecordType() {
        return JobQueueRecord.class;
    }

    /**
     * The column <code>sugarcrm_4_12.job_queue.assigned_user_id</code>.
     */
    public final TableField<JobQueueRecord, String> ASSIGNED_USER_ID = createField("assigned_user_id", org.jooq.impl.SQLDataType.CHAR.length(36), this, "");

    /**
     * The column <code>sugarcrm_4_12.job_queue.id</code>.
     */
    public final TableField<JobQueueRecord, String> ID = createField("id", org.jooq.impl.SQLDataType.CHAR.length(36).nullable(false), this, "");

    /**
     * The column <code>sugarcrm_4_12.job_queue.name</code>.
     */
    public final TableField<JobQueueRecord, String> NAME = createField("name", org.jooq.impl.SQLDataType.VARCHAR.length(255), this, "");

    /**
     * The column <code>sugarcrm_4_12.job_queue.deleted</code>.
     */
    public final TableField<JobQueueRecord, Byte> DELETED = createField("deleted", org.jooq.impl.SQLDataType.TINYINT.defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.TINYINT)), this, "");

    /**
     * The column <code>sugarcrm_4_12.job_queue.date_entered</code>.
     */
    public final TableField<JobQueueRecord, Timestamp> DATE_ENTERED = createField("date_entered", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

    /**
     * The column <code>sugarcrm_4_12.job_queue.date_modified</code>.
     */
    public final TableField<JobQueueRecord, Timestamp> DATE_MODIFIED = createField("date_modified", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

    /**
     * The column <code>sugarcrm_4_12.job_queue.scheduler_id</code>.
     */
    public final TableField<JobQueueRecord, String> SCHEDULER_ID = createField("scheduler_id", org.jooq.impl.SQLDataType.CHAR.length(36), this, "");

    /**
     * The column <code>sugarcrm_4_12.job_queue.execute_time</code>.
     */
    public final TableField<JobQueueRecord, Timestamp> EXECUTE_TIME = createField("execute_time", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

    /**
     * The column <code>sugarcrm_4_12.job_queue.status</code>.
     */
    public final TableField<JobQueueRecord, String> STATUS = createField("status", org.jooq.impl.SQLDataType.VARCHAR.length(20), this, "");

    /**
     * The column <code>sugarcrm_4_12.job_queue.resolution</code>.
     */
    public final TableField<JobQueueRecord, String> RESOLUTION = createField("resolution", org.jooq.impl.SQLDataType.VARCHAR.length(20), this, "");

    /**
     * The column <code>sugarcrm_4_12.job_queue.message</code>.
     */
    public final TableField<JobQueueRecord, String> MESSAGE = createField("message", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * The column <code>sugarcrm_4_12.job_queue.target</code>.
     */
    public final TableField<JobQueueRecord, String> TARGET = createField("target", org.jooq.impl.SQLDataType.VARCHAR.length(255), this, "");

    /**
     * The column <code>sugarcrm_4_12.job_queue.data</code>.
     */
    public final TableField<JobQueueRecord, String> DATA = createField("data", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * The column <code>sugarcrm_4_12.job_queue.requeue</code>.
     */
    public final TableField<JobQueueRecord, Byte> REQUEUE = createField("requeue", org.jooq.impl.SQLDataType.TINYINT.defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.TINYINT)), this, "");

    /**
     * The column <code>sugarcrm_4_12.job_queue.retry_count</code>.
     */
    public final TableField<JobQueueRecord, Byte> RETRY_COUNT = createField("retry_count", org.jooq.impl.SQLDataType.TINYINT, this, "");

    /**
     * The column <code>sugarcrm_4_12.job_queue.failure_count</code>.
     */
    public final TableField<JobQueueRecord, Byte> FAILURE_COUNT = createField("failure_count", org.jooq.impl.SQLDataType.TINYINT, this, "");

    /**
     * The column <code>sugarcrm_4_12.job_queue.job_delay</code>.
     */
    public final TableField<JobQueueRecord, Integer> JOB_DELAY = createField("job_delay", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>sugarcrm_4_12.job_queue.client</code>.
     */
    public final TableField<JobQueueRecord, String> CLIENT = createField("client", org.jooq.impl.SQLDataType.VARCHAR.length(255), this, "");

    /**
     * The column <code>sugarcrm_4_12.job_queue.percent_complete</code>.
     */
    public final TableField<JobQueueRecord, Integer> PERCENT_COMPLETE = createField("percent_complete", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * Create a <code>sugarcrm_4_12.job_queue</code> table reference
     */
    public JobQueue() {
        this("job_queue", null);
    }

    /**
     * Create an aliased <code>sugarcrm_4_12.job_queue</code> table reference
     */
    public JobQueue(String alias) {
        this(alias, JOB_QUEUE);
    }

    private JobQueue(String alias, Table<JobQueueRecord> aliased) {
        this(alias, aliased, null);
    }

    private JobQueue(String alias, Table<JobQueueRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Sugarcrm_4_12.SUGARCRM_4_12;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<JobQueueRecord> getPrimaryKey() {
        return Keys.KEY_JOB_QUEUE_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<JobQueueRecord>> getKeys() {
        return Arrays.<UniqueKey<JobQueueRecord>>asList(Keys.KEY_JOB_QUEUE_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public JobQueue as(String alias) {
        return new JobQueue(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public JobQueue rename(String name) {
        return new JobQueue(name, null);
    }
}
