/*
 * This file is generated by jOOQ.
*/
package com.sms.sis.db.tables;


import com.sms.sis.db.Keys;
import com.sms.sis.db.Sugarcrm_4_12;
import com.sms.sis.db.tables.records.ProjectsContactsRecord;

import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ProjectsContacts extends TableImpl<ProjectsContactsRecord> {

    private static final long serialVersionUID = -1340936898;

    /**
     * The reference instance of <code>sugarcrm_4_12.projects_contacts</code>
     */
    public static final ProjectsContacts PROJECTS_CONTACTS = new ProjectsContacts();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ProjectsContactsRecord> getRecordType() {
        return ProjectsContactsRecord.class;
    }

    /**
     * The column <code>sugarcrm_4_12.projects_contacts.id</code>.
     */
    public final TableField<ProjectsContactsRecord, String> ID = createField("id", org.jooq.impl.SQLDataType.VARCHAR.length(36).nullable(false), this, "");

    /**
     * The column <code>sugarcrm_4_12.projects_contacts.contact_id</code>.
     */
    public final TableField<ProjectsContactsRecord, String> CONTACT_ID = createField("contact_id", org.jooq.impl.SQLDataType.VARCHAR.length(36), this, "");

    /**
     * The column <code>sugarcrm_4_12.projects_contacts.project_id</code>.
     */
    public final TableField<ProjectsContactsRecord, String> PROJECT_ID = createField("project_id", org.jooq.impl.SQLDataType.VARCHAR.length(36), this, "");

    /**
     * The column <code>sugarcrm_4_12.projects_contacts.date_modified</code>.
     */
    public final TableField<ProjectsContactsRecord, Timestamp> DATE_MODIFIED = createField("date_modified", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

    /**
     * The column <code>sugarcrm_4_12.projects_contacts.deleted</code>.
     */
    public final TableField<ProjectsContactsRecord, Byte> DELETED = createField("deleted", org.jooq.impl.SQLDataType.TINYINT.defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.TINYINT)), this, "");

    /**
     * Create a <code>sugarcrm_4_12.projects_contacts</code> table reference
     */
    public ProjectsContacts() {
        this("projects_contacts", null);
    }

    /**
     * Create an aliased <code>sugarcrm_4_12.projects_contacts</code> table reference
     */
    public ProjectsContacts(String alias) {
        this(alias, PROJECTS_CONTACTS);
    }

    private ProjectsContacts(String alias, Table<ProjectsContactsRecord> aliased) {
        this(alias, aliased, null);
    }

    private ProjectsContacts(String alias, Table<ProjectsContactsRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Sugarcrm_4_12.SUGARCRM_4_12;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<ProjectsContactsRecord> getPrimaryKey() {
        return Keys.KEY_PROJECTS_CONTACTS_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<ProjectsContactsRecord>> getKeys() {
        return Arrays.<UniqueKey<ProjectsContactsRecord>>asList(Keys.KEY_PROJECTS_CONTACTS_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProjectsContacts as(String alias) {
        return new ProjectsContacts(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public ProjectsContacts rename(String name) {
        return new ProjectsContacts(name, null);
    }
}
