/*
 * This file is generated by jOOQ.
*/
package com.sms.sis.db.tables;


import com.sms.sis.db.Keys;
import com.sms.sis.db.Sugarcrm_4_12;
import com.sms.sis.db.tables.records.RolesUsersRecord;

import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RolesUsers extends TableImpl<RolesUsersRecord> {

    private static final long serialVersionUID = 208384448;

    /**
     * The reference instance of <code>sugarcrm_4_12.roles_users</code>
     */
    public static final RolesUsers ROLES_USERS = new RolesUsers();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<RolesUsersRecord> getRecordType() {
        return RolesUsersRecord.class;
    }

    /**
     * The column <code>sugarcrm_4_12.roles_users.id</code>.
     */
    public final TableField<RolesUsersRecord, String> ID = createField("id", org.jooq.impl.SQLDataType.VARCHAR.length(36).nullable(false), this, "");

    /**
     * The column <code>sugarcrm_4_12.roles_users.role_id</code>.
     */
    public final TableField<RolesUsersRecord, String> ROLE_ID = createField("role_id", org.jooq.impl.SQLDataType.VARCHAR.length(36), this, "");

    /**
     * The column <code>sugarcrm_4_12.roles_users.user_id</code>.
     */
    public final TableField<RolesUsersRecord, String> USER_ID = createField("user_id", org.jooq.impl.SQLDataType.VARCHAR.length(36), this, "");

    /**
     * The column <code>sugarcrm_4_12.roles_users.date_modified</code>.
     */
    public final TableField<RolesUsersRecord, Timestamp> DATE_MODIFIED = createField("date_modified", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

    /**
     * The column <code>sugarcrm_4_12.roles_users.deleted</code>.
     */
    public final TableField<RolesUsersRecord, Byte> DELETED = createField("deleted", org.jooq.impl.SQLDataType.TINYINT.defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.TINYINT)), this, "");

    /**
     * Create a <code>sugarcrm_4_12.roles_users</code> table reference
     */
    public RolesUsers() {
        this("roles_users", null);
    }

    /**
     * Create an aliased <code>sugarcrm_4_12.roles_users</code> table reference
     */
    public RolesUsers(String alias) {
        this(alias, ROLES_USERS);
    }

    private RolesUsers(String alias, Table<RolesUsersRecord> aliased) {
        this(alias, aliased, null);
    }

    private RolesUsers(String alias, Table<RolesUsersRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Sugarcrm_4_12.SUGARCRM_4_12;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<RolesUsersRecord> getPrimaryKey() {
        return Keys.KEY_ROLES_USERS_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<RolesUsersRecord>> getKeys() {
        return Arrays.<UniqueKey<RolesUsersRecord>>asList(Keys.KEY_ROLES_USERS_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RolesUsers as(String alias) {
        return new RolesUsers(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public RolesUsers rename(String name) {
        return new RolesUsers(name, null);
    }
}
