/*
 * This file is generated by jOOQ.
*/
package com.sms.sis.db.tables;


import com.sms.sis.db.Keys;
import com.sms.sis.db.Sugarcrm_4_12;
import com.sms.sis.db.tables.records.ScApprovaldetailsRecord;

import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ScApprovaldetails extends TableImpl<ScApprovaldetailsRecord> {

    private static final long serialVersionUID = 829943578;

    /**
     * The reference instance of <code>sugarcrm_4_12.sc_approvaldetails</code>
     */
    public static final ScApprovaldetails SC_APPROVALDETAILS = new ScApprovaldetails();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ScApprovaldetailsRecord> getRecordType() {
        return ScApprovaldetailsRecord.class;
    }

    /**
     * The column <code>sugarcrm_4_12.sc_approvaldetails.id</code>.
     */
    public final TableField<ScApprovaldetailsRecord, String> ID = createField("id", org.jooq.impl.SQLDataType.CHAR.length(36).nullable(false), this, "");

    /**
     * The column <code>sugarcrm_4_12.sc_approvaldetails.name</code>.
     */
    public final TableField<ScApprovaldetailsRecord, String> NAME = createField("name", org.jooq.impl.SQLDataType.VARCHAR.length(255), this, "");

    /**
     * The column <code>sugarcrm_4_12.sc_approvaldetails.date_entered</code>.
     */
    public final TableField<ScApprovaldetailsRecord, Timestamp> DATE_ENTERED = createField("date_entered", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

    /**
     * The column <code>sugarcrm_4_12.sc_approvaldetails.date_modified</code>.
     */
    public final TableField<ScApprovaldetailsRecord, Timestamp> DATE_MODIFIED = createField("date_modified", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

    /**
     * The column <code>sugarcrm_4_12.sc_approvaldetails.modified_user_id</code>.
     */
    public final TableField<ScApprovaldetailsRecord, String> MODIFIED_USER_ID = createField("modified_user_id", org.jooq.impl.SQLDataType.CHAR.length(36), this, "");

    /**
     * The column <code>sugarcrm_4_12.sc_approvaldetails.created_by</code>.
     */
    public final TableField<ScApprovaldetailsRecord, String> CREATED_BY = createField("created_by", org.jooq.impl.SQLDataType.CHAR.length(36), this, "");

    /**
     * The column <code>sugarcrm_4_12.sc_approvaldetails.description</code>.
     */
    public final TableField<ScApprovaldetailsRecord, String> DESCRIPTION = createField("description", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * The column <code>sugarcrm_4_12.sc_approvaldetails.deleted</code>.
     */
    public final TableField<ScApprovaldetailsRecord, Byte> DELETED = createField("deleted", org.jooq.impl.SQLDataType.TINYINT.defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.TINYINT)), this, "");

    /**
     * The column <code>sugarcrm_4_12.sc_approvaldetails.assigned_user_id</code>.
     */
    public final TableField<ScApprovaldetailsRecord, String> ASSIGNED_USER_ID = createField("assigned_user_id", org.jooq.impl.SQLDataType.CHAR.length(36), this, "");

    /**
     * The column <code>sugarcrm_4_12.sc_approvaldetails.service_text</code>.
     */
    public final TableField<ScApprovaldetailsRecord, String> SERVICE_TEXT = createField("service_text", org.jooq.impl.SQLDataType.VARCHAR.length(255), this, "");

    /**
     * The column <code>sugarcrm_4_12.sc_approvaldetails.price</code>.
     */
    public final TableField<ScApprovaldetailsRecord, Double> PRICE = createField("price", org.jooq.impl.SQLDataType.FLOAT, this, "");

    /**
     * The column <code>sugarcrm_4_12.sc_approvaldetails.deduction</code>.
     */
    public final TableField<ScApprovaldetailsRecord, Double> DEDUCTION = createField("deduction", org.jooq.impl.SQLDataType.FLOAT, this, "");

    /**
     * The column <code>sugarcrm_4_12.sc_approvaldetails.copayment</code>.
     */
    public final TableField<ScApprovaldetailsRecord, Double> COPAYMENT = createField("copayment", org.jooq.impl.SQLDataType.FLOAT, this, "");

    /**
     * The column <code>sugarcrm_4_12.sc_approvaldetails.teeth</code>.
     */
    public final TableField<ScApprovaldetailsRecord, String> TEETH = createField("teeth", org.jooq.impl.SQLDataType.VARCHAR.length(255), this, "");

    /**
     * The column <code>sugarcrm_4_12.sc_approvaldetails.net</code>.
     */
    public final TableField<ScApprovaldetailsRecord, Double> NET = createField("net", org.jooq.impl.SQLDataType.FLOAT, this, "");

    /**
     * The column <code>sugarcrm_4_12.sc_approvaldetails.drugs_txt</code>.
     */
    public final TableField<ScApprovaldetailsRecord, String> DRUGS_TXT = createField("drugs_txt", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * The column <code>sugarcrm_4_12.sc_approvaldetails.drugs_duration</code>.
     */
    public final TableField<ScApprovaldetailsRecord, String> DRUGS_DURATION = createField("drugs_duration", org.jooq.impl.SQLDataType.VARCHAR.length(255), this, "");

    /**
     * The column <code>sugarcrm_4_12.sc_approvaldetails.drugs_dose</code>.
     */
    public final TableField<ScApprovaldetailsRecord, String> DRUGS_DOSE = createField("drugs_dose", org.jooq.impl.SQLDataType.VARCHAR.length(255), this, "");

    /**
     * The column <code>sugarcrm_4_12.sc_approvaldetails.drugs_price</code>.
     */
    public final TableField<ScApprovaldetailsRecord, String> DRUGS_PRICE = createField("drugs_price", org.jooq.impl.SQLDataType.VARCHAR.length(255), this, "");

    /**
     * The column <code>sugarcrm_4_12.sc_approvaldetails.cmid</code>.
     */
    public final TableField<ScApprovaldetailsRecord, Integer> CMID = createField("cmid", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>sugarcrm_4_12.sc_approvaldetails.sc_providerservices_id_c</code>.
     */
    public final TableField<ScApprovaldetailsRecord, String> SC_PROVIDERSERVICES_ID_C = createField("sc_providerservices_id_c", org.jooq.impl.SQLDataType.CHAR.length(36), this, "");

    /**
     * The column <code>sugarcrm_4_12.sc_approvaldetails.lengthofstay</code>.
     */
    public final TableField<ScApprovaldetailsRecord, Double> LENGTHOFSTAY = createField("lengthofstay", org.jooq.impl.SQLDataType.FLOAT, this, "");

    /**
     * The column <code>sugarcrm_4_12.sc_approvaldetails.lengthofstayinterval</code>.
     */
    public final TableField<ScApprovaldetailsRecord, String> LENGTHOFSTAYINTERVAL = createField("lengthofstayinterval", org.jooq.impl.SQLDataType.VARCHAR.length(100).defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>sugarcrm_4_12.sc_approvaldetails.accommodationlevel</code>.
     */
    public final TableField<ScApprovaldetailsRecord, String> ACCOMMODATIONLEVEL = createField("accommodationlevel", org.jooq.impl.SQLDataType.VARCHAR.length(255), this, "");

    /**
     * The column <code>sugarcrm_4_12.sc_approvaldetails.ceiling</code>.
     */
    public final TableField<ScApprovaldetailsRecord, Double> CEILING = createField("ceiling", org.jooq.impl.SQLDataType.FLOAT, this, "");

    /**
     * The column <code>sugarcrm_4_12.sc_approvaldetails.physiosessions</code>.
     */
    public final TableField<ScApprovaldetailsRecord, Integer> PHYSIOSESSIONS = createField("physiosessions", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>sugarcrm_4_12.sc_approvaldetails.sent</code>.
     */
    public final TableField<ScApprovaldetailsRecord, Boolean> SENT = createField("sent", org.jooq.impl.SQLDataType.BIT.defaultValue(org.jooq.impl.DSL.inline("b'0'", org.jooq.impl.SQLDataType.BIT)), this, "");

    /**
     * Create a <code>sugarcrm_4_12.sc_approvaldetails</code> table reference
     */
    public ScApprovaldetails() {
        this("sc_approvaldetails", null);
    }

    /**
     * Create an aliased <code>sugarcrm_4_12.sc_approvaldetails</code> table reference
     */
    public ScApprovaldetails(String alias) {
        this(alias, SC_APPROVALDETAILS);
    }

    private ScApprovaldetails(String alias, Table<ScApprovaldetailsRecord> aliased) {
        this(alias, aliased, null);
    }

    private ScApprovaldetails(String alias, Table<ScApprovaldetailsRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Sugarcrm_4_12.SUGARCRM_4_12;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<ScApprovaldetailsRecord> getPrimaryKey() {
        return Keys.KEY_SC_APPROVALDETAILS_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<ScApprovaldetailsRecord>> getKeys() {
        return Arrays.<UniqueKey<ScApprovaldetailsRecord>>asList(Keys.KEY_SC_APPROVALDETAILS_PRIMARY, Keys.KEY_SC_APPROVALDETAILS_CMID_UNIQUE);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ScApprovaldetails as(String alias) {
        return new ScApprovaldetails(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public ScApprovaldetails rename(String name) {
        return new ScApprovaldetails(name, null);
    }
}
