/*
 * This file is generated by jOOQ.
*/
package com.sms.sis.db.tables;


import com.sms.sis.db.Keys;
import com.sms.sis.db.Sugarcrm_4_12;
import com.sms.sis.db.tables.records.ScConstraintsRecord;

import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ScConstraints extends TableImpl<ScConstraintsRecord> {

    private static final long serialVersionUID = 118356279;

    /**
     * The reference instance of <code>sugarcrm_4_12.sc_constraints</code>
     */
    public static final ScConstraints SC_CONSTRAINTS = new ScConstraints();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ScConstraintsRecord> getRecordType() {
        return ScConstraintsRecord.class;
    }

    /**
     * The column <code>sugarcrm_4_12.sc_constraints.id</code>.
     */
    public final TableField<ScConstraintsRecord, String> ID = createField("id", org.jooq.impl.SQLDataType.CHAR.length(36).nullable(false), this, "");

    /**
     * The column <code>sugarcrm_4_12.sc_constraints.name</code>.
     */
    public final TableField<ScConstraintsRecord, String> NAME = createField("name", org.jooq.impl.SQLDataType.VARCHAR.length(255), this, "");

    /**
     * The column <code>sugarcrm_4_12.sc_constraints.date_entered</code>.
     */
    public final TableField<ScConstraintsRecord, Timestamp> DATE_ENTERED = createField("date_entered", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

    /**
     * The column <code>sugarcrm_4_12.sc_constraints.date_modified</code>.
     */
    public final TableField<ScConstraintsRecord, Timestamp> DATE_MODIFIED = createField("date_modified", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

    /**
     * The column <code>sugarcrm_4_12.sc_constraints.modified_user_id</code>.
     */
    public final TableField<ScConstraintsRecord, String> MODIFIED_USER_ID = createField("modified_user_id", org.jooq.impl.SQLDataType.CHAR.length(36), this, "");

    /**
     * The column <code>sugarcrm_4_12.sc_constraints.created_by</code>.
     */
    public final TableField<ScConstraintsRecord, String> CREATED_BY = createField("created_by", org.jooq.impl.SQLDataType.CHAR.length(36), this, "");

    /**
     * The column <code>sugarcrm_4_12.sc_constraints.description</code>.
     */
    public final TableField<ScConstraintsRecord, String> DESCRIPTION = createField("description", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * The column <code>sugarcrm_4_12.sc_constraints.deleted</code>.
     */
    public final TableField<ScConstraintsRecord, Byte> DELETED = createField("deleted", org.jooq.impl.SQLDataType.TINYINT.defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.TINYINT)), this, "");

    /**
     * The column <code>sugarcrm_4_12.sc_constraints.assigned_user_id</code>.
     */
    public final TableField<ScConstraintsRecord, String> ASSIGNED_USER_ID = createField("assigned_user_id", org.jooq.impl.SQLDataType.CHAR.length(36), this, "");

    /**
     * The column <code>sugarcrm_4_12.sc_constraints.constraintlist</code>.
     */
    public final TableField<ScConstraintsRecord, String> CONSTRAINTLIST = createField("constraintlist", org.jooq.impl.SQLDataType.VARCHAR.length(100).defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>sugarcrm_4_12.sc_constraints.rulevalues</code>.
     */
    public final TableField<ScConstraintsRecord, String> RULEVALUES = createField("rulevalues", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * The column <code>sugarcrm_4_12.sc_constraints.data_constraint</code>.
     */
    public final TableField<ScConstraintsRecord, String> DATA_CONSTRAINT = createField("data_constraint", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * Create a <code>sugarcrm_4_12.sc_constraints</code> table reference
     */
    public ScConstraints() {
        this("sc_constraints", null);
    }

    /**
     * Create an aliased <code>sugarcrm_4_12.sc_constraints</code> table reference
     */
    public ScConstraints(String alias) {
        this(alias, SC_CONSTRAINTS);
    }

    private ScConstraints(String alias, Table<ScConstraintsRecord> aliased) {
        this(alias, aliased, null);
    }

    private ScConstraints(String alias, Table<ScConstraintsRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Sugarcrm_4_12.SUGARCRM_4_12;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<ScConstraintsRecord> getPrimaryKey() {
        return Keys.KEY_SC_CONSTRAINTS_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<ScConstraintsRecord>> getKeys() {
        return Arrays.<UniqueKey<ScConstraintsRecord>>asList(Keys.KEY_SC_CONSTRAINTS_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ScConstraints as(String alias) {
        return new ScConstraints(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public ScConstraints rename(String name) {
        return new ScConstraints(name, null);
    }
}
