/*
 * This file is generated by jOOQ.
*/
package com.sms.sis.db.tables;


import com.sms.sis.db.Keys;
import com.sms.sis.db.Sugarcrm_4_12;
import com.sms.sis.db.tables.records.ScDeductionCstmRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ScDeductionCstm extends TableImpl<ScDeductionCstmRecord> {

    private static final long serialVersionUID = -392385986;

    /**
     * The reference instance of <code>sugarcrm_4_12.sc_deduction_cstm</code>
     */
    public static final ScDeductionCstm SC_DEDUCTION_CSTM = new ScDeductionCstm();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ScDeductionCstmRecord> getRecordType() {
        return ScDeductionCstmRecord.class;
    }

    /**
     * The column <code>sugarcrm_4_12.sc_deduction_cstm.id_c</code>.
     */
    public final TableField<ScDeductionCstmRecord, String> ID_C = createField("id_c", org.jooq.impl.SQLDataType.CHAR.length(36).nullable(false), this, "");

    /**
     * Create a <code>sugarcrm_4_12.sc_deduction_cstm</code> table reference
     */
    public ScDeductionCstm() {
        this("sc_deduction_cstm", null);
    }

    /**
     * Create an aliased <code>sugarcrm_4_12.sc_deduction_cstm</code> table reference
     */
    public ScDeductionCstm(String alias) {
        this(alias, SC_DEDUCTION_CSTM);
    }

    private ScDeductionCstm(String alias, Table<ScDeductionCstmRecord> aliased) {
        this(alias, aliased, null);
    }

    private ScDeductionCstm(String alias, Table<ScDeductionCstmRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Sugarcrm_4_12.SUGARCRM_4_12;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<ScDeductionCstmRecord> getPrimaryKey() {
        return Keys.KEY_SC_DEDUCTION_CSTM_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<ScDeductionCstmRecord>> getKeys() {
        return Arrays.<UniqueKey<ScDeductionCstmRecord>>asList(Keys.KEY_SC_DEDUCTION_CSTM_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ScDeductionCstm as(String alias) {
        return new ScDeductionCstm(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public ScDeductionCstm rename(String name) {
        return new ScDeductionCstm(name, null);
    }
}
