/*
 * This file is generated by jOOQ.
*/
package com.sms.sis.db.tables;


import com.sms.sis.db.Keys;
import com.sms.sis.db.Sugarcrm_4_12;
import com.sms.sis.db.tables.records.ScDoctortypeRecord;

import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ScDoctortype extends TableImpl<ScDoctortypeRecord> {

    private static final long serialVersionUID = 639295457;

    /**
     * The reference instance of <code>sugarcrm_4_12.sc_doctortype</code>
     */
    public static final ScDoctortype SC_DOCTORTYPE = new ScDoctortype();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ScDoctortypeRecord> getRecordType() {
        return ScDoctortypeRecord.class;
    }

    /**
     * The column <code>sugarcrm_4_12.sc_doctortype.id</code>.
     */
    public final TableField<ScDoctortypeRecord, String> ID = createField("id", org.jooq.impl.SQLDataType.CHAR.length(36).nullable(false), this, "");

    /**
     * The column <code>sugarcrm_4_12.sc_doctortype.name</code>.
     */
    public final TableField<ScDoctortypeRecord, String> NAME = createField("name", org.jooq.impl.SQLDataType.VARCHAR.length(255), this, "");

    /**
     * The column <code>sugarcrm_4_12.sc_doctortype.date_entered</code>.
     */
    public final TableField<ScDoctortypeRecord, Timestamp> DATE_ENTERED = createField("date_entered", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

    /**
     * The column <code>sugarcrm_4_12.sc_doctortype.date_modified</code>.
     */
    public final TableField<ScDoctortypeRecord, Timestamp> DATE_MODIFIED = createField("date_modified", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

    /**
     * The column <code>sugarcrm_4_12.sc_doctortype.modified_user_id</code>.
     */
    public final TableField<ScDoctortypeRecord, String> MODIFIED_USER_ID = createField("modified_user_id", org.jooq.impl.SQLDataType.CHAR.length(36), this, "");

    /**
     * The column <code>sugarcrm_4_12.sc_doctortype.created_by</code>.
     */
    public final TableField<ScDoctortypeRecord, String> CREATED_BY = createField("created_by", org.jooq.impl.SQLDataType.CHAR.length(36), this, "");

    /**
     * The column <code>sugarcrm_4_12.sc_doctortype.description</code>.
     */
    public final TableField<ScDoctortypeRecord, String> DESCRIPTION = createField("description", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * The column <code>sugarcrm_4_12.sc_doctortype.deleted</code>.
     */
    public final TableField<ScDoctortypeRecord, Byte> DELETED = createField("deleted", org.jooq.impl.SQLDataType.TINYINT.defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.TINYINT)), this, "");

    /**
     * The column <code>sugarcrm_4_12.sc_doctortype.assigned_user_id</code>.
     */
    public final TableField<ScDoctortypeRecord, String> ASSIGNED_USER_ID = createField("assigned_user_id", org.jooq.impl.SQLDataType.CHAR.length(36), this, "");

    /**
     * The column <code>sugarcrm_4_12.sc_doctortype.english_name</code>.
     */
    public final TableField<ScDoctortypeRecord, String> ENGLISH_NAME = createField("english_name", org.jooq.impl.SQLDataType.VARCHAR.length(255), this, "");

    /**
     * The column <code>sugarcrm_4_12.sc_doctortype.remarks</code>.
     */
    public final TableField<ScDoctortypeRecord, String> REMARKS = createField("remarks", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * The column <code>sugarcrm_4_12.sc_doctortype.cmid</code>.
     */
    public final TableField<ScDoctortypeRecord, Integer> CMID = createField("cmid", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * Create a <code>sugarcrm_4_12.sc_doctortype</code> table reference
     */
    public ScDoctortype() {
        this("sc_doctortype", null);
    }

    /**
     * Create an aliased <code>sugarcrm_4_12.sc_doctortype</code> table reference
     */
    public ScDoctortype(String alias) {
        this(alias, SC_DOCTORTYPE);
    }

    private ScDoctortype(String alias, Table<ScDoctortypeRecord> aliased) {
        this(alias, aliased, null);
    }

    private ScDoctortype(String alias, Table<ScDoctortypeRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Sugarcrm_4_12.SUGARCRM_4_12;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<ScDoctortypeRecord> getPrimaryKey() {
        return Keys.KEY_SC_DOCTORTYPE_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<ScDoctortypeRecord>> getKeys() {
        return Arrays.<UniqueKey<ScDoctortypeRecord>>asList(Keys.KEY_SC_DOCTORTYPE_PRIMARY, Keys.KEY_SC_DOCTORTYPE_CMID);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ScDoctortype as(String alias) {
        return new ScDoctortype(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public ScDoctortype rename(String name) {
        return new ScDoctortype(name, null);
    }
}
