/*
 * This file is generated by jOOQ.
*/
package com.sms.sis.db.tables;


import com.sms.sis.db.Keys;
import com.sms.sis.db.Sugarcrm_4_12;
import com.sms.sis.db.tables.records.ScServicessupergroupsRecord;

import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ScServicessupergroups extends TableImpl<ScServicessupergroupsRecord> {

    private static final long serialVersionUID = -1214174221;

    /**
     * The reference instance of <code>sugarcrm_4_12.sc_servicessupergroups</code>
     */
    public static final ScServicessupergroups SC_SERVICESSUPERGROUPS = new ScServicessupergroups();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ScServicessupergroupsRecord> getRecordType() {
        return ScServicessupergroupsRecord.class;
    }

    /**
     * The column <code>sugarcrm_4_12.sc_servicessupergroups.id</code>.
     */
    public final TableField<ScServicessupergroupsRecord, String> ID = createField("id", org.jooq.impl.SQLDataType.CHAR.length(36).nullable(false), this, "");

    /**
     * The column <code>sugarcrm_4_12.sc_servicessupergroups.name</code>.
     */
    public final TableField<ScServicessupergroupsRecord, String> NAME = createField("name", org.jooq.impl.SQLDataType.VARCHAR.length(255), this, "");

    /**
     * The column <code>sugarcrm_4_12.sc_servicessupergroups.date_entered</code>.
     */
    public final TableField<ScServicessupergroupsRecord, Timestamp> DATE_ENTERED = createField("date_entered", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

    /**
     * The column <code>sugarcrm_4_12.sc_servicessupergroups.date_modified</code>.
     */
    public final TableField<ScServicessupergroupsRecord, Timestamp> DATE_MODIFIED = createField("date_modified", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

    /**
     * The column <code>sugarcrm_4_12.sc_servicessupergroups.modified_user_id</code>.
     */
    public final TableField<ScServicessupergroupsRecord, String> MODIFIED_USER_ID = createField("modified_user_id", org.jooq.impl.SQLDataType.CHAR.length(36), this, "");

    /**
     * The column <code>sugarcrm_4_12.sc_servicessupergroups.created_by</code>.
     */
    public final TableField<ScServicessupergroupsRecord, String> CREATED_BY = createField("created_by", org.jooq.impl.SQLDataType.CHAR.length(36), this, "");

    /**
     * The column <code>sugarcrm_4_12.sc_servicessupergroups.description</code>.
     */
    public final TableField<ScServicessupergroupsRecord, String> DESCRIPTION = createField("description", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * The column <code>sugarcrm_4_12.sc_servicessupergroups.deleted</code>.
     */
    public final TableField<ScServicessupergroupsRecord, Byte> DELETED = createField("deleted", org.jooq.impl.SQLDataType.TINYINT.defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.TINYINT)), this, "");

    /**
     * The column <code>sugarcrm_4_12.sc_servicessupergroups.assigned_user_id</code>.
     */
    public final TableField<ScServicessupergroupsRecord, String> ASSIGNED_USER_ID = createField("assigned_user_id", org.jooq.impl.SQLDataType.CHAR.length(36), this, "");

    /**
     * The column <code>sugarcrm_4_12.sc_servicessupergroups.remarks</code>.
     */
    public final TableField<ScServicessupergroupsRecord, String> REMARKS = createField("remarks", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * The column <code>sugarcrm_4_12.sc_servicessupergroups.english_name</code>.
     */
    public final TableField<ScServicessupergroupsRecord, String> ENGLISH_NAME = createField("english_name", org.jooq.impl.SQLDataType.VARCHAR.length(255), this, "");

    /**
     * The column <code>sugarcrm_4_12.sc_servicessupergroups.cmid</code>.
     */
    public final TableField<ScServicessupergroupsRecord, Integer> CMID = createField("cmid", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * Create a <code>sugarcrm_4_12.sc_servicessupergroups</code> table reference
     */
    public ScServicessupergroups() {
        this("sc_servicessupergroups", null);
    }

    /**
     * Create an aliased <code>sugarcrm_4_12.sc_servicessupergroups</code> table reference
     */
    public ScServicessupergroups(String alias) {
        this(alias, SC_SERVICESSUPERGROUPS);
    }

    private ScServicessupergroups(String alias, Table<ScServicessupergroupsRecord> aliased) {
        this(alias, aliased, null);
    }

    private ScServicessupergroups(String alias, Table<ScServicessupergroupsRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Sugarcrm_4_12.SUGARCRM_4_12;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<ScServicessupergroupsRecord> getPrimaryKey() {
        return Keys.KEY_SC_SERVICESSUPERGROUPS_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<ScServicessupergroupsRecord>> getKeys() {
        return Arrays.<UniqueKey<ScServicessupergroupsRecord>>asList(Keys.KEY_SC_SERVICESSUPERGROUPS_PRIMARY, Keys.KEY_SC_SERVICESSUPERGROUPS_CMID);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ScServicessupergroups as(String alias) {
        return new ScServicessupergroups(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public ScServicessupergroups rename(String name) {
        return new ScServicessupergroups(name, null);
    }
}
