/*
 * This file is generated by jOOQ.
*/
package com.sms.sis.db.tables;


import com.sms.sis.db.Keys;
import com.sms.sis.db.Sugarcrm_4_12;
import com.sms.sis.db.tables.records.SsBanksSsOutgoingChecksCRecord;

import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SsBanksSsOutgoingChecksC extends TableImpl<SsBanksSsOutgoingChecksCRecord> {

    private static final long serialVersionUID = -1552047171;

    /**
     * The reference instance of <code>sugarcrm_4_12.ss_banks_ss_outgoing_checks_c</code>
     */
    public static final SsBanksSsOutgoingChecksC SS_BANKS_SS_OUTGOING_CHECKS_C = new SsBanksSsOutgoingChecksC();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<SsBanksSsOutgoingChecksCRecord> getRecordType() {
        return SsBanksSsOutgoingChecksCRecord.class;
    }

    /**
     * The column <code>sugarcrm_4_12.ss_banks_ss_outgoing_checks_c.id</code>.
     */
    public final TableField<SsBanksSsOutgoingChecksCRecord, String> ID = createField("id", org.jooq.impl.SQLDataType.VARCHAR.length(36).nullable(false), this, "");

    /**
     * The column <code>sugarcrm_4_12.ss_banks_ss_outgoing_checks_c.date_modified</code>.
     */
    public final TableField<SsBanksSsOutgoingChecksCRecord, Timestamp> DATE_MODIFIED = createField("date_modified", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

    /**
     * The column <code>sugarcrm_4_12.ss_banks_ss_outgoing_checks_c.deleted</code>.
     */
    public final TableField<SsBanksSsOutgoingChecksCRecord, Byte> DELETED = createField("deleted", org.jooq.impl.SQLDataType.TINYINT.defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.TINYINT)), this, "");

    /**
     * The column <code>sugarcrm_4_12.ss_banks_ss_outgoing_checks_c.ss_banks_ss_outgoing_checksss_banks_ida</code>.
     */
    public final TableField<SsBanksSsOutgoingChecksCRecord, String> SS_BANKS_SS_OUTGOING_CHECKSSS_BANKS_IDA = createField("ss_banks_ss_outgoing_checksss_banks_ida", org.jooq.impl.SQLDataType.VARCHAR.length(36), this, "");

    /**
     * The column <code>sugarcrm_4_12.ss_banks_ss_outgoing_checks_c.ss_banks_ss_outgoing_checksss_outgoing_checks_idb</code>.
     */
    public final TableField<SsBanksSsOutgoingChecksCRecord, String> SS_BANKS_SS_OUTGOING_CHECKSSS_OUTGOING_CHECKS_IDB = createField("ss_banks_ss_outgoing_checksss_outgoing_checks_idb", org.jooq.impl.SQLDataType.VARCHAR.length(36), this, "");

    /**
     * Create a <code>sugarcrm_4_12.ss_banks_ss_outgoing_checks_c</code> table reference
     */
    public SsBanksSsOutgoingChecksC() {
        this("ss_banks_ss_outgoing_checks_c", null);
    }

    /**
     * Create an aliased <code>sugarcrm_4_12.ss_banks_ss_outgoing_checks_c</code> table reference
     */
    public SsBanksSsOutgoingChecksC(String alias) {
        this(alias, SS_BANKS_SS_OUTGOING_CHECKS_C);
    }

    private SsBanksSsOutgoingChecksC(String alias, Table<SsBanksSsOutgoingChecksCRecord> aliased) {
        this(alias, aliased, null);
    }

    private SsBanksSsOutgoingChecksC(String alias, Table<SsBanksSsOutgoingChecksCRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Sugarcrm_4_12.SUGARCRM_4_12;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<SsBanksSsOutgoingChecksCRecord> getPrimaryKey() {
        return Keys.KEY_SS_BANKS_SS_OUTGOING_CHECKS_C_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<SsBanksSsOutgoingChecksCRecord>> getKeys() {
        return Arrays.<UniqueKey<SsBanksSsOutgoingChecksCRecord>>asList(Keys.KEY_SS_BANKS_SS_OUTGOING_CHECKS_C_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SsBanksSsOutgoingChecksC as(String alias) {
        return new SsBanksSsOutgoingChecksC(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public SsBanksSsOutgoingChecksC rename(String name) {
        return new SsBanksSsOutgoingChecksC(name, null);
    }
}
