/*
 * This file is generated by jOOQ.
*/
package com.sms.sis.db.tables;


import com.sms.sis.db.Keys;
import com.sms.sis.db.Sugarcrm_4_12;
import com.sms.sis.db.tables.records.SsBSTemplateDetailsRecord;

import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SsBSTemplateDetails extends TableImpl<SsBSTemplateDetailsRecord> {

    private static final long serialVersionUID = 970305055;

    /**
     * The reference instance of <code>sugarcrm_4_12.ss_b_s_template_details</code>
     */
    public static final SsBSTemplateDetails SS_B_S_TEMPLATE_DETAILS = new SsBSTemplateDetails();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<SsBSTemplateDetailsRecord> getRecordType() {
        return SsBSTemplateDetailsRecord.class;
    }

    /**
     * The column <code>sugarcrm_4_12.ss_b_s_template_details.id</code>.
     */
    public final TableField<SsBSTemplateDetailsRecord, String> ID = createField("id", org.jooq.impl.SQLDataType.CHAR.length(36).nullable(false), this, "");

    /**
     * The column <code>sugarcrm_4_12.ss_b_s_template_details.name</code>.
     */
    public final TableField<SsBSTemplateDetailsRecord, String> NAME = createField("name", org.jooq.impl.SQLDataType.VARCHAR.length(255), this, "");

    /**
     * The column <code>sugarcrm_4_12.ss_b_s_template_details.date_entered</code>.
     */
    public final TableField<SsBSTemplateDetailsRecord, Timestamp> DATE_ENTERED = createField("date_entered", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

    /**
     * The column <code>sugarcrm_4_12.ss_b_s_template_details.date_modified</code>.
     */
    public final TableField<SsBSTemplateDetailsRecord, Timestamp> DATE_MODIFIED = createField("date_modified", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

    /**
     * The column <code>sugarcrm_4_12.ss_b_s_template_details.modified_user_id</code>.
     */
    public final TableField<SsBSTemplateDetailsRecord, String> MODIFIED_USER_ID = createField("modified_user_id", org.jooq.impl.SQLDataType.CHAR.length(36), this, "");

    /**
     * The column <code>sugarcrm_4_12.ss_b_s_template_details.created_by</code>.
     */
    public final TableField<SsBSTemplateDetailsRecord, String> CREATED_BY = createField("created_by", org.jooq.impl.SQLDataType.CHAR.length(36), this, "");

    /**
     * The column <code>sugarcrm_4_12.ss_b_s_template_details.description</code>.
     */
    public final TableField<SsBSTemplateDetailsRecord, String> DESCRIPTION = createField("description", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * The column <code>sugarcrm_4_12.ss_b_s_template_details.deleted</code>.
     */
    public final TableField<SsBSTemplateDetailsRecord, Byte> DELETED = createField("deleted", org.jooq.impl.SQLDataType.TINYINT.defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.TINYINT)), this, "");

    /**
     * The column <code>sugarcrm_4_12.ss_b_s_template_details.assigned_user_id</code>.
     */
    public final TableField<SsBSTemplateDetailsRecord, String> ASSIGNED_USER_ID = createField("assigned_user_id", org.jooq.impl.SQLDataType.CHAR.length(36), this, "");

    /**
     * The column <code>sugarcrm_4_12.ss_b_s_template_details.section</code>.
     */
    public final TableField<SsBSTemplateDetailsRecord, String> SECTION = createField("section", org.jooq.impl.SQLDataType.VARCHAR.length(100).defaultValue(org.jooq.impl.DSL.inline("longterm_assets", org.jooq.impl.SQLDataType.VARCHAR)), this, "");

    /**
     * Create a <code>sugarcrm_4_12.ss_b_s_template_details</code> table reference
     */
    public SsBSTemplateDetails() {
        this("ss_b_s_template_details", null);
    }

    /**
     * Create an aliased <code>sugarcrm_4_12.ss_b_s_template_details</code> table reference
     */
    public SsBSTemplateDetails(String alias) {
        this(alias, SS_B_S_TEMPLATE_DETAILS);
    }

    private SsBSTemplateDetails(String alias, Table<SsBSTemplateDetailsRecord> aliased) {
        this(alias, aliased, null);
    }

    private SsBSTemplateDetails(String alias, Table<SsBSTemplateDetailsRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Sugarcrm_4_12.SUGARCRM_4_12;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<SsBSTemplateDetailsRecord> getPrimaryKey() {
        return Keys.KEY_SS_B_S_TEMPLATE_DETAILS_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<SsBSTemplateDetailsRecord>> getKeys() {
        return Arrays.<UniqueKey<SsBSTemplateDetailsRecord>>asList(Keys.KEY_SS_B_S_TEMPLATE_DETAILS_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SsBSTemplateDetails as(String alias) {
        return new SsBSTemplateDetails(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public SsBSTemplateDetails rename(String name) {
        return new SsBSTemplateDetails(name, null);
    }
}
