/*
 * This file is generated by jOOQ.
*/
package com.sms.sis.db.tables;


import com.sms.sis.db.Keys;
import com.sms.sis.db.Sugarcrm_4_12;
import com.sms.sis.db.tables.records.SsBSTemplateDetailsSsGlAccountCRecord;

import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SsBSTemplateDetailsSsGlAccountC extends TableImpl<SsBSTemplateDetailsSsGlAccountCRecord> {

    private static final long serialVersionUID = 859711172;

    /**
     * The reference instance of <code>sugarcrm_4_12.ss_b_s_template_details_ss_gl_account_c</code>
     */
    public static final SsBSTemplateDetailsSsGlAccountC SS_B_S_TEMPLATE_DETAILS_SS_GL_ACCOUNT_C = new SsBSTemplateDetailsSsGlAccountC();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<SsBSTemplateDetailsSsGlAccountCRecord> getRecordType() {
        return SsBSTemplateDetailsSsGlAccountCRecord.class;
    }

    /**
     * The column <code>sugarcrm_4_12.ss_b_s_template_details_ss_gl_account_c.id</code>.
     */
    public final TableField<SsBSTemplateDetailsSsGlAccountCRecord, String> ID = createField("id", org.jooq.impl.SQLDataType.VARCHAR.length(36).nullable(false), this, "");

    /**
     * The column <code>sugarcrm_4_12.ss_b_s_template_details_ss_gl_account_c.date_modified</code>.
     */
    public final TableField<SsBSTemplateDetailsSsGlAccountCRecord, Timestamp> DATE_MODIFIED = createField("date_modified", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

    /**
     * The column <code>sugarcrm_4_12.ss_b_s_template_details_ss_gl_account_c.deleted</code>.
     */
    public final TableField<SsBSTemplateDetailsSsGlAccountCRecord, Byte> DELETED = createField("deleted", org.jooq.impl.SQLDataType.TINYINT.defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.TINYINT)), this, "");

    /**
     * The column <code>sugarcrm_4_12.ss_b_s_template_details_ss_gl_account_c.ss_b_s_template_details_ss_gl_accountss_b_s_template_details_ida</code>.
     */
    public final TableField<SsBSTemplateDetailsSsGlAccountCRecord, String> SS_B_S_TEMPLATE_DETAILS_SS_GL_ACCOUNTSS_B_S_TEMPLATE_DETAILS_IDA = createField("ss_b_s_template_details_ss_gl_accountss_b_s_template_details_ida", org.jooq.impl.SQLDataType.VARCHAR.length(36), this, "");

    /**
     * The column <code>sugarcrm_4_12.ss_b_s_template_details_ss_gl_account_c.ss_b_s_template_details_ss_gl_accountss_gl_account_idb</code>.
     */
    public final TableField<SsBSTemplateDetailsSsGlAccountCRecord, String> SS_B_S_TEMPLATE_DETAILS_SS_GL_ACCOUNTSS_GL_ACCOUNT_IDB = createField("ss_b_s_template_details_ss_gl_accountss_gl_account_idb", org.jooq.impl.SQLDataType.VARCHAR.length(36), this, "");

    /**
     * Create a <code>sugarcrm_4_12.ss_b_s_template_details_ss_gl_account_c</code> table reference
     */
    public SsBSTemplateDetailsSsGlAccountC() {
        this("ss_b_s_template_details_ss_gl_account_c", null);
    }

    /**
     * Create an aliased <code>sugarcrm_4_12.ss_b_s_template_details_ss_gl_account_c</code> table reference
     */
    public SsBSTemplateDetailsSsGlAccountC(String alias) {
        this(alias, SS_B_S_TEMPLATE_DETAILS_SS_GL_ACCOUNT_C);
    }

    private SsBSTemplateDetailsSsGlAccountC(String alias, Table<SsBSTemplateDetailsSsGlAccountCRecord> aliased) {
        this(alias, aliased, null);
    }

    private SsBSTemplateDetailsSsGlAccountC(String alias, Table<SsBSTemplateDetailsSsGlAccountCRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Sugarcrm_4_12.SUGARCRM_4_12;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<SsBSTemplateDetailsSsGlAccountCRecord> getPrimaryKey() {
        return Keys.KEY_SS_B_S_TEMPLATE_DETAILS_SS_GL_ACCOUNT_C_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<SsBSTemplateDetailsSsGlAccountCRecord>> getKeys() {
        return Arrays.<UniqueKey<SsBSTemplateDetailsSsGlAccountCRecord>>asList(Keys.KEY_SS_B_S_TEMPLATE_DETAILS_SS_GL_ACCOUNT_C_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SsBSTemplateDetailsSsGlAccountC as(String alias) {
        return new SsBSTemplateDetailsSsGlAccountC(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public SsBSTemplateDetailsSsGlAccountC rename(String name) {
        return new SsBSTemplateDetailsSsGlAccountC(name, null);
    }
}
