/*
 * This file is generated by jOOQ.
*/
package com.sms.sis.db.tables;


import com.sms.sis.db.Keys;
import com.sms.sis.db.Sugarcrm_4_12;
import com.sms.sis.db.tables.records.TasksCstmRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TasksCstm extends TableImpl<TasksCstmRecord> {

    private static final long serialVersionUID = -66309527;

    /**
     * The reference instance of <code>sugarcrm_4_12.tasks_cstm</code>
     */
    public static final TasksCstm TASKS_CSTM = new TasksCstm();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<TasksCstmRecord> getRecordType() {
        return TasksCstmRecord.class;
    }

    /**
     * The column <code>sugarcrm_4_12.tasks_cstm.id_c</code>.
     */
    public final TableField<TasksCstmRecord, String> ID_C = createField("id_c", org.jooq.impl.SQLDataType.CHAR.length(36).nullable(false), this, "");

    /**
     * The column <code>sugarcrm_4_12.tasks_cstm.approvaltype_c</code>.
     */
    public final TableField<TasksCstmRecord, String> APPROVALTYPE_C = createField("approvaltype_c", org.jooq.impl.SQLDataType.VARCHAR.length(100).defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>sugarcrm_4_12.tasks_cstm.emailid_c</code>.
     */
    public final TableField<TasksCstmRecord, String> EMAILID_C = createField("emailid_c", org.jooq.impl.SQLDataType.VARCHAR.length(255), this, "");

    /**
     * Create a <code>sugarcrm_4_12.tasks_cstm</code> table reference
     */
    public TasksCstm() {
        this("tasks_cstm", null);
    }

    /**
     * Create an aliased <code>sugarcrm_4_12.tasks_cstm</code> table reference
     */
    public TasksCstm(String alias) {
        this(alias, TASKS_CSTM);
    }

    private TasksCstm(String alias, Table<TasksCstmRecord> aliased) {
        this(alias, aliased, null);
    }

    private TasksCstm(String alias, Table<TasksCstmRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Sugarcrm_4_12.SUGARCRM_4_12;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<TasksCstmRecord> getPrimaryKey() {
        return Keys.KEY_TASKS_CSTM_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<TasksCstmRecord>> getKeys() {
        return Arrays.<UniqueKey<TasksCstmRecord>>asList(Keys.KEY_TASKS_CSTM_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TasksCstm as(String alias) {
        return new TasksCstm(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public TasksCstm rename(String name) {
        return new TasksCstm(name, null);
    }
}
