/*
 * This file is generated by jOOQ.
*/
package com.sms.sis.db.tables;


import com.sms.sis.db.Keys;
import com.sms.sis.db.Sugarcrm_4_12;
import com.sms.sis.db.tables.records.UpgradeHistoryRecord;

import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UpgradeHistory extends TableImpl<UpgradeHistoryRecord> {

    private static final long serialVersionUID = -287224849;

    /**
     * The reference instance of <code>sugarcrm_4_12.upgrade_history</code>
     */
    public static final UpgradeHistory UPGRADE_HISTORY = new UpgradeHistory();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<UpgradeHistoryRecord> getRecordType() {
        return UpgradeHistoryRecord.class;
    }

    /**
     * The column <code>sugarcrm_4_12.upgrade_history.id</code>.
     */
    public final TableField<UpgradeHistoryRecord, String> ID = createField("id", org.jooq.impl.SQLDataType.CHAR.length(36).nullable(false), this, "");

    /**
     * The column <code>sugarcrm_4_12.upgrade_history.filename</code>.
     */
    public final TableField<UpgradeHistoryRecord, String> FILENAME = createField("filename", org.jooq.impl.SQLDataType.VARCHAR.length(255), this, "");

    /**
     * The column <code>sugarcrm_4_12.upgrade_history.md5sum</code>.
     */
    public final TableField<UpgradeHistoryRecord, String> MD5SUM = createField("md5sum", org.jooq.impl.SQLDataType.VARCHAR.length(32), this, "");

    /**
     * The column <code>sugarcrm_4_12.upgrade_history.type</code>.
     */
    public final TableField<UpgradeHistoryRecord, String> TYPE = createField("type", org.jooq.impl.SQLDataType.VARCHAR.length(30), this, "");

    /**
     * The column <code>sugarcrm_4_12.upgrade_history.status</code>.
     */
    public final TableField<UpgradeHistoryRecord, String> STATUS = createField("status", org.jooq.impl.SQLDataType.VARCHAR.length(50), this, "");

    /**
     * The column <code>sugarcrm_4_12.upgrade_history.version</code>.
     */
    public final TableField<UpgradeHistoryRecord, String> VERSION = createField("version", org.jooq.impl.SQLDataType.VARCHAR.length(64), this, "");

    /**
     * The column <code>sugarcrm_4_12.upgrade_history.name</code>.
     */
    public final TableField<UpgradeHistoryRecord, String> NAME = createField("name", org.jooq.impl.SQLDataType.VARCHAR.length(255), this, "");

    /**
     * The column <code>sugarcrm_4_12.upgrade_history.description</code>.
     */
    public final TableField<UpgradeHistoryRecord, String> DESCRIPTION = createField("description", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * The column <code>sugarcrm_4_12.upgrade_history.id_name</code>.
     */
    public final TableField<UpgradeHistoryRecord, String> ID_NAME = createField("id_name", org.jooq.impl.SQLDataType.VARCHAR.length(255), this, "");

    /**
     * The column <code>sugarcrm_4_12.upgrade_history.manifest</code>.
     */
    public final TableField<UpgradeHistoryRecord, String> MANIFEST = createField("manifest", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * The column <code>sugarcrm_4_12.upgrade_history.date_entered</code>.
     */
    public final TableField<UpgradeHistoryRecord, Timestamp> DATE_ENTERED = createField("date_entered", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

    /**
     * The column <code>sugarcrm_4_12.upgrade_history.enabled</code>.
     */
    public final TableField<UpgradeHistoryRecord, Byte> ENABLED = createField("enabled", org.jooq.impl.SQLDataType.TINYINT.defaultValue(org.jooq.impl.DSL.inline("1", org.jooq.impl.SQLDataType.TINYINT)), this, "");

    /**
     * Create a <code>sugarcrm_4_12.upgrade_history</code> table reference
     */
    public UpgradeHistory() {
        this("upgrade_history", null);
    }

    /**
     * Create an aliased <code>sugarcrm_4_12.upgrade_history</code> table reference
     */
    public UpgradeHistory(String alias) {
        this(alias, UPGRADE_HISTORY);
    }

    private UpgradeHistory(String alias, Table<UpgradeHistoryRecord> aliased) {
        this(alias, aliased, null);
    }

    private UpgradeHistory(String alias, Table<UpgradeHistoryRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Sugarcrm_4_12.SUGARCRM_4_12;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<UpgradeHistoryRecord> getPrimaryKey() {
        return Keys.KEY_UPGRADE_HISTORY_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<UpgradeHistoryRecord>> getKeys() {
        return Arrays.<UniqueKey<UpgradeHistoryRecord>>asList(Keys.KEY_UPGRADE_HISTORY_PRIMARY, Keys.KEY_UPGRADE_HISTORY_UPGRADE_HISTORY_MD5_UK);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UpgradeHistory as(String alias) {
        return new UpgradeHistory(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public UpgradeHistory rename(String name) {
        return new UpgradeHistory(name, null);
    }
}
