/*
 * This file is generated by jOOQ.
*/
package com.sms.sis.db.tables;


import com.sms.sis.db.Sugarcrm_4_12;
import com.sms.sis.db.tables.records.UsersFeedsRecord;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UsersFeeds extends TableImpl<UsersFeedsRecord> {

    private static final long serialVersionUID = 2013505604;

    /**
     * The reference instance of <code>sugarcrm_4_12.users_feeds</code>
     */
    public static final UsersFeeds USERS_FEEDS = new UsersFeeds();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<UsersFeedsRecord> getRecordType() {
        return UsersFeedsRecord.class;
    }

    /**
     * The column <code>sugarcrm_4_12.users_feeds.user_id</code>.
     */
    public final TableField<UsersFeedsRecord, String> USER_ID = createField("user_id", org.jooq.impl.SQLDataType.VARCHAR.length(36), this, "");

    /**
     * The column <code>sugarcrm_4_12.users_feeds.feed_id</code>.
     */
    public final TableField<UsersFeedsRecord, String> FEED_ID = createField("feed_id", org.jooq.impl.SQLDataType.VARCHAR.length(36), this, "");

    /**
     * The column <code>sugarcrm_4_12.users_feeds.rank</code>.
     */
    public final TableField<UsersFeedsRecord, Integer> RANK = createField("rank", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>sugarcrm_4_12.users_feeds.date_modified</code>.
     */
    public final TableField<UsersFeedsRecord, Timestamp> DATE_MODIFIED = createField("date_modified", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

    /**
     * The column <code>sugarcrm_4_12.users_feeds.deleted</code>.
     */
    public final TableField<UsersFeedsRecord, Byte> DELETED = createField("deleted", org.jooq.impl.SQLDataType.TINYINT.defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.TINYINT)), this, "");

    /**
     * Create a <code>sugarcrm_4_12.users_feeds</code> table reference
     */
    public UsersFeeds() {
        this("users_feeds", null);
    }

    /**
     * Create an aliased <code>sugarcrm_4_12.users_feeds</code> table reference
     */
    public UsersFeeds(String alias) {
        this(alias, USERS_FEEDS);
    }

    private UsersFeeds(String alias, Table<UsersFeedsRecord> aliased) {
        this(alias, aliased, null);
    }

    private UsersFeeds(String alias, Table<UsersFeedsRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Sugarcrm_4_12.SUGARCRM_4_12;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UsersFeeds as(String alias) {
        return new UsersFeeds(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public UsersFeeds rename(String name) {
        return new UsersFeeds(name, null);
    }
}
