/*
 * This file is generated by jOOQ.
*/
package com.sms.sis.db;


import com.sms.sis.db.tables.Accounts;
import com.sms.sis.db.tables.AccountsAudit;
import com.sms.sis.db.tables.AccountsBugs;
import com.sms.sis.db.tables.AccountsCases;
import com.sms.sis.db.tables.AccountsContacts;
import com.sms.sis.db.tables.AccountsCstm;
import com.sms.sis.db.tables.AccountsOpportunities;
import com.sms.sis.db.tables.AclActions;
import com.sms.sis.db.tables.AclRoles;
import com.sms.sis.db.tables.AclRolesActions;
import com.sms.sis.db.tables.AclRolesUsers;
import com.sms.sis.db.tables.AddressBook;
import com.sms.sis.db.tables.Approvaldetailsutilizationtable;
import com.sms.sis.db.tables.AreasFix_5;
import com.sms.sis.db.tables.AsteriskLog;
import com.sms.sis.db.tables.Bugs;
import com.sms.sis.db.tables.BugsAudit;
import com.sms.sis.db.tables.Calls;
import com.sms.sis.db.tables.CallsContacts;
import com.sms.sis.db.tables.CallsCstm;
import com.sms.sis.db.tables.CallsLeads;
import com.sms.sis.db.tables.CallsUsers;
import com.sms.sis.db.tables.CampaignLog;
import com.sms.sis.db.tables.CampaignTrkrs;
import com.sms.sis.db.tables.Campaigns;
import com.sms.sis.db.tables.CampaignsAudit;
import com.sms.sis.db.tables.Cases;
import com.sms.sis.db.tables.CasesAudit;
import com.sms.sis.db.tables.CasesBugs;
import com.sms.sis.db.tables.Claimdetailsutilizationtable;
import com.sms.sis.db.tables.Config;
import com.sms.sis.db.tables.ConstraintstructureLog;
import com.sms.sis.db.tables.Contacts;
import com.sms.sis.db.tables.ContactsAudit;
import com.sms.sis.db.tables.ContactsBugs;
import com.sms.sis.db.tables.ContactsCases;
import com.sms.sis.db.tables.ContactsCstm;
import com.sms.sis.db.tables.ContactsUsers;
import com.sms.sis.db.tables.CronRemoveDocuments;
import com.sms.sis.db.tables.Currencies;
import com.sms.sis.db.tables.CustomFields;
import com.sms.sis.db.tables.DmBocs;
import com.sms.sis.db.tables.DmBocsAudit;
import com.sms.sis.db.tables.DmBocsScPatchesC;
import com.sms.sis.db.tables.DocumentRevisions;
import com.sms.sis.db.tables.Documents;
import com.sms.sis.db.tables.DocumentsAccounts;
import com.sms.sis.db.tables.DocumentsBugs;
import com.sms.sis.db.tables.DocumentsCases;
import com.sms.sis.db.tables.DocumentsContacts;
import com.sms.sis.db.tables.DocumentsOpportunities;
import com.sms.sis.db.tables.Eapm;
import com.sms.sis.db.tables.EmailAddrBeanRel;
import com.sms.sis.db.tables.EmailAddresses;
import com.sms.sis.db.tables.EmailCache;
import com.sms.sis.db.tables.EmailMarketing;
import com.sms.sis.db.tables.EmailMarketingProspectLists;
import com.sms.sis.db.tables.EmailTemplates;
import com.sms.sis.db.tables.Emailman;
import com.sms.sis.db.tables.Emails;
import com.sms.sis.db.tables.EmailsBeans;
import com.sms.sis.db.tables.EmailsEmailAddrRel;
import com.sms.sis.db.tables.EmailsText;
import com.sms.sis.db.tables.FieldsMetaData;
import com.sms.sis.db.tables.Folders;
import com.sms.sis.db.tables.FoldersRel;
import com.sms.sis.db.tables.FoldersSubscriptions;
import com.sms.sis.db.tables.ImportMaps;
import com.sms.sis.db.tables.InboundEmail;
import com.sms.sis.db.tables.InboundEmailAutoreply;
import com.sms.sis.db.tables.InboundEmailCacheTs;
import com.sms.sis.db.tables.JobQueue;
import com.sms.sis.db.tables.Leads;
import com.sms.sis.db.tables.LeadsAudit;
import com.sms.sis.db.tables.LinkedDocuments;
import com.sms.sis.db.tables.Meetings;
import com.sms.sis.db.tables.MeetingsContacts;
import com.sms.sis.db.tables.MeetingsLeads;
import com.sms.sis.db.tables.MeetingsUsers;
import com.sms.sis.db.tables.Notes;
import com.sms.sis.db.tables.OauthConsumer;
import com.sms.sis.db.tables.OauthNonce;
import com.sms.sis.db.tables.OauthTokens;
import com.sms.sis.db.tables.Opportunities;
import com.sms.sis.db.tables.OpportunitiesAudit;
import com.sms.sis.db.tables.OpportunitiesContacts;
import com.sms.sis.db.tables.OutboundEmail;
import com.sms.sis.db.tables.Project;
import com.sms.sis.db.tables.ProjectTask;
import com.sms.sis.db.tables.ProjectTaskAudit;
import com.sms.sis.db.tables.ProjectsAccounts;
import com.sms.sis.db.tables.ProjectsBugs;
import com.sms.sis.db.tables.ProjectsCases;
import com.sms.sis.db.tables.ProjectsContacts;
import com.sms.sis.db.tables.ProjectsOpportunities;
import com.sms.sis.db.tables.ProjectsProducts;
import com.sms.sis.db.tables.ProspectListCampaigns;
import com.sms.sis.db.tables.ProspectLists;
import com.sms.sis.db.tables.ProspectListsProspects;
import com.sms.sis.db.tables.Prospects;
import com.sms.sis.db.tables.Relationships;
import com.sms.sis.db.tables.Releases;
import com.sms.sis.db.tables.Roles;
import com.sms.sis.db.tables.RolesModules;
import com.sms.sis.db.tables.RolesUsers;
import com.sms.sis.db.tables.SavedSearch;
import com.sms.sis.db.tables.ScAccountoperators;
import com.sms.sis.db.tables.ScAccountoperatorsAccountsC;
import com.sms.sis.db.tables.ScAccountoperatorsAudit;
import com.sms.sis.db.tables.ScAccountoperatorsCallsC;
import com.sms.sis.db.tables.ScAccountoperatorsScClaimsC;
import com.sms.sis.db.tables.ScAccountoperatorsScCompanycontractsC;
import com.sms.sis.db.tables.ScAccountoperatorsUsersC;
import com.sms.sis.db.tables.ScApprovaldetails;
import com.sms.sis.db.tables.ScApprovaldetailsAudit;
import com.sms.sis.db.tables.ScApprovaldetailsdrugs;
import com.sms.sis.db.tables.ScApprovaldetailsdrugsAudit;
import com.sms.sis.db.tables.ScApprovaldetailsdrugsScApprovaldetailsC;
import com.sms.sis.db.tables.ScApprovals;
import com.sms.sis.db.tables.ScApprovalsAudit;
import com.sms.sis.db.tables.ScApprovalsCallsC;
import com.sms.sis.db.tables.ScApprovalsScApprovaldetailsC;
import com.sms.sis.db.tables.ScApprovalsScPatientsC;
import com.sms.sis.db.tables.ScApprovalsScProvidersC;
import com.sms.sis.db.tables.ScApprovalsTasksC;
import com.sms.sis.db.tables.ScAreas;
import com.sms.sis.db.tables.ScAreasAccountsC;
import com.sms.sis.db.tables.ScAreasAudit;
import com.sms.sis.db.tables.ScClaimdetails;
import com.sms.sis.db.tables.ScClaimdetailsAudit;
import com.sms.sis.db.tables.ScClaims;
import com.sms.sis.db.tables.ScClaimsAudit;
import com.sms.sis.db.tables.ScClaimsScApprovalsC;
import com.sms.sis.db.tables.ScClaimsScClaimdetailsC;
import com.sms.sis.db.tables.ScClasses;
import com.sms.sis.db.tables.ScClassesAudit;
import com.sms.sis.db.tables.ScCompanies;
import com.sms.sis.db.tables.ScCompaniesAudit;
import com.sms.sis.db.tables.ScCompaniesScCompanycontractsC;
import com.sms.sis.db.tables.ScCompaniesScPatientsC;
import com.sms.sis.db.tables.ScCompanycontracts;
import com.sms.sis.db.tables.ScCompanycontractsAccountsC;
import com.sms.sis.db.tables.ScCompanycontractsAudit;
import com.sms.sis.db.tables.ScCompanycontractsScConstraintsC;
import com.sms.sis.db.tables.ScCompanycontractsScContractsClassesC;
import com.sms.sis.db.tables.ScConstraints;
import com.sms.sis.db.tables.ScConstraintsAudit;
import com.sms.sis.db.tables.ScConstraintsScCompanycontractsC;
import com.sms.sis.db.tables.ScConstraintsScContractsClassesC;
import com.sms.sis.db.tables.ScContractsClasses;
import com.sms.sis.db.tables.ScContractsClassesAudit;
import com.sms.sis.db.tables.ScContractsClassesScContractsclassgroupC;
import com.sms.sis.db.tables.ScContractsClassesScContractsclassserviceC;
import com.sms.sis.db.tables.ScContractsClassesScContractsclasssupergroupC;
import com.sms.sis.db.tables.ScContractsClassesScPatientsC;
import com.sms.sis.db.tables.ScContractsTypes;
import com.sms.sis.db.tables.ScContractsTypesAudit;
import com.sms.sis.db.tables.ScContractsclassgroup;
import com.sms.sis.db.tables.ScContractsclassgroupAudit;
import com.sms.sis.db.tables.ScContractsclassservice;
import com.sms.sis.db.tables.ScContractsclassserviceAudit;
import com.sms.sis.db.tables.ScContractsclasssupergroup;
import com.sms.sis.db.tables.ScContractsclasssupergroupAudit;
import com.sms.sis.db.tables.ScDeduction;
import com.sms.sis.db.tables.ScDeductionAudit;
import com.sms.sis.db.tables.ScDeductionCstm;
import com.sms.sis.db.tables.ScDoctortype;
import com.sms.sis.db.tables.ScDoctortypeAudit;
import com.sms.sis.db.tables.ScDoctortypeTasksC;
import com.sms.sis.db.tables.ScDrugs;
import com.sms.sis.db.tables.ScDrugsAudit;
import com.sms.sis.db.tables.ScDrugsScIngredientsC;
import com.sms.sis.db.tables.ScIcd10;
import com.sms.sis.db.tables.ScIcd10Audit;
import com.sms.sis.db.tables.ScIngredients;
import com.sms.sis.db.tables.ScIngredientsAudit;
import com.sms.sis.db.tables.ScInstallments;
import com.sms.sis.db.tables.ScInstallmentsAudit;
import com.sms.sis.db.tables.ScInstallmentsScCompanycontractsC;
import com.sms.sis.db.tables.ScInsurancecompanies;
import com.sms.sis.db.tables.ScInsurancecompaniesAudit;
import com.sms.sis.db.tables.ScInsurancecompaniesScCompanycontractsC;
import com.sms.sis.db.tables.ScPatches;
import com.sms.sis.db.tables.ScPatchesAudit;
import com.sms.sis.db.tables.ScPatchesScClaimsC;
import com.sms.sis.db.tables.ScPatchesSsJournalEntryC;
import com.sms.sis.db.tables.ScPatients;
import com.sms.sis.db.tables.ScPatientsAccountsC;
import com.sms.sis.db.tables.ScPatientsAudit;
import com.sms.sis.db.tables.ScPatientsContactsC;
import com.sms.sis.db.tables.ScPatientsScApprovaldetails_1C;
import com.sms.sis.db.tables.ScPatientsScClaimsC;
import com.sms.sis.db.tables.ScPatientsScPatientsC;
import com.sms.sis.db.tables.ScPatientsTasksC;
import com.sms.sis.db.tables.ScPatienttype;
import com.sms.sis.db.tables.ScPatienttypeAudit;
import com.sms.sis.db.tables.ScPriceListServices;
import com.sms.sis.db.tables.ScPriceListServicesAudit;
import com.sms.sis.db.tables.ScPriceLists;
import com.sms.sis.db.tables.ScPriceListsAudit;
import com.sms.sis.db.tables.ScPriceListsScPriceListServicesC;
import com.sms.sis.db.tables.ScPriceListsScProvidersC;
import com.sms.sis.db.tables.ScProviderBands;
import com.sms.sis.db.tables.ScProviderBandsAudit;
import com.sms.sis.db.tables.ScProviderBandsScProvidersC;
import com.sms.sis.db.tables.ScProviderbranches;
import com.sms.sis.db.tables.ScProviderbranchesAudit;
import com.sms.sis.db.tables.ScProviderbranchesScProvidersC;
import com.sms.sis.db.tables.ScProviders;
import com.sms.sis.db.tables.ScProvidersAudit;
import com.sms.sis.db.tables.ScProvidersCallsC;
import com.sms.sis.db.tables.ScProvidersCalls_1C;
import com.sms.sis.db.tables.ScProvidersContactsC;
import com.sms.sis.db.tables.ScProvidersScClaimsC;
import com.sms.sis.db.tables.ScProvidersScClaims_1C;
import com.sms.sis.db.tables.ScProvidersScPatchesC;
import com.sms.sis.db.tables.ScProvidersScProviderservicesC;
import com.sms.sis.db.tables.ScProvidersScProviderservicesCBackup;
import com.sms.sis.db.tables.ScProvidersTasksC;
import com.sms.sis.db.tables.ScProvidersTpModule1C;
import com.sms.sis.db.tables.ScProviderservices;
import com.sms.sis.db.tables.ScProviderservicesAudit;
import com.sms.sis.db.tables.ScProviderservicesCallsC;
import com.sms.sis.db.tables.ScProvidertypes;
import com.sms.sis.db.tables.ScProvidertypesAudit;
import com.sms.sis.db.tables.ScRegions;
import com.sms.sis.db.tables.ScRegionsAudit;
import com.sms.sis.db.tables.ScReports;
import com.sms.sis.db.tables.ScReportsAudit;
import com.sms.sis.db.tables.ScServicegroups;
import com.sms.sis.db.tables.ScServicegroupsAudit;
import com.sms.sis.db.tables.ScServicegroupsScServicesC;
import com.sms.sis.db.tables.ScServices;
import com.sms.sis.db.tables.ScServicesAudit;
import com.sms.sis.db.tables.ScServicessupergroups;
import com.sms.sis.db.tables.ScServicessupergroupsAudit;
import com.sms.sis.db.tables.ScServicessupergroupsScServicegroupsC;
import com.sms.sis.db.tables.ScSitedoctors;
import com.sms.sis.db.tables.ScSitedoctorsAudit;
import com.sms.sis.db.tables.ScSitedoctorsCallsC;
import com.sms.sis.db.tables.ScSitedoctorsScClaimsC;
import com.sms.sis.db.tables.ScSitedoctorsScCompanycontractsC;
import com.sms.sis.db.tables.ScSms;
import com.sms.sis.db.tables.ScSmsAudit;
import com.sms.sis.db.tables.ScSmsScPatientsC;
import com.sms.sis.db.tables.ScTest;
import com.sms.sis.db.tables.ScTestAudit;
import com.sms.sis.db.tables.ScTestidmodule;
import com.sms.sis.db.tables.ScTestidmoduleAudit;
import com.sms.sis.db.tables.ScTestidmoduleScClaimsC;
import com.sms.sis.db.tables.Schedulers;
import com.sms.sis.db.tables.SsAccountingSettings;
import com.sms.sis.db.tables.SsAccountingSettingsAudit;
import com.sms.sis.db.tables.SsBSTemplateDetails;
import com.sms.sis.db.tables.SsBSTemplateDetailsAudit;
import com.sms.sis.db.tables.SsBSTemplateDetailsSsGlAccountC;
import com.sms.sis.db.tables.SsBalanceSheetTemplates;
import com.sms.sis.db.tables.SsBalanceSheetTemplatesAudit;
import com.sms.sis.db.tables.SsBalanceSheetTemplatesSsBSTemplateDetailsC;
import com.sms.sis.db.tables.SsBanks;
import com.sms.sis.db.tables.SsBanksAudit;
import com.sms.sis.db.tables.SsBanksSsOutgoingChecksC;
import com.sms.sis.db.tables.SsBranchCases;
import com.sms.sis.db.tables.SsBranchCasesAudit;
import com.sms.sis.db.tables.SsBranches;
import com.sms.sis.db.tables.SsBranchesAudit;
import com.sms.sis.db.tables.SsBsTemplateData;
import com.sms.sis.db.tables.SsBsTemplateDataAudit;
import com.sms.sis.db.tables.SsCostCenters;
import com.sms.sis.db.tables.SsCostCentersAudit;
import com.sms.sis.db.tables.SsCustomerInvoices;
import com.sms.sis.db.tables.SsCustomerInvoicesAudit;
import com.sms.sis.db.tables.SsFiscalYear;
import com.sms.sis.db.tables.SsFiscalYearAudit;
import com.sms.sis.db.tables.SsGlAccount;
import com.sms.sis.db.tables.SsGlAccountAudit;
import com.sms.sis.db.tables.SsGlAccountSsGlAccountC;
import com.sms.sis.db.tables.SsGlAccountsDistribution;
import com.sms.sis.db.tables.SsGlAccountsDistributionAudit;
import com.sms.sis.db.tables.SsISTemplateDetails;
import com.sms.sis.db.tables.SsISTemplateDetailsAudit;
import com.sms.sis.db.tables.SsISTemplateDetailsSsGlAccountC;
import com.sms.sis.db.tables.SsIncomeStatemantTemplates;
import com.sms.sis.db.tables.SsIncomeStatemantTemplatesAudit;
import com.sms.sis.db.tables.SsIncomeStatemantTemplatesSsISTemplateDetailsC;
import com.sms.sis.db.tables.SsIncomingChecks;
import com.sms.sis.db.tables.SsIncomingChecksAudit;
import com.sms.sis.db.tables.SsIsTemplateData;
import com.sms.sis.db.tables.SsIsTemplateDataAudit;
import com.sms.sis.db.tables.SsJournalEntry;
import com.sms.sis.db.tables.SsJournalEntryAudit;
import com.sms.sis.db.tables.SsJournalEntryRow;
import com.sms.sis.db.tables.SsJournalEntryRowAudit;
import com.sms.sis.db.tables.SsJournalEntrySsJournalEntryRowC;
import com.sms.sis.db.tables.SsOutgoingChecks;
import com.sms.sis.db.tables.SsOutgoingChecksAudit;
import com.sms.sis.db.tables.SsPayables;
import com.sms.sis.db.tables.SsPayablesAudit;
import com.sms.sis.db.tables.SsPayablesSsGlAccountsDistributionC;
import com.sms.sis.db.tables.SsPayablesSsOutgoingChecksC;
import com.sms.sis.db.tables.SsProviderInvoices;
import com.sms.sis.db.tables.SsProviderInvoicesAudit;
import com.sms.sis.db.tables.SsReceivables;
import com.sms.sis.db.tables.SsReceivablesAudit;
import com.sms.sis.db.tables.SsReceivablesSsGlAccountC;
import com.sms.sis.db.tables.SsReceivablesSsGlAccountsDistributionC;
import com.sms.sis.db.tables.SsReceivablesSsIncomingChecksC;
import com.sms.sis.db.tables.Sugarfeed;
import com.sms.sis.db.tables.Tasks;
import com.sms.sis.db.tables.TasksCstm;
import com.sms.sis.db.tables.TasksDocuments_1C;
import com.sms.sis.db.tables.Testinglong;
import com.sms.sis.db.tables.TpModule1;
import com.sms.sis.db.tables.TpModule1Audit;
import com.sms.sis.db.tables.TpModule1ScAreasC;
import com.sms.sis.db.tables.TpModule1ScRegionsC;
import com.sms.sis.db.tables.Tracker;
import com.sms.sis.db.tables.UpgradeHistory;
import com.sms.sis.db.tables.UserPreferences;
import com.sms.sis.db.tables.Users;
import com.sms.sis.db.tables.UsersCstm;
import com.sms.sis.db.tables.UsersFeeds;
import com.sms.sis.db.tables.UsersLastImport;
import com.sms.sis.db.tables.UsersPasswordLink;
import com.sms.sis.db.tables.UsersSignatures;
import com.sms.sis.db.tables.Vcals;
import com.sms.sis.db.tables.Versions;
import com.sms.sis.db.tables._Tempproviderbranches;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in sugarcrm_4_12
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>sugarcrm_4_12.accounts</code>.
     */
    public static final Accounts ACCOUNTS = com.sms.sis.db.tables.Accounts.ACCOUNTS;

    /**
     * The table <code>sugarcrm_4_12.accounts_audit</code>.
     */
    public static final AccountsAudit ACCOUNTS_AUDIT = com.sms.sis.db.tables.AccountsAudit.ACCOUNTS_AUDIT;

    /**
     * The table <code>sugarcrm_4_12.accounts_bugs</code>.
     */
    public static final AccountsBugs ACCOUNTS_BUGS = com.sms.sis.db.tables.AccountsBugs.ACCOUNTS_BUGS;

    /**
     * The table <code>sugarcrm_4_12.accounts_cases</code>.
     */
    public static final AccountsCases ACCOUNTS_CASES = com.sms.sis.db.tables.AccountsCases.ACCOUNTS_CASES;

    /**
     * The table <code>sugarcrm_4_12.accounts_contacts</code>.
     */
    public static final AccountsContacts ACCOUNTS_CONTACTS = com.sms.sis.db.tables.AccountsContacts.ACCOUNTS_CONTACTS;

    /**
     * The table <code>sugarcrm_4_12.accounts_cstm</code>.
     */
    public static final AccountsCstm ACCOUNTS_CSTM = com.sms.sis.db.tables.AccountsCstm.ACCOUNTS_CSTM;

    /**
     * The table <code>sugarcrm_4_12.accounts_opportunities</code>.
     */
    public static final AccountsOpportunities ACCOUNTS_OPPORTUNITIES = com.sms.sis.db.tables.AccountsOpportunities.ACCOUNTS_OPPORTUNITIES;

    /**
     * The table <code>sugarcrm_4_12.acl_actions</code>.
     */
    public static final AclActions ACL_ACTIONS = com.sms.sis.db.tables.AclActions.ACL_ACTIONS;

    /**
     * The table <code>sugarcrm_4_12.acl_roles</code>.
     */
    public static final AclRoles ACL_ROLES = com.sms.sis.db.tables.AclRoles.ACL_ROLES;

    /**
     * The table <code>sugarcrm_4_12.acl_roles_actions</code>.
     */
    public static final AclRolesActions ACL_ROLES_ACTIONS = com.sms.sis.db.tables.AclRolesActions.ACL_ROLES_ACTIONS;

    /**
     * The table <code>sugarcrm_4_12.acl_roles_users</code>.
     */
    public static final AclRolesUsers ACL_ROLES_USERS = com.sms.sis.db.tables.AclRolesUsers.ACL_ROLES_USERS;

    /**
     * The table <code>sugarcrm_4_12.address_book</code>.
     */
    public static final AddressBook ADDRESS_BOOK = com.sms.sis.db.tables.AddressBook.ADDRESS_BOOK;

    /**
     * The table <code>sugarcrm_4_12.approvaldetailsutilizationtable</code>.
     */
    public static final Approvaldetailsutilizationtable APPROVALDETAILSUTILIZATIONTABLE = com.sms.sis.db.tables.Approvaldetailsutilizationtable.APPROVALDETAILSUTILIZATIONTABLE;

    /**
     * The table <code>sugarcrm_4_12.areas_fix_5</code>.
     */
    public static final AreasFix_5 AREAS_FIX_5 = com.sms.sis.db.tables.AreasFix_5.AREAS_FIX_5;

    /**
     * The table <code>sugarcrm_4_12.asterisk_log</code>.
     */
    public static final AsteriskLog ASTERISK_LOG = com.sms.sis.db.tables.AsteriskLog.ASTERISK_LOG;

    /**
     * The table <code>sugarcrm_4_12.bugs</code>.
     */
    public static final Bugs BUGS = com.sms.sis.db.tables.Bugs.BUGS;

    /**
     * The table <code>sugarcrm_4_12.bugs_audit</code>.
     */
    public static final BugsAudit BUGS_AUDIT = com.sms.sis.db.tables.BugsAudit.BUGS_AUDIT;

    /**
     * The table <code>sugarcrm_4_12.calls</code>.
     */
    public static final Calls CALLS = com.sms.sis.db.tables.Calls.CALLS;

    /**
     * The table <code>sugarcrm_4_12.calls_contacts</code>.
     */
    public static final CallsContacts CALLS_CONTACTS = com.sms.sis.db.tables.CallsContacts.CALLS_CONTACTS;

    /**
     * The table <code>sugarcrm_4_12.calls_cstm</code>.
     */
    public static final CallsCstm CALLS_CSTM = com.sms.sis.db.tables.CallsCstm.CALLS_CSTM;

    /**
     * The table <code>sugarcrm_4_12.calls_leads</code>.
     */
    public static final CallsLeads CALLS_LEADS = com.sms.sis.db.tables.CallsLeads.CALLS_LEADS;

    /**
     * The table <code>sugarcrm_4_12.calls_users</code>.
     */
    public static final CallsUsers CALLS_USERS = com.sms.sis.db.tables.CallsUsers.CALLS_USERS;

    /**
     * The table <code>sugarcrm_4_12.campaigns</code>.
     */
    public static final Campaigns CAMPAIGNS = com.sms.sis.db.tables.Campaigns.CAMPAIGNS;

    /**
     * The table <code>sugarcrm_4_12.campaigns_audit</code>.
     */
    public static final CampaignsAudit CAMPAIGNS_AUDIT = com.sms.sis.db.tables.CampaignsAudit.CAMPAIGNS_AUDIT;

    /**
     * The table <code>sugarcrm_4_12.campaign_log</code>.
     */
    public static final CampaignLog CAMPAIGN_LOG = com.sms.sis.db.tables.CampaignLog.CAMPAIGN_LOG;

    /**
     * The table <code>sugarcrm_4_12.campaign_trkrs</code>.
     */
    public static final CampaignTrkrs CAMPAIGN_TRKRS = com.sms.sis.db.tables.CampaignTrkrs.CAMPAIGN_TRKRS;

    /**
     * The table <code>sugarcrm_4_12.cases</code>.
     */
    public static final Cases CASES = com.sms.sis.db.tables.Cases.CASES;

    /**
     * The table <code>sugarcrm_4_12.cases_audit</code>.
     */
    public static final CasesAudit CASES_AUDIT = com.sms.sis.db.tables.CasesAudit.CASES_AUDIT;

    /**
     * The table <code>sugarcrm_4_12.cases_bugs</code>.
     */
    public static final CasesBugs CASES_BUGS = com.sms.sis.db.tables.CasesBugs.CASES_BUGS;

    /**
     * The table <code>sugarcrm_4_12.claimdetailsutilizationtable</code>.
     */
    public static final Claimdetailsutilizationtable CLAIMDETAILSUTILIZATIONTABLE = com.sms.sis.db.tables.Claimdetailsutilizationtable.CLAIMDETAILSUTILIZATIONTABLE;

    /**
     * The table <code>sugarcrm_4_12.config</code>.
     */
    public static final Config CONFIG = com.sms.sis.db.tables.Config.CONFIG;

    /**
     * The table <code>sugarcrm_4_12.constraintstructure_log</code>.
     */
    public static final ConstraintstructureLog CONSTRAINTSTRUCTURE_LOG = com.sms.sis.db.tables.ConstraintstructureLog.CONSTRAINTSTRUCTURE_LOG;

    /**
     * The table <code>sugarcrm_4_12.contacts</code>.
     */
    public static final Contacts CONTACTS = com.sms.sis.db.tables.Contacts.CONTACTS;

    /**
     * The table <code>sugarcrm_4_12.contacts_audit</code>.
     */
    public static final ContactsAudit CONTACTS_AUDIT = com.sms.sis.db.tables.ContactsAudit.CONTACTS_AUDIT;

    /**
     * The table <code>sugarcrm_4_12.contacts_bugs</code>.
     */
    public static final ContactsBugs CONTACTS_BUGS = com.sms.sis.db.tables.ContactsBugs.CONTACTS_BUGS;

    /**
     * The table <code>sugarcrm_4_12.contacts_cases</code>.
     */
    public static final ContactsCases CONTACTS_CASES = com.sms.sis.db.tables.ContactsCases.CONTACTS_CASES;

    /**
     * The table <code>sugarcrm_4_12.contacts_cstm</code>.
     */
    public static final ContactsCstm CONTACTS_CSTM = com.sms.sis.db.tables.ContactsCstm.CONTACTS_CSTM;

    /**
     * The table <code>sugarcrm_4_12.contacts_users</code>.
     */
    public static final ContactsUsers CONTACTS_USERS = com.sms.sis.db.tables.ContactsUsers.CONTACTS_USERS;

    /**
     * The table <code>sugarcrm_4_12.cron_remove_documents</code>.
     */
    public static final CronRemoveDocuments CRON_REMOVE_DOCUMENTS = com.sms.sis.db.tables.CronRemoveDocuments.CRON_REMOVE_DOCUMENTS;

    /**
     * The table <code>sugarcrm_4_12.currencies</code>.
     */
    public static final Currencies CURRENCIES = com.sms.sis.db.tables.Currencies.CURRENCIES;

    /**
     * The table <code>sugarcrm_4_12.custom_fields</code>.
     */
    public static final CustomFields CUSTOM_FIELDS = com.sms.sis.db.tables.CustomFields.CUSTOM_FIELDS;

    /**
     * The table <code>sugarcrm_4_12.dm_bocs</code>.
     */
    public static final DmBocs DM_BOCS = com.sms.sis.db.tables.DmBocs.DM_BOCS;

    /**
     * The table <code>sugarcrm_4_12.dm_bocs_audit</code>.
     */
    public static final DmBocsAudit DM_BOCS_AUDIT = com.sms.sis.db.tables.DmBocsAudit.DM_BOCS_AUDIT;

    /**
     * The table <code>sugarcrm_4_12.dm_bocs_sc_patches_c</code>.
     */
    public static final DmBocsScPatchesC DM_BOCS_SC_PATCHES_C = com.sms.sis.db.tables.DmBocsScPatchesC.DM_BOCS_SC_PATCHES_C;

    /**
     * The table <code>sugarcrm_4_12.documents</code>.
     */
    public static final Documents DOCUMENTS = com.sms.sis.db.tables.Documents.DOCUMENTS;

    /**
     * The table <code>sugarcrm_4_12.documents_accounts</code>.
     */
    public static final DocumentsAccounts DOCUMENTS_ACCOUNTS = com.sms.sis.db.tables.DocumentsAccounts.DOCUMENTS_ACCOUNTS;

    /**
     * The table <code>sugarcrm_4_12.documents_bugs</code>.
     */
    public static final DocumentsBugs DOCUMENTS_BUGS = com.sms.sis.db.tables.DocumentsBugs.DOCUMENTS_BUGS;

    /**
     * The table <code>sugarcrm_4_12.documents_cases</code>.
     */
    public static final DocumentsCases DOCUMENTS_CASES = com.sms.sis.db.tables.DocumentsCases.DOCUMENTS_CASES;

    /**
     * The table <code>sugarcrm_4_12.documents_contacts</code>.
     */
    public static final DocumentsContacts DOCUMENTS_CONTACTS = com.sms.sis.db.tables.DocumentsContacts.DOCUMENTS_CONTACTS;

    /**
     * The table <code>sugarcrm_4_12.documents_opportunities</code>.
     */
    public static final DocumentsOpportunities DOCUMENTS_OPPORTUNITIES = com.sms.sis.db.tables.DocumentsOpportunities.DOCUMENTS_OPPORTUNITIES;

    /**
     * The table <code>sugarcrm_4_12.document_revisions</code>.
     */
    public static final DocumentRevisions DOCUMENT_REVISIONS = com.sms.sis.db.tables.DocumentRevisions.DOCUMENT_REVISIONS;

    /**
     * The table <code>sugarcrm_4_12.eapm</code>.
     */
    public static final Eapm EAPM = com.sms.sis.db.tables.Eapm.EAPM;

    /**
     * The table <code>sugarcrm_4_12.emailman</code>.
     */
    public static final Emailman EMAILMAN = com.sms.sis.db.tables.Emailman.EMAILMAN;

    /**
     * The table <code>sugarcrm_4_12.emails</code>.
     */
    public static final Emails EMAILS = com.sms.sis.db.tables.Emails.EMAILS;

    /**
     * The table <code>sugarcrm_4_12.emails_beans</code>.
     */
    public static final EmailsBeans EMAILS_BEANS = com.sms.sis.db.tables.EmailsBeans.EMAILS_BEANS;

    /**
     * The table <code>sugarcrm_4_12.emails_email_addr_rel</code>.
     */
    public static final EmailsEmailAddrRel EMAILS_EMAIL_ADDR_REL = com.sms.sis.db.tables.EmailsEmailAddrRel.EMAILS_EMAIL_ADDR_REL;

    /**
     * The table <code>sugarcrm_4_12.emails_text</code>.
     */
    public static final EmailsText EMAILS_TEXT = com.sms.sis.db.tables.EmailsText.EMAILS_TEXT;

    /**
     * The table <code>sugarcrm_4_12.email_addresses</code>.
     */
    public static final EmailAddresses EMAIL_ADDRESSES = com.sms.sis.db.tables.EmailAddresses.EMAIL_ADDRESSES;

    /**
     * The table <code>sugarcrm_4_12.email_addr_bean_rel</code>.
     */
    public static final EmailAddrBeanRel EMAIL_ADDR_BEAN_REL = com.sms.sis.db.tables.EmailAddrBeanRel.EMAIL_ADDR_BEAN_REL;

    /**
     * The table <code>sugarcrm_4_12.email_cache</code>.
     */
    public static final EmailCache EMAIL_CACHE = com.sms.sis.db.tables.EmailCache.EMAIL_CACHE;

    /**
     * The table <code>sugarcrm_4_12.email_marketing</code>.
     */
    public static final EmailMarketing EMAIL_MARKETING = com.sms.sis.db.tables.EmailMarketing.EMAIL_MARKETING;

    /**
     * The table <code>sugarcrm_4_12.email_marketing_prospect_lists</code>.
     */
    public static final EmailMarketingProspectLists EMAIL_MARKETING_PROSPECT_LISTS = com.sms.sis.db.tables.EmailMarketingProspectLists.EMAIL_MARKETING_PROSPECT_LISTS;

    /**
     * The table <code>sugarcrm_4_12.email_templates</code>.
     */
    public static final EmailTemplates EMAIL_TEMPLATES = com.sms.sis.db.tables.EmailTemplates.EMAIL_TEMPLATES;

    /**
     * The table <code>sugarcrm_4_12.fields_meta_data</code>.
     */
    public static final FieldsMetaData FIELDS_META_DATA = com.sms.sis.db.tables.FieldsMetaData.FIELDS_META_DATA;

    /**
     * The table <code>sugarcrm_4_12.folders</code>.
     */
    public static final Folders FOLDERS = com.sms.sis.db.tables.Folders.FOLDERS;

    /**
     * The table <code>sugarcrm_4_12.folders_rel</code>.
     */
    public static final FoldersRel FOLDERS_REL = com.sms.sis.db.tables.FoldersRel.FOLDERS_REL;

    /**
     * The table <code>sugarcrm_4_12.folders_subscriptions</code>.
     */
    public static final FoldersSubscriptions FOLDERS_SUBSCRIPTIONS = com.sms.sis.db.tables.FoldersSubscriptions.FOLDERS_SUBSCRIPTIONS;

    /**
     * The table <code>sugarcrm_4_12.import_maps</code>.
     */
    public static final ImportMaps IMPORT_MAPS = com.sms.sis.db.tables.ImportMaps.IMPORT_MAPS;

    /**
     * The table <code>sugarcrm_4_12.inbound_email</code>.
     */
    public static final InboundEmail INBOUND_EMAIL = com.sms.sis.db.tables.InboundEmail.INBOUND_EMAIL;

    /**
     * The table <code>sugarcrm_4_12.inbound_email_autoreply</code>.
     */
    public static final InboundEmailAutoreply INBOUND_EMAIL_AUTOREPLY = com.sms.sis.db.tables.InboundEmailAutoreply.INBOUND_EMAIL_AUTOREPLY;

    /**
     * The table <code>sugarcrm_4_12.inbound_email_cache_ts</code>.
     */
    public static final InboundEmailCacheTs INBOUND_EMAIL_CACHE_TS = com.sms.sis.db.tables.InboundEmailCacheTs.INBOUND_EMAIL_CACHE_TS;

    /**
     * The table <code>sugarcrm_4_12.job_queue</code>.
     */
    public static final JobQueue JOB_QUEUE = com.sms.sis.db.tables.JobQueue.JOB_QUEUE;

    /**
     * The table <code>sugarcrm_4_12.leads</code>.
     */
    public static final Leads LEADS = com.sms.sis.db.tables.Leads.LEADS;

    /**
     * The table <code>sugarcrm_4_12.leads_audit</code>.
     */
    public static final LeadsAudit LEADS_AUDIT = com.sms.sis.db.tables.LeadsAudit.LEADS_AUDIT;

    /**
     * The table <code>sugarcrm_4_12.linked_documents</code>.
     */
    public static final LinkedDocuments LINKED_DOCUMENTS = com.sms.sis.db.tables.LinkedDocuments.LINKED_DOCUMENTS;

    /**
     * The table <code>sugarcrm_4_12.meetings</code>.
     */
    public static final Meetings MEETINGS = com.sms.sis.db.tables.Meetings.MEETINGS;

    /**
     * The table <code>sugarcrm_4_12.meetings_contacts</code>.
     */
    public static final MeetingsContacts MEETINGS_CONTACTS = com.sms.sis.db.tables.MeetingsContacts.MEETINGS_CONTACTS;

    /**
     * The table <code>sugarcrm_4_12.meetings_leads</code>.
     */
    public static final MeetingsLeads MEETINGS_LEADS = com.sms.sis.db.tables.MeetingsLeads.MEETINGS_LEADS;

    /**
     * The table <code>sugarcrm_4_12.meetings_users</code>.
     */
    public static final MeetingsUsers MEETINGS_USERS = com.sms.sis.db.tables.MeetingsUsers.MEETINGS_USERS;

    /**
     * The table <code>sugarcrm_4_12.notes</code>.
     */
    public static final Notes NOTES = com.sms.sis.db.tables.Notes.NOTES;

    /**
     * The table <code>sugarcrm_4_12.oauth_consumer</code>.
     */
    public static final OauthConsumer OAUTH_CONSUMER = com.sms.sis.db.tables.OauthConsumer.OAUTH_CONSUMER;

    /**
     * The table <code>sugarcrm_4_12.oauth_nonce</code>.
     */
    public static final OauthNonce OAUTH_NONCE = com.sms.sis.db.tables.OauthNonce.OAUTH_NONCE;

    /**
     * The table <code>sugarcrm_4_12.oauth_tokens</code>.
     */
    public static final OauthTokens OAUTH_TOKENS = com.sms.sis.db.tables.OauthTokens.OAUTH_TOKENS;

    /**
     * The table <code>sugarcrm_4_12.opportunities</code>.
     */
    public static final Opportunities OPPORTUNITIES = com.sms.sis.db.tables.Opportunities.OPPORTUNITIES;

    /**
     * The table <code>sugarcrm_4_12.opportunities_audit</code>.
     */
    public static final OpportunitiesAudit OPPORTUNITIES_AUDIT = com.sms.sis.db.tables.OpportunitiesAudit.OPPORTUNITIES_AUDIT;

    /**
     * The table <code>sugarcrm_4_12.opportunities_contacts</code>.
     */
    public static final OpportunitiesContacts OPPORTUNITIES_CONTACTS = com.sms.sis.db.tables.OpportunitiesContacts.OPPORTUNITIES_CONTACTS;

    /**
     * The table <code>sugarcrm_4_12.outbound_email</code>.
     */
    public static final OutboundEmail OUTBOUND_EMAIL = com.sms.sis.db.tables.OutboundEmail.OUTBOUND_EMAIL;

    /**
     * The table <code>sugarcrm_4_12.project</code>.
     */
    public static final Project PROJECT = com.sms.sis.db.tables.Project.PROJECT;

    /**
     * The table <code>sugarcrm_4_12.projects_accounts</code>.
     */
    public static final ProjectsAccounts PROJECTS_ACCOUNTS = com.sms.sis.db.tables.ProjectsAccounts.PROJECTS_ACCOUNTS;

    /**
     * The table <code>sugarcrm_4_12.projects_bugs</code>.
     */
    public static final ProjectsBugs PROJECTS_BUGS = com.sms.sis.db.tables.ProjectsBugs.PROJECTS_BUGS;

    /**
     * The table <code>sugarcrm_4_12.projects_cases</code>.
     */
    public static final ProjectsCases PROJECTS_CASES = com.sms.sis.db.tables.ProjectsCases.PROJECTS_CASES;

    /**
     * The table <code>sugarcrm_4_12.projects_contacts</code>.
     */
    public static final ProjectsContacts PROJECTS_CONTACTS = com.sms.sis.db.tables.ProjectsContacts.PROJECTS_CONTACTS;

    /**
     * The table <code>sugarcrm_4_12.projects_opportunities</code>.
     */
    public static final ProjectsOpportunities PROJECTS_OPPORTUNITIES = com.sms.sis.db.tables.ProjectsOpportunities.PROJECTS_OPPORTUNITIES;

    /**
     * The table <code>sugarcrm_4_12.projects_products</code>.
     */
    public static final ProjectsProducts PROJECTS_PRODUCTS = com.sms.sis.db.tables.ProjectsProducts.PROJECTS_PRODUCTS;

    /**
     * The table <code>sugarcrm_4_12.project_task</code>.
     */
    public static final ProjectTask PROJECT_TASK = com.sms.sis.db.tables.ProjectTask.PROJECT_TASK;

    /**
     * The table <code>sugarcrm_4_12.project_task_audit</code>.
     */
    public static final ProjectTaskAudit PROJECT_TASK_AUDIT = com.sms.sis.db.tables.ProjectTaskAudit.PROJECT_TASK_AUDIT;

    /**
     * The table <code>sugarcrm_4_12.prospects</code>.
     */
    public static final Prospects PROSPECTS = com.sms.sis.db.tables.Prospects.PROSPECTS;

    /**
     * The table <code>sugarcrm_4_12.prospect_lists</code>.
     */
    public static final ProspectLists PROSPECT_LISTS = com.sms.sis.db.tables.ProspectLists.PROSPECT_LISTS;

    /**
     * The table <code>sugarcrm_4_12.prospect_lists_prospects</code>.
     */
    public static final ProspectListsProspects PROSPECT_LISTS_PROSPECTS = com.sms.sis.db.tables.ProspectListsProspects.PROSPECT_LISTS_PROSPECTS;

    /**
     * The table <code>sugarcrm_4_12.prospect_list_campaigns</code>.
     */
    public static final ProspectListCampaigns PROSPECT_LIST_CAMPAIGNS = com.sms.sis.db.tables.ProspectListCampaigns.PROSPECT_LIST_CAMPAIGNS;

    /**
     * The table <code>sugarcrm_4_12.relationships</code>.
     */
    public static final Relationships RELATIONSHIPS = com.sms.sis.db.tables.Relationships.RELATIONSHIPS;

    /**
     * The table <code>sugarcrm_4_12.releases</code>.
     */
    public static final Releases RELEASES = com.sms.sis.db.tables.Releases.RELEASES;

    /**
     * The table <code>sugarcrm_4_12.roles</code>.
     */
    public static final Roles ROLES = com.sms.sis.db.tables.Roles.ROLES;

    /**
     * The table <code>sugarcrm_4_12.roles_modules</code>.
     */
    public static final RolesModules ROLES_MODULES = com.sms.sis.db.tables.RolesModules.ROLES_MODULES;

    /**
     * The table <code>sugarcrm_4_12.roles_users</code>.
     */
    public static final RolesUsers ROLES_USERS = com.sms.sis.db.tables.RolesUsers.ROLES_USERS;

    /**
     * The table <code>sugarcrm_4_12.saved_search</code>.
     */
    public static final SavedSearch SAVED_SEARCH = com.sms.sis.db.tables.SavedSearch.SAVED_SEARCH;

    /**
     * The table <code>sugarcrm_4_12.schedulers</code>.
     */
    public static final Schedulers SCHEDULERS = com.sms.sis.db.tables.Schedulers.SCHEDULERS;

    /**
     * The table <code>sugarcrm_4_12.sc_accountoperators</code>.
     */
    public static final ScAccountoperators SC_ACCOUNTOPERATORS = com.sms.sis.db.tables.ScAccountoperators.SC_ACCOUNTOPERATORS;

    /**
     * The table <code>sugarcrm_4_12.sc_accountoperators_accounts_c</code>.
     */
    public static final ScAccountoperatorsAccountsC SC_ACCOUNTOPERATORS_ACCOUNTS_C = com.sms.sis.db.tables.ScAccountoperatorsAccountsC.SC_ACCOUNTOPERATORS_ACCOUNTS_C;

    /**
     * The table <code>sugarcrm_4_12.sc_accountoperators_audit</code>.
     */
    public static final ScAccountoperatorsAudit SC_ACCOUNTOPERATORS_AUDIT = com.sms.sis.db.tables.ScAccountoperatorsAudit.SC_ACCOUNTOPERATORS_AUDIT;

    /**
     * The table <code>sugarcrm_4_12.sc_accountoperators_calls_c</code>.
     */
    public static final ScAccountoperatorsCallsC SC_ACCOUNTOPERATORS_CALLS_C = com.sms.sis.db.tables.ScAccountoperatorsCallsC.SC_ACCOUNTOPERATORS_CALLS_C;

    /**
     * The table <code>sugarcrm_4_12.sc_accountoperators_sc_claims_c</code>.
     */
    public static final ScAccountoperatorsScClaimsC SC_ACCOUNTOPERATORS_SC_CLAIMS_C = com.sms.sis.db.tables.ScAccountoperatorsScClaimsC.SC_ACCOUNTOPERATORS_SC_CLAIMS_C;

    /**
     * The table <code>sugarcrm_4_12.sc_accountoperators_sc_companycontracts_c</code>.
     */
    public static final ScAccountoperatorsScCompanycontractsC SC_ACCOUNTOPERATORS_SC_COMPANYCONTRACTS_C = com.sms.sis.db.tables.ScAccountoperatorsScCompanycontractsC.SC_ACCOUNTOPERATORS_SC_COMPANYCONTRACTS_C;

    /**
     * The table <code>sugarcrm_4_12.sc_accountoperators_users_c</code>.
     */
    public static final ScAccountoperatorsUsersC SC_ACCOUNTOPERATORS_USERS_C = com.sms.sis.db.tables.ScAccountoperatorsUsersC.SC_ACCOUNTOPERATORS_USERS_C;

    /**
     * The table <code>sugarcrm_4_12.sc_approvaldetails</code>.
     */
    public static final ScApprovaldetails SC_APPROVALDETAILS = com.sms.sis.db.tables.ScApprovaldetails.SC_APPROVALDETAILS;

    /**
     * The table <code>sugarcrm_4_12.sc_approvaldetailsdrugs</code>.
     */
    public static final ScApprovaldetailsdrugs SC_APPROVALDETAILSDRUGS = com.sms.sis.db.tables.ScApprovaldetailsdrugs.SC_APPROVALDETAILSDRUGS;

    /**
     * The table <code>sugarcrm_4_12.sc_approvaldetailsdrugs_audit</code>.
     */
    public static final ScApprovaldetailsdrugsAudit SC_APPROVALDETAILSDRUGS_AUDIT = com.sms.sis.db.tables.ScApprovaldetailsdrugsAudit.SC_APPROVALDETAILSDRUGS_AUDIT;

    /**
     * The table <code>sugarcrm_4_12.sc_approvaldetailsdrugs_sc_approvaldetails_c</code>.
     */
    public static final ScApprovaldetailsdrugsScApprovaldetailsC SC_APPROVALDETAILSDRUGS_SC_APPROVALDETAILS_C = com.sms.sis.db.tables.ScApprovaldetailsdrugsScApprovaldetailsC.SC_APPROVALDETAILSDRUGS_SC_APPROVALDETAILS_C;

    /**
     * The table <code>sugarcrm_4_12.sc_approvaldetails_audit</code>.
     */
    public static final ScApprovaldetailsAudit SC_APPROVALDETAILS_AUDIT = com.sms.sis.db.tables.ScApprovaldetailsAudit.SC_APPROVALDETAILS_AUDIT;

    /**
     * The table <code>sugarcrm_4_12.sc_approvals</code>.
     */
    public static final ScApprovals SC_APPROVALS = com.sms.sis.db.tables.ScApprovals.SC_APPROVALS;

    /**
     * The table <code>sugarcrm_4_12.sc_approvals_audit</code>.
     */
    public static final ScApprovalsAudit SC_APPROVALS_AUDIT = com.sms.sis.db.tables.ScApprovalsAudit.SC_APPROVALS_AUDIT;

    /**
     * The table <code>sugarcrm_4_12.sc_approvals_calls_c</code>.
     */
    public static final ScApprovalsCallsC SC_APPROVALS_CALLS_C = com.sms.sis.db.tables.ScApprovalsCallsC.SC_APPROVALS_CALLS_C;

    /**
     * The table <code>sugarcrm_4_12.sc_approvals_sc_approvaldetails_c</code>.
     */
    public static final ScApprovalsScApprovaldetailsC SC_APPROVALS_SC_APPROVALDETAILS_C = com.sms.sis.db.tables.ScApprovalsScApprovaldetailsC.SC_APPROVALS_SC_APPROVALDETAILS_C;

    /**
     * The table <code>sugarcrm_4_12.sc_approvals_sc_patients_c</code>.
     */
    public static final ScApprovalsScPatientsC SC_APPROVALS_SC_PATIENTS_C = com.sms.sis.db.tables.ScApprovalsScPatientsC.SC_APPROVALS_SC_PATIENTS_C;

    /**
     * The table <code>sugarcrm_4_12.sc_approvals_sc_providers_c</code>.
     */
    public static final ScApprovalsScProvidersC SC_APPROVALS_SC_PROVIDERS_C = com.sms.sis.db.tables.ScApprovalsScProvidersC.SC_APPROVALS_SC_PROVIDERS_C;

    /**
     * The table <code>sugarcrm_4_12.sc_approvals_tasks_c</code>.
     */
    public static final ScApprovalsTasksC SC_APPROVALS_TASKS_C = com.sms.sis.db.tables.ScApprovalsTasksC.SC_APPROVALS_TASKS_C;

    /**
     * The table <code>sugarcrm_4_12.sc_areas</code>.
     */
    public static final ScAreas SC_AREAS = com.sms.sis.db.tables.ScAreas.SC_AREAS;

    /**
     * The table <code>sugarcrm_4_12.sc_areas_accounts_c</code>.
     */
    public static final ScAreasAccountsC SC_AREAS_ACCOUNTS_C = com.sms.sis.db.tables.ScAreasAccountsC.SC_AREAS_ACCOUNTS_C;

    /**
     * The table <code>sugarcrm_4_12.sc_areas_audit</code>.
     */
    public static final ScAreasAudit SC_AREAS_AUDIT = com.sms.sis.db.tables.ScAreasAudit.SC_AREAS_AUDIT;

    /**
     * The table <code>sugarcrm_4_12.sc_claimdetails</code>.
     */
    public static final ScClaimdetails SC_CLAIMDETAILS = com.sms.sis.db.tables.ScClaimdetails.SC_CLAIMDETAILS;

    /**
     * The table <code>sugarcrm_4_12.sc_claimdetails_audit</code>.
     */
    public static final ScClaimdetailsAudit SC_CLAIMDETAILS_AUDIT = com.sms.sis.db.tables.ScClaimdetailsAudit.SC_CLAIMDETAILS_AUDIT;

    /**
     * The table <code>sugarcrm_4_12.sc_claims</code>.
     */
    public static final ScClaims SC_CLAIMS = com.sms.sis.db.tables.ScClaims.SC_CLAIMS;

    /**
     * The table <code>sugarcrm_4_12.sc_claims_audit</code>.
     */
    public static final ScClaimsAudit SC_CLAIMS_AUDIT = com.sms.sis.db.tables.ScClaimsAudit.SC_CLAIMS_AUDIT;

    /**
     * The table <code>sugarcrm_4_12.sc_claims_sc_approvals_c</code>.
     */
    public static final ScClaimsScApprovalsC SC_CLAIMS_SC_APPROVALS_C = com.sms.sis.db.tables.ScClaimsScApprovalsC.SC_CLAIMS_SC_APPROVALS_C;

    /**
     * The table <code>sugarcrm_4_12.sc_claims_sc_claimdetails_c</code>.
     */
    public static final ScClaimsScClaimdetailsC SC_CLAIMS_SC_CLAIMDETAILS_C = com.sms.sis.db.tables.ScClaimsScClaimdetailsC.SC_CLAIMS_SC_CLAIMDETAILS_C;

    /**
     * The table <code>sugarcrm_4_12.sc_classes</code>.
     */
    public static final ScClasses SC_CLASSES = com.sms.sis.db.tables.ScClasses.SC_CLASSES;

    /**
     * The table <code>sugarcrm_4_12.sc_classes_audit</code>.
     */
    public static final ScClassesAudit SC_CLASSES_AUDIT = com.sms.sis.db.tables.ScClassesAudit.SC_CLASSES_AUDIT;

    /**
     * The table <code>sugarcrm_4_12.sc_companies</code>.
     */
    public static final ScCompanies SC_COMPANIES = com.sms.sis.db.tables.ScCompanies.SC_COMPANIES;

    /**
     * The table <code>sugarcrm_4_12.sc_companies_audit</code>.
     */
    public static final ScCompaniesAudit SC_COMPANIES_AUDIT = com.sms.sis.db.tables.ScCompaniesAudit.SC_COMPANIES_AUDIT;

    /**
     * The table <code>sugarcrm_4_12.sc_companies_sc_companycontracts_c</code>.
     */
    public static final ScCompaniesScCompanycontractsC SC_COMPANIES_SC_COMPANYCONTRACTS_C = com.sms.sis.db.tables.ScCompaniesScCompanycontractsC.SC_COMPANIES_SC_COMPANYCONTRACTS_C;

    /**
     * The table <code>sugarcrm_4_12.sc_companies_sc_patients_c</code>.
     */
    public static final ScCompaniesScPatientsC SC_COMPANIES_SC_PATIENTS_C = com.sms.sis.db.tables.ScCompaniesScPatientsC.SC_COMPANIES_SC_PATIENTS_C;

    /**
     * The table <code>sugarcrm_4_12.sc_companycontracts</code>.
     */
    public static final ScCompanycontracts SC_COMPANYCONTRACTS = com.sms.sis.db.tables.ScCompanycontracts.SC_COMPANYCONTRACTS;

    /**
     * The table <code>sugarcrm_4_12.sc_companycontracts_accounts_c</code>.
     */
    public static final ScCompanycontractsAccountsC SC_COMPANYCONTRACTS_ACCOUNTS_C = com.sms.sis.db.tables.ScCompanycontractsAccountsC.SC_COMPANYCONTRACTS_ACCOUNTS_C;

    /**
     * The table <code>sugarcrm_4_12.sc_companycontracts_audit</code>.
     */
    public static final ScCompanycontractsAudit SC_COMPANYCONTRACTS_AUDIT = com.sms.sis.db.tables.ScCompanycontractsAudit.SC_COMPANYCONTRACTS_AUDIT;

    /**
     * The table <code>sugarcrm_4_12.sc_companycontracts_sc_constraints_c</code>.
     */
    public static final ScCompanycontractsScConstraintsC SC_COMPANYCONTRACTS_SC_CONSTRAINTS_C = com.sms.sis.db.tables.ScCompanycontractsScConstraintsC.SC_COMPANYCONTRACTS_SC_CONSTRAINTS_C;

    /**
     * The table <code>sugarcrm_4_12.sc_companycontracts_sc_contracts_classes_c</code>.
     */
    public static final ScCompanycontractsScContractsClassesC SC_COMPANYCONTRACTS_SC_CONTRACTS_CLASSES_C = com.sms.sis.db.tables.ScCompanycontractsScContractsClassesC.SC_COMPANYCONTRACTS_SC_CONTRACTS_CLASSES_C;

    /**
     * The table <code>sugarcrm_4_12.sc_constraints</code>.
     */
    public static final ScConstraints SC_CONSTRAINTS = com.sms.sis.db.tables.ScConstraints.SC_CONSTRAINTS;

    /**
     * The table <code>sugarcrm_4_12.sc_constraints_audit</code>.
     */
    public static final ScConstraintsAudit SC_CONSTRAINTS_AUDIT = com.sms.sis.db.tables.ScConstraintsAudit.SC_CONSTRAINTS_AUDIT;

    /**
     * The table <code>sugarcrm_4_12.sc_constraints_sc_companycontracts_c</code>.
     */
    public static final ScConstraintsScCompanycontractsC SC_CONSTRAINTS_SC_COMPANYCONTRACTS_C = com.sms.sis.db.tables.ScConstraintsScCompanycontractsC.SC_CONSTRAINTS_SC_COMPANYCONTRACTS_C;

    /**
     * The table <code>sugarcrm_4_12.sc_constraints_sc_contracts_classes_c</code>.
     */
    public static final ScConstraintsScContractsClassesC SC_CONSTRAINTS_SC_CONTRACTS_CLASSES_C = com.sms.sis.db.tables.ScConstraintsScContractsClassesC.SC_CONSTRAINTS_SC_CONTRACTS_CLASSES_C;

    /**
     * The table <code>sugarcrm_4_12.sc_contractsclassgroup</code>.
     */
    public static final ScContractsclassgroup SC_CONTRACTSCLASSGROUP = com.sms.sis.db.tables.ScContractsclassgroup.SC_CONTRACTSCLASSGROUP;

    /**
     * The table <code>sugarcrm_4_12.sc_contractsclassgroup_audit</code>.
     */
    public static final ScContractsclassgroupAudit SC_CONTRACTSCLASSGROUP_AUDIT = com.sms.sis.db.tables.ScContractsclassgroupAudit.SC_CONTRACTSCLASSGROUP_AUDIT;

    /**
     * The table <code>sugarcrm_4_12.sc_contractsclassservice</code>.
     */
    public static final ScContractsclassservice SC_CONTRACTSCLASSSERVICE = com.sms.sis.db.tables.ScContractsclassservice.SC_CONTRACTSCLASSSERVICE;

    /**
     * The table <code>sugarcrm_4_12.sc_contractsclassservice_audit</code>.
     */
    public static final ScContractsclassserviceAudit SC_CONTRACTSCLASSSERVICE_AUDIT = com.sms.sis.db.tables.ScContractsclassserviceAudit.SC_CONTRACTSCLASSSERVICE_AUDIT;

    /**
     * The table <code>sugarcrm_4_12.sc_contractsclasssupergroup</code>.
     */
    public static final ScContractsclasssupergroup SC_CONTRACTSCLASSSUPERGROUP = com.sms.sis.db.tables.ScContractsclasssupergroup.SC_CONTRACTSCLASSSUPERGROUP;

    /**
     * The table <code>sugarcrm_4_12.sc_contractsclasssupergroup_audit</code>.
     */
    public static final ScContractsclasssupergroupAudit SC_CONTRACTSCLASSSUPERGROUP_AUDIT = com.sms.sis.db.tables.ScContractsclasssupergroupAudit.SC_CONTRACTSCLASSSUPERGROUP_AUDIT;

    /**
     * The table <code>sugarcrm_4_12.sc_contracts_classes</code>.
     */
    public static final ScContractsClasses SC_CONTRACTS_CLASSES = com.sms.sis.db.tables.ScContractsClasses.SC_CONTRACTS_CLASSES;

    /**
     * The table <code>sugarcrm_4_12.sc_contracts_classes_audit</code>.
     */
    public static final ScContractsClassesAudit SC_CONTRACTS_CLASSES_AUDIT = com.sms.sis.db.tables.ScContractsClassesAudit.SC_CONTRACTS_CLASSES_AUDIT;

    /**
     * The table <code>sugarcrm_4_12.sc_contracts_classes_sc_contractsclassgroup_c</code>.
     */
    public static final ScContractsClassesScContractsclassgroupC SC_CONTRACTS_CLASSES_SC_CONTRACTSCLASSGROUP_C = com.sms.sis.db.tables.ScContractsClassesScContractsclassgroupC.SC_CONTRACTS_CLASSES_SC_CONTRACTSCLASSGROUP_C;

    /**
     * The table <code>sugarcrm_4_12.sc_contracts_classes_sc_contractsclassservice_c</code>.
     */
    public static final ScContractsClassesScContractsclassserviceC SC_CONTRACTS_CLASSES_SC_CONTRACTSCLASSSERVICE_C = com.sms.sis.db.tables.ScContractsClassesScContractsclassserviceC.SC_CONTRACTS_CLASSES_SC_CONTRACTSCLASSSERVICE_C;

    /**
     * The table <code>sugarcrm_4_12.sc_contracts_classes_sc_contractsclasssupergroup_c</code>.
     */
    public static final ScContractsClassesScContractsclasssupergroupC SC_CONTRACTS_CLASSES_SC_CONTRACTSCLASSSUPERGROUP_C = com.sms.sis.db.tables.ScContractsClassesScContractsclasssupergroupC.SC_CONTRACTS_CLASSES_SC_CONTRACTSCLASSSUPERGROUP_C;

    /**
     * The table <code>sugarcrm_4_12.sc_contracts_classes_sc_patients_c</code>.
     */
    public static final ScContractsClassesScPatientsC SC_CONTRACTS_CLASSES_SC_PATIENTS_C = com.sms.sis.db.tables.ScContractsClassesScPatientsC.SC_CONTRACTS_CLASSES_SC_PATIENTS_C;

    /**
     * The table <code>sugarcrm_4_12.sc_contracts_types</code>.
     */
    public static final ScContractsTypes SC_CONTRACTS_TYPES = com.sms.sis.db.tables.ScContractsTypes.SC_CONTRACTS_TYPES;

    /**
     * The table <code>sugarcrm_4_12.sc_contracts_types_audit</code>.
     */
    public static final ScContractsTypesAudit SC_CONTRACTS_TYPES_AUDIT = com.sms.sis.db.tables.ScContractsTypesAudit.SC_CONTRACTS_TYPES_AUDIT;

    /**
     * The table <code>sugarcrm_4_12.sc_deduction</code>.
     */
    public static final ScDeduction SC_DEDUCTION = com.sms.sis.db.tables.ScDeduction.SC_DEDUCTION;

    /**
     * The table <code>sugarcrm_4_12.sc_deduction_audit</code>.
     */
    public static final ScDeductionAudit SC_DEDUCTION_AUDIT = com.sms.sis.db.tables.ScDeductionAudit.SC_DEDUCTION_AUDIT;

    /**
     * The table <code>sugarcrm_4_12.sc_deduction_cstm</code>.
     */
    public static final ScDeductionCstm SC_DEDUCTION_CSTM = com.sms.sis.db.tables.ScDeductionCstm.SC_DEDUCTION_CSTM;

    /**
     * The table <code>sugarcrm_4_12.sc_doctortype</code>.
     */
    public static final ScDoctortype SC_DOCTORTYPE = com.sms.sis.db.tables.ScDoctortype.SC_DOCTORTYPE;

    /**
     * The table <code>sugarcrm_4_12.sc_doctortype_audit</code>.
     */
    public static final ScDoctortypeAudit SC_DOCTORTYPE_AUDIT = com.sms.sis.db.tables.ScDoctortypeAudit.SC_DOCTORTYPE_AUDIT;

    /**
     * The table <code>sugarcrm_4_12.sc_doctortype_tasks_c</code>.
     */
    public static final ScDoctortypeTasksC SC_DOCTORTYPE_TASKS_C = com.sms.sis.db.tables.ScDoctortypeTasksC.SC_DOCTORTYPE_TASKS_C;

    /**
     * The table <code>sugarcrm_4_12.sc_drugs</code>.
     */
    public static final ScDrugs SC_DRUGS = com.sms.sis.db.tables.ScDrugs.SC_DRUGS;

    /**
     * The table <code>sugarcrm_4_12.sc_drugs_audit</code>.
     */
    public static final ScDrugsAudit SC_DRUGS_AUDIT = com.sms.sis.db.tables.ScDrugsAudit.SC_DRUGS_AUDIT;

    /**
     * The table <code>sugarcrm_4_12.sc_drugs_sc_ingredients_c</code>.
     */
    public static final ScDrugsScIngredientsC SC_DRUGS_SC_INGREDIENTS_C = com.sms.sis.db.tables.ScDrugsScIngredientsC.SC_DRUGS_SC_INGREDIENTS_C;

    /**
     * The table <code>sugarcrm_4_12.sc_icd10</code>.
     */
    public static final ScIcd10 SC_ICD10 = com.sms.sis.db.tables.ScIcd10.SC_ICD10;

    /**
     * The table <code>sugarcrm_4_12.sc_icd10_audit</code>.
     */
    public static final ScIcd10Audit SC_ICD10_AUDIT = com.sms.sis.db.tables.ScIcd10Audit.SC_ICD10_AUDIT;

    /**
     * The table <code>sugarcrm_4_12.sc_ingredients</code>.
     */
    public static final ScIngredients SC_INGREDIENTS = com.sms.sis.db.tables.ScIngredients.SC_INGREDIENTS;

    /**
     * The table <code>sugarcrm_4_12.sc_ingredients_audit</code>.
     */
    public static final ScIngredientsAudit SC_INGREDIENTS_AUDIT = com.sms.sis.db.tables.ScIngredientsAudit.SC_INGREDIENTS_AUDIT;

    /**
     * The table <code>sugarcrm_4_12.sc_installments</code>.
     */
    public static final ScInstallments SC_INSTALLMENTS = com.sms.sis.db.tables.ScInstallments.SC_INSTALLMENTS;

    /**
     * The table <code>sugarcrm_4_12.sc_installments_audit</code>.
     */
    public static final ScInstallmentsAudit SC_INSTALLMENTS_AUDIT = com.sms.sis.db.tables.ScInstallmentsAudit.SC_INSTALLMENTS_AUDIT;

    /**
     * The table <code>sugarcrm_4_12.sc_installments_sc_companycontracts_c</code>.
     */
    public static final ScInstallmentsScCompanycontractsC SC_INSTALLMENTS_SC_COMPANYCONTRACTS_C = com.sms.sis.db.tables.ScInstallmentsScCompanycontractsC.SC_INSTALLMENTS_SC_COMPANYCONTRACTS_C;

    /**
     * The table <code>sugarcrm_4_12.sc_insurancecompanies</code>.
     */
    public static final ScInsurancecompanies SC_INSURANCECOMPANIES = com.sms.sis.db.tables.ScInsurancecompanies.SC_INSURANCECOMPANIES;

    /**
     * The table <code>sugarcrm_4_12.sc_insurancecompanies_audit</code>.
     */
    public static final ScInsurancecompaniesAudit SC_INSURANCECOMPANIES_AUDIT = com.sms.sis.db.tables.ScInsurancecompaniesAudit.SC_INSURANCECOMPANIES_AUDIT;

    /**
     * The table <code>sugarcrm_4_12.sc_insurancecompanies_sc_companycontracts_c</code>.
     */
    public static final ScInsurancecompaniesScCompanycontractsC SC_INSURANCECOMPANIES_SC_COMPANYCONTRACTS_C = com.sms.sis.db.tables.ScInsurancecompaniesScCompanycontractsC.SC_INSURANCECOMPANIES_SC_COMPANYCONTRACTS_C;

    /**
     * The table <code>sugarcrm_4_12.sc_patches</code>.
     */
    public static final ScPatches SC_PATCHES = com.sms.sis.db.tables.ScPatches.SC_PATCHES;

    /**
     * The table <code>sugarcrm_4_12.sc_patches_audit</code>.
     */
    public static final ScPatchesAudit SC_PATCHES_AUDIT = com.sms.sis.db.tables.ScPatchesAudit.SC_PATCHES_AUDIT;

    /**
     * The table <code>sugarcrm_4_12.sc_patches_sc_claims_c</code>.
     */
    public static final ScPatchesScClaimsC SC_PATCHES_SC_CLAIMS_C = com.sms.sis.db.tables.ScPatchesScClaimsC.SC_PATCHES_SC_CLAIMS_C;

    /**
     * The table <code>sugarcrm_4_12.sc_patches_ss_journal_entry_c</code>.
     */
    public static final ScPatchesSsJournalEntryC SC_PATCHES_SS_JOURNAL_ENTRY_C = com.sms.sis.db.tables.ScPatchesSsJournalEntryC.SC_PATCHES_SS_JOURNAL_ENTRY_C;

    /**
     * The table <code>sugarcrm_4_12.sc_patients</code>.
     */
    public static final ScPatients SC_PATIENTS = com.sms.sis.db.tables.ScPatients.SC_PATIENTS;

    /**
     * The table <code>sugarcrm_4_12.sc_patients_accounts_c</code>.
     */
    public static final ScPatientsAccountsC SC_PATIENTS_ACCOUNTS_C = com.sms.sis.db.tables.ScPatientsAccountsC.SC_PATIENTS_ACCOUNTS_C;

    /**
     * The table <code>sugarcrm_4_12.sc_patients_audit</code>.
     */
    public static final ScPatientsAudit SC_PATIENTS_AUDIT = com.sms.sis.db.tables.ScPatientsAudit.SC_PATIENTS_AUDIT;

    /**
     * The table <code>sugarcrm_4_12.sc_patients_contacts_c</code>.
     */
    public static final ScPatientsContactsC SC_PATIENTS_CONTACTS_C = com.sms.sis.db.tables.ScPatientsContactsC.SC_PATIENTS_CONTACTS_C;

    /**
     * The table <code>sugarcrm_4_12.sc_patients_sc_approvaldetails_1_c</code>.
     */
    public static final ScPatientsScApprovaldetails_1C SC_PATIENTS_SC_APPROVALDETAILS_1_C = com.sms.sis.db.tables.ScPatientsScApprovaldetails_1C.SC_PATIENTS_SC_APPROVALDETAILS_1_C;

    /**
     * The table <code>sugarcrm_4_12.sc_patients_sc_claims_c</code>.
     */
    public static final ScPatientsScClaimsC SC_PATIENTS_SC_CLAIMS_C = com.sms.sis.db.tables.ScPatientsScClaimsC.SC_PATIENTS_SC_CLAIMS_C;

    /**
     * The table <code>sugarcrm_4_12.sc_patients_sc_patients_c</code>.
     */
    public static final ScPatientsScPatientsC SC_PATIENTS_SC_PATIENTS_C = com.sms.sis.db.tables.ScPatientsScPatientsC.SC_PATIENTS_SC_PATIENTS_C;

    /**
     * The table <code>sugarcrm_4_12.sc_patients_tasks_c</code>.
     */
    public static final ScPatientsTasksC SC_PATIENTS_TASKS_C = com.sms.sis.db.tables.ScPatientsTasksC.SC_PATIENTS_TASKS_C;

    /**
     * The table <code>sugarcrm_4_12.sc_patienttype</code>.
     */
    public static final ScPatienttype SC_PATIENTTYPE = com.sms.sis.db.tables.ScPatienttype.SC_PATIENTTYPE;

    /**
     * The table <code>sugarcrm_4_12.sc_patienttype_audit</code>.
     */
    public static final ScPatienttypeAudit SC_PATIENTTYPE_AUDIT = com.sms.sis.db.tables.ScPatienttypeAudit.SC_PATIENTTYPE_AUDIT;

    /**
     * The table <code>sugarcrm_4_12.sc_price_lists</code>.
     */
    public static final ScPriceLists SC_PRICE_LISTS = com.sms.sis.db.tables.ScPriceLists.SC_PRICE_LISTS;

    /**
     * The table <code>sugarcrm_4_12.sc_price_lists_audit</code>.
     */
    public static final ScPriceListsAudit SC_PRICE_LISTS_AUDIT = com.sms.sis.db.tables.ScPriceListsAudit.SC_PRICE_LISTS_AUDIT;

    /**
     * The table <code>sugarcrm_4_12.sc_price_lists_sc_price_list_services_c</code>.
     */
    public static final ScPriceListsScPriceListServicesC SC_PRICE_LISTS_SC_PRICE_LIST_SERVICES_C = com.sms.sis.db.tables.ScPriceListsScPriceListServicesC.SC_PRICE_LISTS_SC_PRICE_LIST_SERVICES_C;

    /**
     * The table <code>sugarcrm_4_12.sc_price_lists_sc_providers_c</code>.
     */
    public static final ScPriceListsScProvidersC SC_PRICE_LISTS_SC_PROVIDERS_C = com.sms.sis.db.tables.ScPriceListsScProvidersC.SC_PRICE_LISTS_SC_PROVIDERS_C;

    /**
     * The table <code>sugarcrm_4_12.sc_price_list_services</code>.
     */
    public static final ScPriceListServices SC_PRICE_LIST_SERVICES = com.sms.sis.db.tables.ScPriceListServices.SC_PRICE_LIST_SERVICES;

    /**
     * The table <code>sugarcrm_4_12.sc_price_list_services_audit</code>.
     */
    public static final ScPriceListServicesAudit SC_PRICE_LIST_SERVICES_AUDIT = com.sms.sis.db.tables.ScPriceListServicesAudit.SC_PRICE_LIST_SERVICES_AUDIT;

    /**
     * The table <code>sugarcrm_4_12.sc_providerbranches</code>.
     */
    public static final ScProviderbranches SC_PROVIDERBRANCHES = com.sms.sis.db.tables.ScProviderbranches.SC_PROVIDERBRANCHES;

    /**
     * The table <code>sugarcrm_4_12.sc_providerbranches_audit</code>.
     */
    public static final ScProviderbranchesAudit SC_PROVIDERBRANCHES_AUDIT = com.sms.sis.db.tables.ScProviderbranchesAudit.SC_PROVIDERBRANCHES_AUDIT;

    /**
     * The table <code>sugarcrm_4_12.sc_providerbranches_sc_providers_c</code>.
     */
    public static final ScProviderbranchesScProvidersC SC_PROVIDERBRANCHES_SC_PROVIDERS_C = com.sms.sis.db.tables.ScProviderbranchesScProvidersC.SC_PROVIDERBRANCHES_SC_PROVIDERS_C;

    /**
     * The table <code>sugarcrm_4_12.sc_providers</code>.
     */
    public static final ScProviders SC_PROVIDERS = com.sms.sis.db.tables.ScProviders.SC_PROVIDERS;

    /**
     * The table <code>sugarcrm_4_12.sc_providerservices</code>.
     */
    public static final ScProviderservices SC_PROVIDERSERVICES = com.sms.sis.db.tables.ScProviderservices.SC_PROVIDERSERVICES;

    /**
     * The table <code>sugarcrm_4_12.sc_providerservices_audit</code>.
     */
    public static final ScProviderservicesAudit SC_PROVIDERSERVICES_AUDIT = com.sms.sis.db.tables.ScProviderservicesAudit.SC_PROVIDERSERVICES_AUDIT;

    /**
     * The table <code>sugarcrm_4_12.sc_providerservices_calls_c</code>.
     */
    public static final ScProviderservicesCallsC SC_PROVIDERSERVICES_CALLS_C = com.sms.sis.db.tables.ScProviderservicesCallsC.SC_PROVIDERSERVICES_CALLS_C;

    /**
     * The table <code>sugarcrm_4_12.sc_providers_audit</code>.
     */
    public static final ScProvidersAudit SC_PROVIDERS_AUDIT = com.sms.sis.db.tables.ScProvidersAudit.SC_PROVIDERS_AUDIT;

    /**
     * The table <code>sugarcrm_4_12.sc_providers_calls_1_c</code>.
     */
    public static final ScProvidersCalls_1C SC_PROVIDERS_CALLS_1_C = com.sms.sis.db.tables.ScProvidersCalls_1C.SC_PROVIDERS_CALLS_1_C;

    /**
     * The table <code>sugarcrm_4_12.sc_providers_calls_c</code>.
     */
    public static final ScProvidersCallsC SC_PROVIDERS_CALLS_C = com.sms.sis.db.tables.ScProvidersCallsC.SC_PROVIDERS_CALLS_C;

    /**
     * The table <code>sugarcrm_4_12.sc_providers_contacts_c</code>.
     */
    public static final ScProvidersContactsC SC_PROVIDERS_CONTACTS_C = com.sms.sis.db.tables.ScProvidersContactsC.SC_PROVIDERS_CONTACTS_C;

    /**
     * The table <code>sugarcrm_4_12.sc_providers_sc_claims_1_c</code>.
     */
    public static final ScProvidersScClaims_1C SC_PROVIDERS_SC_CLAIMS_1_C = com.sms.sis.db.tables.ScProvidersScClaims_1C.SC_PROVIDERS_SC_CLAIMS_1_C;

    /**
     * The table <code>sugarcrm_4_12.sc_providers_sc_claims_c</code>.
     */
    public static final ScProvidersScClaimsC SC_PROVIDERS_SC_CLAIMS_C = com.sms.sis.db.tables.ScProvidersScClaimsC.SC_PROVIDERS_SC_CLAIMS_C;

    /**
     * The table <code>sugarcrm_4_12.sc_providers_sc_patches_c</code>.
     */
    public static final ScProvidersScPatchesC SC_PROVIDERS_SC_PATCHES_C = com.sms.sis.db.tables.ScProvidersScPatchesC.SC_PROVIDERS_SC_PATCHES_C;

    /**
     * The table <code>sugarcrm_4_12.sc_providers_sc_providerservices_c</code>.
     */
    public static final ScProvidersScProviderservicesC SC_PROVIDERS_SC_PROVIDERSERVICES_C = com.sms.sis.db.tables.ScProvidersScProviderservicesC.SC_PROVIDERS_SC_PROVIDERSERVICES_C;

    /**
     * The table <code>sugarcrm_4_12.sc_providers_sc_providerservices_c_backup</code>.
     */
    public static final ScProvidersScProviderservicesCBackup SC_PROVIDERS_SC_PROVIDERSERVICES_C_BACKUP = com.sms.sis.db.tables.ScProvidersScProviderservicesCBackup.SC_PROVIDERS_SC_PROVIDERSERVICES_C_BACKUP;

    /**
     * The table <code>sugarcrm_4_12.sc_providers_tasks_c</code>.
     */
    public static final ScProvidersTasksC SC_PROVIDERS_TASKS_C = com.sms.sis.db.tables.ScProvidersTasksC.SC_PROVIDERS_TASKS_C;

    /**
     * The table <code>sugarcrm_4_12.sc_providers_tp_module1_c</code>.
     */
    public static final ScProvidersTpModule1C SC_PROVIDERS_TP_MODULE1_C = com.sms.sis.db.tables.ScProvidersTpModule1C.SC_PROVIDERS_TP_MODULE1_C;

    /**
     * The table <code>sugarcrm_4_12.sc_providertypes</code>.
     */
    public static final ScProvidertypes SC_PROVIDERTYPES = com.sms.sis.db.tables.ScProvidertypes.SC_PROVIDERTYPES;

    /**
     * The table <code>sugarcrm_4_12.sc_providertypes_audit</code>.
     */
    public static final ScProvidertypesAudit SC_PROVIDERTYPES_AUDIT = com.sms.sis.db.tables.ScProvidertypesAudit.SC_PROVIDERTYPES_AUDIT;

    /**
     * The table <code>sugarcrm_4_12.sc_provider_bands</code>.
     */
    public static final ScProviderBands SC_PROVIDER_BANDS = com.sms.sis.db.tables.ScProviderBands.SC_PROVIDER_BANDS;

    /**
     * The table <code>sugarcrm_4_12.sc_provider_bands_audit</code>.
     */
    public static final ScProviderBandsAudit SC_PROVIDER_BANDS_AUDIT = com.sms.sis.db.tables.ScProviderBandsAudit.SC_PROVIDER_BANDS_AUDIT;

    /**
     * The table <code>sugarcrm_4_12.sc_provider_bands_sc_providers_c</code>.
     */
    public static final ScProviderBandsScProvidersC SC_PROVIDER_BANDS_SC_PROVIDERS_C = com.sms.sis.db.tables.ScProviderBandsScProvidersC.SC_PROVIDER_BANDS_SC_PROVIDERS_C;

    /**
     * The table <code>sugarcrm_4_12.sc_regions</code>.
     */
    public static final ScRegions SC_REGIONS = com.sms.sis.db.tables.ScRegions.SC_REGIONS;

    /**
     * The table <code>sugarcrm_4_12.sc_regions_audit</code>.
     */
    public static final ScRegionsAudit SC_REGIONS_AUDIT = com.sms.sis.db.tables.ScRegionsAudit.SC_REGIONS_AUDIT;

    /**
     * The table <code>sugarcrm_4_12.sc_reports</code>.
     */
    public static final ScReports SC_REPORTS = com.sms.sis.db.tables.ScReports.SC_REPORTS;

    /**
     * The table <code>sugarcrm_4_12.sc_reports_audit</code>.
     */
    public static final ScReportsAudit SC_REPORTS_AUDIT = com.sms.sis.db.tables.ScReportsAudit.SC_REPORTS_AUDIT;

    /**
     * The table <code>sugarcrm_4_12.sc_servicegroups</code>.
     */
    public static final ScServicegroups SC_SERVICEGROUPS = com.sms.sis.db.tables.ScServicegroups.SC_SERVICEGROUPS;

    /**
     * The table <code>sugarcrm_4_12.sc_servicegroups_audit</code>.
     */
    public static final ScServicegroupsAudit SC_SERVICEGROUPS_AUDIT = com.sms.sis.db.tables.ScServicegroupsAudit.SC_SERVICEGROUPS_AUDIT;

    /**
     * The table <code>sugarcrm_4_12.sc_servicegroups_sc_services_c</code>.
     */
    public static final ScServicegroupsScServicesC SC_SERVICEGROUPS_SC_SERVICES_C = com.sms.sis.db.tables.ScServicegroupsScServicesC.SC_SERVICEGROUPS_SC_SERVICES_C;

    /**
     * The table <code>sugarcrm_4_12.sc_services</code>.
     */
    public static final ScServices SC_SERVICES = com.sms.sis.db.tables.ScServices.SC_SERVICES;

    /**
     * The table <code>sugarcrm_4_12.sc_servicessupergroups</code>.
     */
    public static final ScServicessupergroups SC_SERVICESSUPERGROUPS = com.sms.sis.db.tables.ScServicessupergroups.SC_SERVICESSUPERGROUPS;

    /**
     * The table <code>sugarcrm_4_12.sc_servicessupergroups_audit</code>.
     */
    public static final ScServicessupergroupsAudit SC_SERVICESSUPERGROUPS_AUDIT = com.sms.sis.db.tables.ScServicessupergroupsAudit.SC_SERVICESSUPERGROUPS_AUDIT;

    /**
     * The table <code>sugarcrm_4_12.sc_servicessupergroups_sc_servicegroups_c</code>.
     */
    public static final ScServicessupergroupsScServicegroupsC SC_SERVICESSUPERGROUPS_SC_SERVICEGROUPS_C = com.sms.sis.db.tables.ScServicessupergroupsScServicegroupsC.SC_SERVICESSUPERGROUPS_SC_SERVICEGROUPS_C;

    /**
     * The table <code>sugarcrm_4_12.sc_services_audit</code>.
     */
    public static final ScServicesAudit SC_SERVICES_AUDIT = com.sms.sis.db.tables.ScServicesAudit.SC_SERVICES_AUDIT;

    /**
     * The table <code>sugarcrm_4_12.sc_sitedoctors</code>.
     */
    public static final ScSitedoctors SC_SITEDOCTORS = com.sms.sis.db.tables.ScSitedoctors.SC_SITEDOCTORS;

    /**
     * The table <code>sugarcrm_4_12.sc_sitedoctors_audit</code>.
     */
    public static final ScSitedoctorsAudit SC_SITEDOCTORS_AUDIT = com.sms.sis.db.tables.ScSitedoctorsAudit.SC_SITEDOCTORS_AUDIT;

    /**
     * The table <code>sugarcrm_4_12.sc_sitedoctors_calls_c</code>.
     */
    public static final ScSitedoctorsCallsC SC_SITEDOCTORS_CALLS_C = com.sms.sis.db.tables.ScSitedoctorsCallsC.SC_SITEDOCTORS_CALLS_C;

    /**
     * The table <code>sugarcrm_4_12.sc_sitedoctors_sc_claims_c</code>.
     */
    public static final ScSitedoctorsScClaimsC SC_SITEDOCTORS_SC_CLAIMS_C = com.sms.sis.db.tables.ScSitedoctorsScClaimsC.SC_SITEDOCTORS_SC_CLAIMS_C;

    /**
     * The table <code>sugarcrm_4_12.sc_sitedoctors_sc_companycontracts_c</code>.
     */
    public static final ScSitedoctorsScCompanycontractsC SC_SITEDOCTORS_SC_COMPANYCONTRACTS_C = com.sms.sis.db.tables.ScSitedoctorsScCompanycontractsC.SC_SITEDOCTORS_SC_COMPANYCONTRACTS_C;

    /**
     * The table <code>sugarcrm_4_12.sc_sms</code>.
     */
    public static final ScSms SC_SMS = com.sms.sis.db.tables.ScSms.SC_SMS;

    /**
     * The table <code>sugarcrm_4_12.sc_sms_audit</code>.
     */
    public static final ScSmsAudit SC_SMS_AUDIT = com.sms.sis.db.tables.ScSmsAudit.SC_SMS_AUDIT;

    /**
     * The table <code>sugarcrm_4_12.sc_sms_sc_patients_c</code>.
     */
    public static final ScSmsScPatientsC SC_SMS_SC_PATIENTS_C = com.sms.sis.db.tables.ScSmsScPatientsC.SC_SMS_SC_PATIENTS_C;

    /**
     * The table <code>sugarcrm_4_12.sc_test</code>.
     */
    public static final ScTest SC_TEST = com.sms.sis.db.tables.ScTest.SC_TEST;

    /**
     * The table <code>sugarcrm_4_12.sc_testidmodule</code>.
     */
    public static final ScTestidmodule SC_TESTIDMODULE = com.sms.sis.db.tables.ScTestidmodule.SC_TESTIDMODULE;

    /**
     * The table <code>sugarcrm_4_12.sc_testidmodule_audit</code>.
     */
    public static final ScTestidmoduleAudit SC_TESTIDMODULE_AUDIT = com.sms.sis.db.tables.ScTestidmoduleAudit.SC_TESTIDMODULE_AUDIT;

    /**
     * The table <code>sugarcrm_4_12.sc_testidmodule_sc_claims_c</code>.
     */
    public static final ScTestidmoduleScClaimsC SC_TESTIDMODULE_SC_CLAIMS_C = com.sms.sis.db.tables.ScTestidmoduleScClaimsC.SC_TESTIDMODULE_SC_CLAIMS_C;

    /**
     * The table <code>sugarcrm_4_12.sc_test_audit</code>.
     */
    public static final ScTestAudit SC_TEST_AUDIT = com.sms.sis.db.tables.ScTestAudit.SC_TEST_AUDIT;

    /**
     * The table <code>sugarcrm_4_12.ss_accounting_settings</code>.
     */
    public static final SsAccountingSettings SS_ACCOUNTING_SETTINGS = com.sms.sis.db.tables.SsAccountingSettings.SS_ACCOUNTING_SETTINGS;

    /**
     * The table <code>sugarcrm_4_12.ss_accounting_settings_audit</code>.
     */
    public static final SsAccountingSettingsAudit SS_ACCOUNTING_SETTINGS_AUDIT = com.sms.sis.db.tables.SsAccountingSettingsAudit.SS_ACCOUNTING_SETTINGS_AUDIT;

    /**
     * The table <code>sugarcrm_4_12.ss_balance_sheet_templates</code>.
     */
    public static final SsBalanceSheetTemplates SS_BALANCE_SHEET_TEMPLATES = com.sms.sis.db.tables.SsBalanceSheetTemplates.SS_BALANCE_SHEET_TEMPLATES;

    /**
     * The table <code>sugarcrm_4_12.ss_balance_sheet_templates_audit</code>.
     */
    public static final SsBalanceSheetTemplatesAudit SS_BALANCE_SHEET_TEMPLATES_AUDIT = com.sms.sis.db.tables.SsBalanceSheetTemplatesAudit.SS_BALANCE_SHEET_TEMPLATES_AUDIT;

    /**
     * The table <code>sugarcrm_4_12.ss_balance_sheet_templates_ss_b_s_template_details_c</code>.
     */
    public static final SsBalanceSheetTemplatesSsBSTemplateDetailsC SS_BALANCE_SHEET_TEMPLATES_SS_B_S_TEMPLATE_DETAILS_C = com.sms.sis.db.tables.SsBalanceSheetTemplatesSsBSTemplateDetailsC.SS_BALANCE_SHEET_TEMPLATES_SS_B_S_TEMPLATE_DETAILS_C;

    /**
     * The table <code>sugarcrm_4_12.ss_banks</code>.
     */
    public static final SsBanks SS_BANKS = com.sms.sis.db.tables.SsBanks.SS_BANKS;

    /**
     * The table <code>sugarcrm_4_12.ss_banks_audit</code>.
     */
    public static final SsBanksAudit SS_BANKS_AUDIT = com.sms.sis.db.tables.SsBanksAudit.SS_BANKS_AUDIT;

    /**
     * The table <code>sugarcrm_4_12.ss_banks_ss_outgoing_checks_c</code>.
     */
    public static final SsBanksSsOutgoingChecksC SS_BANKS_SS_OUTGOING_CHECKS_C = com.sms.sis.db.tables.SsBanksSsOutgoingChecksC.SS_BANKS_SS_OUTGOING_CHECKS_C;

    /**
     * The table <code>sugarcrm_4_12.ss_branches</code>.
     */
    public static final SsBranches SS_BRANCHES = com.sms.sis.db.tables.SsBranches.SS_BRANCHES;

    /**
     * The table <code>sugarcrm_4_12.ss_branches_audit</code>.
     */
    public static final SsBranchesAudit SS_BRANCHES_AUDIT = com.sms.sis.db.tables.SsBranchesAudit.SS_BRANCHES_AUDIT;

    /**
     * The table <code>sugarcrm_4_12.ss_branch_cases</code>.
     */
    public static final SsBranchCases SS_BRANCH_CASES = com.sms.sis.db.tables.SsBranchCases.SS_BRANCH_CASES;

    /**
     * The table <code>sugarcrm_4_12.ss_branch_cases_audit</code>.
     */
    public static final SsBranchCasesAudit SS_BRANCH_CASES_AUDIT = com.sms.sis.db.tables.SsBranchCasesAudit.SS_BRANCH_CASES_AUDIT;

    /**
     * The table <code>sugarcrm_4_12.ss_bs_template_data</code>.
     */
    public static final SsBsTemplateData SS_BS_TEMPLATE_DATA = com.sms.sis.db.tables.SsBsTemplateData.SS_BS_TEMPLATE_DATA;

    /**
     * The table <code>sugarcrm_4_12.ss_bs_template_data_audit</code>.
     */
    public static final SsBsTemplateDataAudit SS_BS_TEMPLATE_DATA_AUDIT = com.sms.sis.db.tables.SsBsTemplateDataAudit.SS_BS_TEMPLATE_DATA_AUDIT;

    /**
     * The table <code>sugarcrm_4_12.ss_b_s_template_details</code>.
     */
    public static final SsBSTemplateDetails SS_B_S_TEMPLATE_DETAILS = com.sms.sis.db.tables.SsBSTemplateDetails.SS_B_S_TEMPLATE_DETAILS;

    /**
     * The table <code>sugarcrm_4_12.ss_b_s_template_details_audit</code>.
     */
    public static final SsBSTemplateDetailsAudit SS_B_S_TEMPLATE_DETAILS_AUDIT = com.sms.sis.db.tables.SsBSTemplateDetailsAudit.SS_B_S_TEMPLATE_DETAILS_AUDIT;

    /**
     * The table <code>sugarcrm_4_12.ss_b_s_template_details_ss_gl_account_c</code>.
     */
    public static final SsBSTemplateDetailsSsGlAccountC SS_B_S_TEMPLATE_DETAILS_SS_GL_ACCOUNT_C = com.sms.sis.db.tables.SsBSTemplateDetailsSsGlAccountC.SS_B_S_TEMPLATE_DETAILS_SS_GL_ACCOUNT_C;

    /**
     * The table <code>sugarcrm_4_12.ss_cost_centers</code>.
     */
    public static final SsCostCenters SS_COST_CENTERS = com.sms.sis.db.tables.SsCostCenters.SS_COST_CENTERS;

    /**
     * The table <code>sugarcrm_4_12.ss_cost_centers_audit</code>.
     */
    public static final SsCostCentersAudit SS_COST_CENTERS_AUDIT = com.sms.sis.db.tables.SsCostCentersAudit.SS_COST_CENTERS_AUDIT;

    /**
     * The table <code>sugarcrm_4_12.ss_customer_invoices</code>.
     */
    public static final SsCustomerInvoices SS_CUSTOMER_INVOICES = com.sms.sis.db.tables.SsCustomerInvoices.SS_CUSTOMER_INVOICES;

    /**
     * The table <code>sugarcrm_4_12.ss_customer_invoices_audit</code>.
     */
    public static final SsCustomerInvoicesAudit SS_CUSTOMER_INVOICES_AUDIT = com.sms.sis.db.tables.SsCustomerInvoicesAudit.SS_CUSTOMER_INVOICES_AUDIT;

    /**
     * The table <code>sugarcrm_4_12.ss_fiscal_year</code>.
     */
    public static final SsFiscalYear SS_FISCAL_YEAR = com.sms.sis.db.tables.SsFiscalYear.SS_FISCAL_YEAR;

    /**
     * The table <code>sugarcrm_4_12.ss_fiscal_year_audit</code>.
     */
    public static final SsFiscalYearAudit SS_FISCAL_YEAR_AUDIT = com.sms.sis.db.tables.SsFiscalYearAudit.SS_FISCAL_YEAR_AUDIT;

    /**
     * The table <code>sugarcrm_4_12.ss_gl_account</code>.
     */
    public static final SsGlAccount SS_GL_ACCOUNT = com.sms.sis.db.tables.SsGlAccount.SS_GL_ACCOUNT;

    /**
     * The table <code>sugarcrm_4_12.ss_gl_accounts_distribution</code>.
     */
    public static final SsGlAccountsDistribution SS_GL_ACCOUNTS_DISTRIBUTION = com.sms.sis.db.tables.SsGlAccountsDistribution.SS_GL_ACCOUNTS_DISTRIBUTION;

    /**
     * The table <code>sugarcrm_4_12.ss_gl_accounts_distribution_audit</code>.
     */
    public static final SsGlAccountsDistributionAudit SS_GL_ACCOUNTS_DISTRIBUTION_AUDIT = com.sms.sis.db.tables.SsGlAccountsDistributionAudit.SS_GL_ACCOUNTS_DISTRIBUTION_AUDIT;

    /**
     * The table <code>sugarcrm_4_12.ss_gl_account_audit</code>.
     */
    public static final SsGlAccountAudit SS_GL_ACCOUNT_AUDIT = com.sms.sis.db.tables.SsGlAccountAudit.SS_GL_ACCOUNT_AUDIT;

    /**
     * The table <code>sugarcrm_4_12.ss_gl_account_ss_gl_account_c</code>.
     */
    public static final SsGlAccountSsGlAccountC SS_GL_ACCOUNT_SS_GL_ACCOUNT_C = com.sms.sis.db.tables.SsGlAccountSsGlAccountC.SS_GL_ACCOUNT_SS_GL_ACCOUNT_C;

    /**
     * The table <code>sugarcrm_4_12.ss_income_statemant_templates</code>.
     */
    public static final SsIncomeStatemantTemplates SS_INCOME_STATEMANT_TEMPLATES = com.sms.sis.db.tables.SsIncomeStatemantTemplates.SS_INCOME_STATEMANT_TEMPLATES;

    /**
     * The table <code>sugarcrm_4_12.ss_income_statemant_templates_audit</code>.
     */
    public static final SsIncomeStatemantTemplatesAudit SS_INCOME_STATEMANT_TEMPLATES_AUDIT = com.sms.sis.db.tables.SsIncomeStatemantTemplatesAudit.SS_INCOME_STATEMANT_TEMPLATES_AUDIT;

    /**
     * The table <code>sugarcrm_4_12.ss_income_statemant_templates_ss_i_s_template_details_c</code>.
     */
    public static final SsIncomeStatemantTemplatesSsISTemplateDetailsC SS_INCOME_STATEMANT_TEMPLATES_SS_I_S_TEMPLATE_DETAILS_C = com.sms.sis.db.tables.SsIncomeStatemantTemplatesSsISTemplateDetailsC.SS_INCOME_STATEMANT_TEMPLATES_SS_I_S_TEMPLATE_DETAILS_C;

    /**
     * The table <code>sugarcrm_4_12.ss_incoming_checks</code>.
     */
    public static final SsIncomingChecks SS_INCOMING_CHECKS = com.sms.sis.db.tables.SsIncomingChecks.SS_INCOMING_CHECKS;

    /**
     * The table <code>sugarcrm_4_12.ss_incoming_checks_audit</code>.
     */
    public static final SsIncomingChecksAudit SS_INCOMING_CHECKS_AUDIT = com.sms.sis.db.tables.SsIncomingChecksAudit.SS_INCOMING_CHECKS_AUDIT;

    /**
     * The table <code>sugarcrm_4_12.ss_is_template_data</code>.
     */
    public static final SsIsTemplateData SS_IS_TEMPLATE_DATA = com.sms.sis.db.tables.SsIsTemplateData.SS_IS_TEMPLATE_DATA;

    /**
     * The table <code>sugarcrm_4_12.ss_is_template_data_audit</code>.
     */
    public static final SsIsTemplateDataAudit SS_IS_TEMPLATE_DATA_AUDIT = com.sms.sis.db.tables.SsIsTemplateDataAudit.SS_IS_TEMPLATE_DATA_AUDIT;

    /**
     * The table <code>sugarcrm_4_12.ss_i_s_template_details</code>.
     */
    public static final SsISTemplateDetails SS_I_S_TEMPLATE_DETAILS = com.sms.sis.db.tables.SsISTemplateDetails.SS_I_S_TEMPLATE_DETAILS;

    /**
     * The table <code>sugarcrm_4_12.ss_i_s_template_details_audit</code>.
     */
    public static final SsISTemplateDetailsAudit SS_I_S_TEMPLATE_DETAILS_AUDIT = com.sms.sis.db.tables.SsISTemplateDetailsAudit.SS_I_S_TEMPLATE_DETAILS_AUDIT;

    /**
     * The table <code>sugarcrm_4_12.ss_i_s_template_details_ss_gl_account_c</code>.
     */
    public static final SsISTemplateDetailsSsGlAccountC SS_I_S_TEMPLATE_DETAILS_SS_GL_ACCOUNT_C = com.sms.sis.db.tables.SsISTemplateDetailsSsGlAccountC.SS_I_S_TEMPLATE_DETAILS_SS_GL_ACCOUNT_C;

    /**
     * The table <code>sugarcrm_4_12.ss_journal_entry</code>.
     */
    public static final SsJournalEntry SS_JOURNAL_ENTRY = com.sms.sis.db.tables.SsJournalEntry.SS_JOURNAL_ENTRY;

    /**
     * The table <code>sugarcrm_4_12.ss_journal_entry_audit</code>.
     */
    public static final SsJournalEntryAudit SS_JOURNAL_ENTRY_AUDIT = com.sms.sis.db.tables.SsJournalEntryAudit.SS_JOURNAL_ENTRY_AUDIT;

    /**
     * The table <code>sugarcrm_4_12.ss_journal_entry_row</code>.
     */
    public static final SsJournalEntryRow SS_JOURNAL_ENTRY_ROW = com.sms.sis.db.tables.SsJournalEntryRow.SS_JOURNAL_ENTRY_ROW;

    /**
     * The table <code>sugarcrm_4_12.ss_journal_entry_row_audit</code>.
     */
    public static final SsJournalEntryRowAudit SS_JOURNAL_ENTRY_ROW_AUDIT = com.sms.sis.db.tables.SsJournalEntryRowAudit.SS_JOURNAL_ENTRY_ROW_AUDIT;

    /**
     * The table <code>sugarcrm_4_12.ss_journal_entry_ss_journal_entry_row_c</code>.
     */
    public static final SsJournalEntrySsJournalEntryRowC SS_JOURNAL_ENTRY_SS_JOURNAL_ENTRY_ROW_C = com.sms.sis.db.tables.SsJournalEntrySsJournalEntryRowC.SS_JOURNAL_ENTRY_SS_JOURNAL_ENTRY_ROW_C;

    /**
     * The table <code>sugarcrm_4_12.ss_outgoing_checks</code>.
     */
    public static final SsOutgoingChecks SS_OUTGOING_CHECKS = com.sms.sis.db.tables.SsOutgoingChecks.SS_OUTGOING_CHECKS;

    /**
     * The table <code>sugarcrm_4_12.ss_outgoing_checks_audit</code>.
     */
    public static final SsOutgoingChecksAudit SS_OUTGOING_CHECKS_AUDIT = com.sms.sis.db.tables.SsOutgoingChecksAudit.SS_OUTGOING_CHECKS_AUDIT;

    /**
     * The table <code>sugarcrm_4_12.ss_payables</code>.
     */
    public static final SsPayables SS_PAYABLES = com.sms.sis.db.tables.SsPayables.SS_PAYABLES;

    /**
     * The table <code>sugarcrm_4_12.ss_payables_audit</code>.
     */
    public static final SsPayablesAudit SS_PAYABLES_AUDIT = com.sms.sis.db.tables.SsPayablesAudit.SS_PAYABLES_AUDIT;

    /**
     * The table <code>sugarcrm_4_12.ss_payables_ss_gl_accounts_distribution_c</code>.
     */
    public static final SsPayablesSsGlAccountsDistributionC SS_PAYABLES_SS_GL_ACCOUNTS_DISTRIBUTION_C = com.sms.sis.db.tables.SsPayablesSsGlAccountsDistributionC.SS_PAYABLES_SS_GL_ACCOUNTS_DISTRIBUTION_C;

    /**
     * The table <code>sugarcrm_4_12.ss_payables_ss_outgoing_checks_c</code>.
     */
    public static final SsPayablesSsOutgoingChecksC SS_PAYABLES_SS_OUTGOING_CHECKS_C = com.sms.sis.db.tables.SsPayablesSsOutgoingChecksC.SS_PAYABLES_SS_OUTGOING_CHECKS_C;

    /**
     * The table <code>sugarcrm_4_12.ss_provider_invoices</code>.
     */
    public static final SsProviderInvoices SS_PROVIDER_INVOICES = com.sms.sis.db.tables.SsProviderInvoices.SS_PROVIDER_INVOICES;

    /**
     * The table <code>sugarcrm_4_12.ss_provider_invoices_audit</code>.
     */
    public static final SsProviderInvoicesAudit SS_PROVIDER_INVOICES_AUDIT = com.sms.sis.db.tables.SsProviderInvoicesAudit.SS_PROVIDER_INVOICES_AUDIT;

    /**
     * The table <code>sugarcrm_4_12.ss_receivables</code>.
     */
    public static final SsReceivables SS_RECEIVABLES = com.sms.sis.db.tables.SsReceivables.SS_RECEIVABLES;

    /**
     * The table <code>sugarcrm_4_12.ss_receivables_audit</code>.
     */
    public static final SsReceivablesAudit SS_RECEIVABLES_AUDIT = com.sms.sis.db.tables.SsReceivablesAudit.SS_RECEIVABLES_AUDIT;

    /**
     * The table <code>sugarcrm_4_12.ss_receivables_ss_gl_accounts_distribution_c</code>.
     */
    public static final SsReceivablesSsGlAccountsDistributionC SS_RECEIVABLES_SS_GL_ACCOUNTS_DISTRIBUTION_C = com.sms.sis.db.tables.SsReceivablesSsGlAccountsDistributionC.SS_RECEIVABLES_SS_GL_ACCOUNTS_DISTRIBUTION_C;

    /**
     * The table <code>sugarcrm_4_12.ss_receivables_ss_gl_account_c</code>.
     */
    public static final SsReceivablesSsGlAccountC SS_RECEIVABLES_SS_GL_ACCOUNT_C = com.sms.sis.db.tables.SsReceivablesSsGlAccountC.SS_RECEIVABLES_SS_GL_ACCOUNT_C;

    /**
     * The table <code>sugarcrm_4_12.ss_receivables_ss_incoming_checks_c</code>.
     */
    public static final SsReceivablesSsIncomingChecksC SS_RECEIVABLES_SS_INCOMING_CHECKS_C = com.sms.sis.db.tables.SsReceivablesSsIncomingChecksC.SS_RECEIVABLES_SS_INCOMING_CHECKS_C;

    /**
     * The table <code>sugarcrm_4_12.sugarfeed</code>.
     */
    public static final Sugarfeed SUGARFEED = com.sms.sis.db.tables.Sugarfeed.SUGARFEED;

    /**
     * The table <code>sugarcrm_4_12.tasks</code>.
     */
    public static final Tasks TASKS = com.sms.sis.db.tables.Tasks.TASKS;

    /**
     * The table <code>sugarcrm_4_12.tasks_cstm</code>.
     */
    public static final TasksCstm TASKS_CSTM = com.sms.sis.db.tables.TasksCstm.TASKS_CSTM;

    /**
     * The table <code>sugarcrm_4_12.tasks_documents_1_c</code>.
     */
    public static final TasksDocuments_1C TASKS_DOCUMENTS_1_C = com.sms.sis.db.tables.TasksDocuments_1C.TASKS_DOCUMENTS_1_C;

    /**
     * The table <code>sugarcrm_4_12.testinglong</code>.
     */
    public static final Testinglong TESTINGLONG = com.sms.sis.db.tables.Testinglong.TESTINGLONG;

    /**
     * The table <code>sugarcrm_4_12.tp_module1</code>.
     */
    public static final TpModule1 TP_MODULE1 = com.sms.sis.db.tables.TpModule1.TP_MODULE1;

    /**
     * The table <code>sugarcrm_4_12.tp_module1_audit</code>.
     */
    public static final TpModule1Audit TP_MODULE1_AUDIT = com.sms.sis.db.tables.TpModule1Audit.TP_MODULE1_AUDIT;

    /**
     * The table <code>sugarcrm_4_12.tp_module1_sc_areas_c</code>.
     */
    public static final TpModule1ScAreasC TP_MODULE1_SC_AREAS_C = com.sms.sis.db.tables.TpModule1ScAreasC.TP_MODULE1_SC_AREAS_C;

    /**
     * The table <code>sugarcrm_4_12.tp_module1_sc_regions_c</code>.
     */
    public static final TpModule1ScRegionsC TP_MODULE1_SC_REGIONS_C = com.sms.sis.db.tables.TpModule1ScRegionsC.TP_MODULE1_SC_REGIONS_C;

    /**
     * The table <code>sugarcrm_4_12.tracker</code>.
     */
    public static final Tracker TRACKER = com.sms.sis.db.tables.Tracker.TRACKER;

    /**
     * The table <code>sugarcrm_4_12.upgrade_history</code>.
     */
    public static final UpgradeHistory UPGRADE_HISTORY = com.sms.sis.db.tables.UpgradeHistory.UPGRADE_HISTORY;

    /**
     * The table <code>sugarcrm_4_12.users</code>.
     */
    public static final Users USERS = com.sms.sis.db.tables.Users.USERS;

    /**
     * The table <code>sugarcrm_4_12.users_cstm</code>.
     */
    public static final UsersCstm USERS_CSTM = com.sms.sis.db.tables.UsersCstm.USERS_CSTM;

    /**
     * The table <code>sugarcrm_4_12.users_feeds</code>.
     */
    public static final UsersFeeds USERS_FEEDS = com.sms.sis.db.tables.UsersFeeds.USERS_FEEDS;

    /**
     * The table <code>sugarcrm_4_12.users_last_import</code>.
     */
    public static final UsersLastImport USERS_LAST_IMPORT = com.sms.sis.db.tables.UsersLastImport.USERS_LAST_IMPORT;

    /**
     * The table <code>sugarcrm_4_12.users_password_link</code>.
     */
    public static final UsersPasswordLink USERS_PASSWORD_LINK = com.sms.sis.db.tables.UsersPasswordLink.USERS_PASSWORD_LINK;

    /**
     * The table <code>sugarcrm_4_12.users_signatures</code>.
     */
    public static final UsersSignatures USERS_SIGNATURES = com.sms.sis.db.tables.UsersSignatures.USERS_SIGNATURES;

    /**
     * The table <code>sugarcrm_4_12.user_preferences</code>.
     */
    public static final UserPreferences USER_PREFERENCES = com.sms.sis.db.tables.UserPreferences.USER_PREFERENCES;

    /**
     * The table <code>sugarcrm_4_12.vcals</code>.
     */
    public static final Vcals VCALS = com.sms.sis.db.tables.Vcals.VCALS;

    /**
     * The table <code>sugarcrm_4_12.versions</code>.
     */
    public static final Versions VERSIONS = com.sms.sis.db.tables.Versions.VERSIONS;

    /**
     * The table <code>sugarcrm_4_12._tempproviderbranches</code>.
     */
    public static final _Tempproviderbranches _TEMPPROVIDERBRANCHES = com.sms.sis.db.tables._Tempproviderbranches._TEMPPROVIDERBRANCHES;
}
