/*
 * This file is generated by jOOQ.
*/
package com.sms.sis.db.tables.records;


import com.sms.sis.db.tables._Tempproviderbranches;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record9;
import org.jooq.Row9;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class _TempproviderbranchesRecord extends UpdatableRecordImpl<_TempproviderbranchesRecord> implements Record9<String, String, String, String, String, String, String, String, Integer> {

    private static final long serialVersionUID = -586569697;

    /**
     * Setter for <code>sugarcrm_4_12._tempproviderbranches.providerName</code>.
     */
    public void setProvidername(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>sugarcrm_4_12._tempproviderbranches.providerName</code>.
     */
    public String getProvidername() {
        return (String) get(0);
    }

    /**
     * Setter for <code>sugarcrm_4_12._tempproviderbranches.area</code>.
     */
    public void setArea(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>sugarcrm_4_12._tempproviderbranches.area</code>.
     */
    public String getArea() {
        return (String) get(1);
    }

    /**
     * Setter for <code>sugarcrm_4_12._tempproviderbranches.address</code>.
     */
    public void setAddress(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>sugarcrm_4_12._tempproviderbranches.address</code>.
     */
    public String getAddress() {
        return (String) get(2);
    }

    /**
     * Setter for <code>sugarcrm_4_12._tempproviderbranches.phone1</code>.
     */
    public void setPhone1(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>sugarcrm_4_12._tempproviderbranches.phone1</code>.
     */
    public String getPhone1() {
        return (String) get(3);
    }

    /**
     * Setter for <code>sugarcrm_4_12._tempproviderbranches.phone2</code>.
     */
    public void setPhone2(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>sugarcrm_4_12._tempproviderbranches.phone2</code>.
     */
    public String getPhone2() {
        return (String) get(4);
    }

    /**
     * Setter for <code>sugarcrm_4_12._tempproviderbranches.phone3</code>.
     */
    public void setPhone3(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>sugarcrm_4_12._tempproviderbranches.phone3</code>.
     */
    public String getPhone3() {
        return (String) get(5);
    }

    /**
     * Setter for <code>sugarcrm_4_12._tempproviderbranches.phone4</code>.
     */
    public void setPhone4(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>sugarcrm_4_12._tempproviderbranches.phone4</code>.
     */
    public String getPhone4() {
        return (String) get(6);
    }

    /**
     * Setter for <code>sugarcrm_4_12._tempproviderbranches.fax</code>.
     */
    public void setFax(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>sugarcrm_4_12._tempproviderbranches.fax</code>.
     */
    public String getFax() {
        return (String) get(7);
    }

    /**
     * Setter for <code>sugarcrm_4_12._tempproviderbranches.id</code>.
     */
    public void setId(Integer value) {
        set(8, value);
    }

    /**
     * Getter for <code>sugarcrm_4_12._tempproviderbranches.id</code>.
     */
    public Integer getId() {
        return (Integer) get(8);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record9 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row9<String, String, String, String, String, String, String, String, Integer> fieldsRow() {
        return (Row9) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row9<String, String, String, String, String, String, String, String, Integer> valuesRow() {
        return (Row9) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field1() {
        return _Tempproviderbranches._TEMPPROVIDERBRANCHES.PROVIDERNAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return _Tempproviderbranches._TEMPPROVIDERBRANCHES.AREA;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return _Tempproviderbranches._TEMPPROVIDERBRANCHES.ADDRESS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return _Tempproviderbranches._TEMPPROVIDERBRANCHES.PHONE1;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return _Tempproviderbranches._TEMPPROVIDERBRANCHES.PHONE2;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return _Tempproviderbranches._TEMPPROVIDERBRANCHES.PHONE3;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field7() {
        return _Tempproviderbranches._TEMPPROVIDERBRANCHES.PHONE4;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field8() {
        return _Tempproviderbranches._TEMPPROVIDERBRANCHES.FAX;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field9() {
        return _Tempproviderbranches._TEMPPROVIDERBRANCHES.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value1() {
        return getProvidername();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getArea();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getAddress();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getPhone1();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getPhone2();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getPhone3();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value7() {
        return getPhone4();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value8() {
        return getFax();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value9() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public _TempproviderbranchesRecord value1(String value) {
        setProvidername(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public _TempproviderbranchesRecord value2(String value) {
        setArea(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public _TempproviderbranchesRecord value3(String value) {
        setAddress(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public _TempproviderbranchesRecord value4(String value) {
        setPhone1(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public _TempproviderbranchesRecord value5(String value) {
        setPhone2(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public _TempproviderbranchesRecord value6(String value) {
        setPhone3(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public _TempproviderbranchesRecord value7(String value) {
        setPhone4(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public _TempproviderbranchesRecord value8(String value) {
        setFax(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public _TempproviderbranchesRecord value9(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public _TempproviderbranchesRecord values(String value1, String value2, String value3, String value4, String value5, String value6, String value7, String value8, Integer value9) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached _TempproviderbranchesRecord
     */
    public _TempproviderbranchesRecord() {
        super(_Tempproviderbranches._TEMPPROVIDERBRANCHES);
    }

    /**
     * Create a detached, initialised _TempproviderbranchesRecord
     */
    public _TempproviderbranchesRecord(String providername, String area, String address, String phone1, String phone2, String phone3, String phone4, String fax, Integer id) {
        super(_Tempproviderbranches._TEMPPROVIDERBRANCHES);

        set(0, providername);
        set(1, area);
        set(2, address);
        set(3, phone1);
        set(4, phone2);
        set(5, phone3);
        set(6, phone4);
        set(7, fax);
        set(8, id);
    }
}
