/*
 * This file is generated by jOOQ.
*/
package com.sms.sis.db.tables.records;


import com.sms.sis.db.tables.CustomFields;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record13;
import org.jooq.Row13;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CustomFieldsRecord extends TableRecordImpl<CustomFieldsRecord> implements Record13<String, Integer, String, String, String, String, String, String, String, String, String, String, Byte> {

    private static final long serialVersionUID = 2039109529;

    /**
     * Setter for <code>sugarcrm_4_12.custom_fields.bean_id</code>.
     */
    public void setBeanId(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>sugarcrm_4_12.custom_fields.bean_id</code>.
     */
    public String getBeanId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>sugarcrm_4_12.custom_fields.set_num</code>.
     */
    public void setSetNum(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>sugarcrm_4_12.custom_fields.set_num</code>.
     */
    public Integer getSetNum() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>sugarcrm_4_12.custom_fields.field0</code>.
     */
    public void setField0(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>sugarcrm_4_12.custom_fields.field0</code>.
     */
    public String getField0() {
        return (String) get(2);
    }

    /**
     * Setter for <code>sugarcrm_4_12.custom_fields.field1</code>.
     */
    public void setField1(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>sugarcrm_4_12.custom_fields.field1</code>.
     */
    public String getField1() {
        return (String) get(3);
    }

    /**
     * Setter for <code>sugarcrm_4_12.custom_fields.field2</code>.
     */
    public void setField2(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>sugarcrm_4_12.custom_fields.field2</code>.
     */
    public String getField2() {
        return (String) get(4);
    }

    /**
     * Setter for <code>sugarcrm_4_12.custom_fields.field3</code>.
     */
    public void setField3(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>sugarcrm_4_12.custom_fields.field3</code>.
     */
    public String getField3() {
        return (String) get(5);
    }

    /**
     * Setter for <code>sugarcrm_4_12.custom_fields.field4</code>.
     */
    public void setField4(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>sugarcrm_4_12.custom_fields.field4</code>.
     */
    public String getField4() {
        return (String) get(6);
    }

    /**
     * Setter for <code>sugarcrm_4_12.custom_fields.field5</code>.
     */
    public void setField5(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>sugarcrm_4_12.custom_fields.field5</code>.
     */
    public String getField5() {
        return (String) get(7);
    }

    /**
     * Setter for <code>sugarcrm_4_12.custom_fields.field6</code>.
     */
    public void setField6(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>sugarcrm_4_12.custom_fields.field6</code>.
     */
    public String getField6() {
        return (String) get(8);
    }

    /**
     * Setter for <code>sugarcrm_4_12.custom_fields.field7</code>.
     */
    public void setField7(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>sugarcrm_4_12.custom_fields.field7</code>.
     */
    public String getField7() {
        return (String) get(9);
    }

    /**
     * Setter for <code>sugarcrm_4_12.custom_fields.field8</code>.
     */
    public void setField8(String value) {
        set(10, value);
    }

    /**
     * Getter for <code>sugarcrm_4_12.custom_fields.field8</code>.
     */
    public String getField8() {
        return (String) get(10);
    }

    /**
     * Setter for <code>sugarcrm_4_12.custom_fields.field9</code>.
     */
    public void setField9(String value) {
        set(11, value);
    }

    /**
     * Getter for <code>sugarcrm_4_12.custom_fields.field9</code>.
     */
    public String getField9() {
        return (String) get(11);
    }

    /**
     * Setter for <code>sugarcrm_4_12.custom_fields.deleted</code>.
     */
    public void setDeleted(Byte value) {
        set(12, value);
    }

    /**
     * Getter for <code>sugarcrm_4_12.custom_fields.deleted</code>.
     */
    public Byte getDeleted() {
        return (Byte) get(12);
    }

    // -------------------------------------------------------------------------
    // Record13 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row13<String, Integer, String, String, String, String, String, String, String, String, String, String, Byte> fieldsRow() {
        return (Row13) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row13<String, Integer, String, String, String, String, String, String, String, String, String, String, Byte> valuesRow() {
        return (Row13) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field1() {
        return CustomFields.CUSTOM_FIELDS.BEAN_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return CustomFields.CUSTOM_FIELDS.SET_NUM;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return CustomFields.CUSTOM_FIELDS.FIELD0;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return CustomFields.CUSTOM_FIELDS.FIELD1;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return CustomFields.CUSTOM_FIELDS.FIELD2;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return CustomFields.CUSTOM_FIELDS.FIELD3;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field7() {
        return CustomFields.CUSTOM_FIELDS.FIELD4;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field8() {
        return CustomFields.CUSTOM_FIELDS.FIELD5;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field9() {
        return CustomFields.CUSTOM_FIELDS.FIELD6;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field10() {
        return CustomFields.CUSTOM_FIELDS.FIELD7;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field11() {
        return CustomFields.CUSTOM_FIELDS.FIELD8;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field12() {
        return CustomFields.CUSTOM_FIELDS.FIELD9;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Byte> field13() {
        return CustomFields.CUSTOM_FIELDS.DELETED;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value1() {
        return getBeanId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getSetNum();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getField0();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getField1();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getField2();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getField3();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value7() {
        return getField4();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value8() {
        return getField5();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value9() {
        return getField6();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value10() {
        return getField7();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value11() {
        return getField8();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value12() {
        return getField9();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte value13() {
        return getDeleted();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CustomFieldsRecord value1(String value) {
        setBeanId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CustomFieldsRecord value2(Integer value) {
        setSetNum(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CustomFieldsRecord value3(String value) {
        setField0(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CustomFieldsRecord value4(String value) {
        setField1(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CustomFieldsRecord value5(String value) {
        setField2(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CustomFieldsRecord value6(String value) {
        setField3(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CustomFieldsRecord value7(String value) {
        setField4(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CustomFieldsRecord value8(String value) {
        setField5(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CustomFieldsRecord value9(String value) {
        setField6(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CustomFieldsRecord value10(String value) {
        setField7(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CustomFieldsRecord value11(String value) {
        setField8(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CustomFieldsRecord value12(String value) {
        setField9(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CustomFieldsRecord value13(Byte value) {
        setDeleted(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CustomFieldsRecord values(String value1, Integer value2, String value3, String value4, String value5, String value6, String value7, String value8, String value9, String value10, String value11, String value12, Byte value13) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached CustomFieldsRecord
     */
    public CustomFieldsRecord() {
        super(CustomFields.CUSTOM_FIELDS);
    }

    /**
     * Create a detached, initialised CustomFieldsRecord
     */
    public CustomFieldsRecord(String beanId, Integer setNum, String field0, String field1, String field2, String field3, String field4, String field5, String field6, String field7, String field8, String field9, Byte deleted) {
        super(CustomFields.CUSTOM_FIELDS);

        set(0, beanId);
        set(1, setNum);
        set(2, field0);
        set(3, field1);
        set(4, field2);
        set(5, field3);
        set(6, field4);
        set(7, field5);
        set(8, field6);
        set(9, field7);
        set(10, field8);
        set(11, field9);
        set(12, deleted);
    }
}
