/*
 * This file is generated by jOOQ.
*/
package com.sms.sis.db.tables.records;


import com.sms.sis.db.tables.Folders;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record12;
import org.jooq.Row12;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class FoldersRecord extends UpdatableRecordImpl<FoldersRecord> implements Record12<String, String, String, String, Byte, Byte, Byte, String, String, String, String, Byte> {

    private static final long serialVersionUID = -1794399247;

    /**
     * Setter for <code>sugarcrm_4_12.folders.id</code>.
     */
    public void setId(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>sugarcrm_4_12.folders.id</code>.
     */
    public String getId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>sugarcrm_4_12.folders.name</code>.
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>sugarcrm_4_12.folders.name</code>.
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>sugarcrm_4_12.folders.folder_type</code>.
     */
    public void setFolderType(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>sugarcrm_4_12.folders.folder_type</code>.
     */
    public String getFolderType() {
        return (String) get(2);
    }

    /**
     * Setter for <code>sugarcrm_4_12.folders.parent_folder</code>.
     */
    public void setParentFolder(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>sugarcrm_4_12.folders.parent_folder</code>.
     */
    public String getParentFolder() {
        return (String) get(3);
    }

    /**
     * Setter for <code>sugarcrm_4_12.folders.has_child</code>.
     */
    public void setHasChild(Byte value) {
        set(4, value);
    }

    /**
     * Getter for <code>sugarcrm_4_12.folders.has_child</code>.
     */
    public Byte getHasChild() {
        return (Byte) get(4);
    }

    /**
     * Setter for <code>sugarcrm_4_12.folders.is_group</code>.
     */
    public void setIsGroup(Byte value) {
        set(5, value);
    }

    /**
     * Getter for <code>sugarcrm_4_12.folders.is_group</code>.
     */
    public Byte getIsGroup() {
        return (Byte) get(5);
    }

    /**
     * Setter for <code>sugarcrm_4_12.folders.is_dynamic</code>.
     */
    public void setIsDynamic(Byte value) {
        set(6, value);
    }

    /**
     * Getter for <code>sugarcrm_4_12.folders.is_dynamic</code>.
     */
    public Byte getIsDynamic() {
        return (Byte) get(6);
    }

    /**
     * Setter for <code>sugarcrm_4_12.folders.dynamic_query</code>.
     */
    public void setDynamicQuery(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>sugarcrm_4_12.folders.dynamic_query</code>.
     */
    public String getDynamicQuery() {
        return (String) get(7);
    }

    /**
     * Setter for <code>sugarcrm_4_12.folders.assign_to_id</code>.
     */
    public void setAssignToId(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>sugarcrm_4_12.folders.assign_to_id</code>.
     */
    public String getAssignToId() {
        return (String) get(8);
    }

    /**
     * Setter for <code>sugarcrm_4_12.folders.created_by</code>.
     */
    public void setCreatedBy(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>sugarcrm_4_12.folders.created_by</code>.
     */
    public String getCreatedBy() {
        return (String) get(9);
    }

    /**
     * Setter for <code>sugarcrm_4_12.folders.modified_by</code>.
     */
    public void setModifiedBy(String value) {
        set(10, value);
    }

    /**
     * Getter for <code>sugarcrm_4_12.folders.modified_by</code>.
     */
    public String getModifiedBy() {
        return (String) get(10);
    }

    /**
     * Setter for <code>sugarcrm_4_12.folders.deleted</code>.
     */
    public void setDeleted(Byte value) {
        set(11, value);
    }

    /**
     * Getter for <code>sugarcrm_4_12.folders.deleted</code>.
     */
    public Byte getDeleted() {
        return (Byte) get(11);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record12 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row12<String, String, String, String, Byte, Byte, Byte, String, String, String, String, Byte> fieldsRow() {
        return (Row12) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row12<String, String, String, String, Byte, Byte, Byte, String, String, String, String, Byte> valuesRow() {
        return (Row12) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field1() {
        return Folders.FOLDERS.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return Folders.FOLDERS.NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return Folders.FOLDERS.FOLDER_TYPE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return Folders.FOLDERS.PARENT_FOLDER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Byte> field5() {
        return Folders.FOLDERS.HAS_CHILD;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Byte> field6() {
        return Folders.FOLDERS.IS_GROUP;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Byte> field7() {
        return Folders.FOLDERS.IS_DYNAMIC;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field8() {
        return Folders.FOLDERS.DYNAMIC_QUERY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field9() {
        return Folders.FOLDERS.ASSIGN_TO_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field10() {
        return Folders.FOLDERS.CREATED_BY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field11() {
        return Folders.FOLDERS.MODIFIED_BY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Byte> field12() {
        return Folders.FOLDERS.DELETED;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getFolderType();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getParentFolder();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte value5() {
        return getHasChild();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte value6() {
        return getIsGroup();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte value7() {
        return getIsDynamic();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value8() {
        return getDynamicQuery();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value9() {
        return getAssignToId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value10() {
        return getCreatedBy();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value11() {
        return getModifiedBy();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte value12() {
        return getDeleted();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public FoldersRecord value1(String value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public FoldersRecord value2(String value) {
        setName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public FoldersRecord value3(String value) {
        setFolderType(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public FoldersRecord value4(String value) {
        setParentFolder(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public FoldersRecord value5(Byte value) {
        setHasChild(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public FoldersRecord value6(Byte value) {
        setIsGroup(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public FoldersRecord value7(Byte value) {
        setIsDynamic(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public FoldersRecord value8(String value) {
        setDynamicQuery(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public FoldersRecord value9(String value) {
        setAssignToId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public FoldersRecord value10(String value) {
        setCreatedBy(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public FoldersRecord value11(String value) {
        setModifiedBy(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public FoldersRecord value12(Byte value) {
        setDeleted(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public FoldersRecord values(String value1, String value2, String value3, String value4, Byte value5, Byte value6, Byte value7, String value8, String value9, String value10, String value11, Byte value12) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached FoldersRecord
     */
    public FoldersRecord() {
        super(Folders.FOLDERS);
    }

    /**
     * Create a detached, initialised FoldersRecord
     */
    public FoldersRecord(String id, String name, String folderType, String parentFolder, Byte hasChild, Byte isGroup, Byte isDynamic, String dynamicQuery, String assignToId, String createdBy, String modifiedBy, Byte deleted) {
        super(Folders.FOLDERS);

        set(0, id);
        set(1, name);
        set(2, folderType);
        set(3, parentFolder);
        set(4, hasChild);
        set(5, isGroup);
        set(6, isDynamic);
        set(7, dynamicQuery);
        set(8, assignToId);
        set(9, createdBy);
        set(10, modifiedBy);
        set(11, deleted);
    }
}
