/*
 * This file is generated by jOOQ.
*/
package com.sms.sis.db.tables.records;


import com.sms.sis.db.tables.ProjectsProducts;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ProjectsProductsRecord extends UpdatableRecordImpl<ProjectsProductsRecord> implements Record5<String, String, String, Timestamp, Byte> {

    private static final long serialVersionUID = -1231161257;

    /**
     * Setter for <code>sugarcrm_4_12.projects_products.id</code>.
     */
    public void setId(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>sugarcrm_4_12.projects_products.id</code>.
     */
    public String getId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>sugarcrm_4_12.projects_products.product_id</code>.
     */
    public void setProductId(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>sugarcrm_4_12.projects_products.product_id</code>.
     */
    public String getProductId() {
        return (String) get(1);
    }

    /**
     * Setter for <code>sugarcrm_4_12.projects_products.project_id</code>.
     */
    public void setProjectId(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>sugarcrm_4_12.projects_products.project_id</code>.
     */
    public String getProjectId() {
        return (String) get(2);
    }

    /**
     * Setter for <code>sugarcrm_4_12.projects_products.date_modified</code>.
     */
    public void setDateModified(Timestamp value) {
        set(3, value);
    }

    /**
     * Getter for <code>sugarcrm_4_12.projects_products.date_modified</code>.
     */
    public Timestamp getDateModified() {
        return (Timestamp) get(3);
    }

    /**
     * Setter for <code>sugarcrm_4_12.projects_products.deleted</code>.
     */
    public void setDeleted(Byte value) {
        set(4, value);
    }

    /**
     * Getter for <code>sugarcrm_4_12.projects_products.deleted</code>.
     */
    public Byte getDeleted() {
        return (Byte) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<String, String, String, Timestamp, Byte> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<String, String, String, Timestamp, Byte> valuesRow() {
        return (Row5) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field1() {
        return ProjectsProducts.PROJECTS_PRODUCTS.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return ProjectsProducts.PROJECTS_PRODUCTS.PRODUCT_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return ProjectsProducts.PROJECTS_PRODUCTS.PROJECT_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field4() {
        return ProjectsProducts.PROJECTS_PRODUCTS.DATE_MODIFIED;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Byte> field5() {
        return ProjectsProducts.PROJECTS_PRODUCTS.DELETED;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getProductId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getProjectId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value4() {
        return getDateModified();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte value5() {
        return getDeleted();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProjectsProductsRecord value1(String value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProjectsProductsRecord value2(String value) {
        setProductId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProjectsProductsRecord value3(String value) {
        setProjectId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProjectsProductsRecord value4(Timestamp value) {
        setDateModified(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProjectsProductsRecord value5(Byte value) {
        setDeleted(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProjectsProductsRecord values(String value1, String value2, String value3, Timestamp value4, Byte value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ProjectsProductsRecord
     */
    public ProjectsProductsRecord() {
        super(ProjectsProducts.PROJECTS_PRODUCTS);
    }

    /**
     * Create a detached, initialised ProjectsProductsRecord
     */
    public ProjectsProductsRecord(String id, String productId, String projectId, Timestamp dateModified, Byte deleted) {
        super(ProjectsProducts.PROJECTS_PRODUCTS);

        set(0, id);
        set(1, productId);
        set(2, projectId);
        set(3, dateModified);
        set(4, deleted);
    }
}
