/*
 * This file is generated by jOOQ.
*/
package com.sms.sis.db.tables.records;


import com.sms.sis.db.tables.ScContractsclassgroup;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record21;
import org.jooq.Row21;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ScContractsclassgroupRecord extends UpdatableRecordImpl<ScContractsclassgroupRecord> implements Record21<Integer, String, Timestamp, Timestamp, String, String, String, Byte, String, Integer, String, String, Integer, String, String, String, Byte, Byte, Integer, Integer, String> {

    private static final long serialVersionUID = 630640987;

    /**
     * Setter for <code>sugarcrm_4_12.sc_contractsclassgroup.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>sugarcrm_4_12.sc_contractsclassgroup.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>sugarcrm_4_12.sc_contractsclassgroup.name</code>.
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>sugarcrm_4_12.sc_contractsclassgroup.name</code>.
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>sugarcrm_4_12.sc_contractsclassgroup.date_entered</code>.
     */
    public void setDateEntered(Timestamp value) {
        set(2, value);
    }

    /**
     * Getter for <code>sugarcrm_4_12.sc_contractsclassgroup.date_entered</code>.
     */
    public Timestamp getDateEntered() {
        return (Timestamp) get(2);
    }

    /**
     * Setter for <code>sugarcrm_4_12.sc_contractsclassgroup.date_modified</code>.
     */
    public void setDateModified(Timestamp value) {
        set(3, value);
    }

    /**
     * Getter for <code>sugarcrm_4_12.sc_contractsclassgroup.date_modified</code>.
     */
    public Timestamp getDateModified() {
        return (Timestamp) get(3);
    }

    /**
     * Setter for <code>sugarcrm_4_12.sc_contractsclassgroup.modified_user_id</code>.
     */
    public void setModifiedUserId(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>sugarcrm_4_12.sc_contractsclassgroup.modified_user_id</code>.
     */
    public String getModifiedUserId() {
        return (String) get(4);
    }

    /**
     * Setter for <code>sugarcrm_4_12.sc_contractsclassgroup.created_by</code>.
     */
    public void setCreatedBy(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>sugarcrm_4_12.sc_contractsclassgroup.created_by</code>.
     */
    public String getCreatedBy() {
        return (String) get(5);
    }

    /**
     * Setter for <code>sugarcrm_4_12.sc_contractsclassgroup.description</code>.
     */
    public void setDescription(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>sugarcrm_4_12.sc_contractsclassgroup.description</code>.
     */
    public String getDescription() {
        return (String) get(6);
    }

    /**
     * Setter for <code>sugarcrm_4_12.sc_contractsclassgroup.deleted</code>.
     */
    public void setDeleted(Byte value) {
        set(7, value);
    }

    /**
     * Getter for <code>sugarcrm_4_12.sc_contractsclassgroup.deleted</code>.
     */
    public Byte getDeleted() {
        return (Byte) get(7);
    }

    /**
     * Setter for <code>sugarcrm_4_12.sc_contractsclassgroup.assigned_user_id</code>.
     */
    public void setAssignedUserId(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>sugarcrm_4_12.sc_contractsclassgroup.assigned_user_id</code>.
     */
    public String getAssignedUserId() {
        return (String) get(8);
    }

    /**
     * Setter for <code>sugarcrm_4_12.sc_contractsclassgroup.cmid</code>.
     */
    public void setCmid(Integer value) {
        set(9, value);
    }

    /**
     * Getter for <code>sugarcrm_4_12.sc_contractsclassgroup.cmid</code>.
     */
    public Integer getCmid() {
        return (Integer) get(9);
    }

    /**
     * Setter for <code>sugarcrm_4_12.sc_contractsclassgroup.sc_contracts_classes_id_c</code>.
     */
    public void setScContractsClassesIdC(String value) {
        set(10, value);
    }

    /**
     * Getter for <code>sugarcrm_4_12.sc_contractsclassgroup.sc_contracts_classes_id_c</code>.
     */
    public String getScContractsClassesIdC() {
        return (String) get(10);
    }

    /**
     * Setter for <code>sugarcrm_4_12.sc_contractsclassgroup.sc_companies_id_c</code>.
     */
    public void setScCompaniesIdC(String value) {
        set(11, value);
    }

    /**
     * Getter for <code>sugarcrm_4_12.sc_contractsclassgroup.sc_companies_id_c</code>.
     */
    public String getScCompaniesIdC() {
        return (String) get(11);
    }

    /**
     * Setter for <code>sugarcrm_4_12.sc_contractsclassgroup.contract_id</code>.
     */
    public void setContractId(Integer value) {
        set(12, value);
    }

    /**
     * Getter for <code>sugarcrm_4_12.sc_contractsclassgroup.contract_id</code>.
     */
    public Integer getContractId() {
        return (Integer) get(12);
    }

    /**
     * Setter for <code>sugarcrm_4_12.sc_contractsclassgroup.sc_classes_id_c</code>.
     */
    public void setScClassesIdC(String value) {
        set(13, value);
    }

    /**
     * Getter for <code>sugarcrm_4_12.sc_contractsclassgroup.sc_classes_id_c</code>.
     */
    public String getScClassesIdC() {
        return (String) get(13);
    }

    /**
     * Setter for <code>sugarcrm_4_12.sc_contractsclassgroup.sc_servicessupergroups_id_c</code>.
     */
    public void setScServicessupergroupsIdC(String value) {
        set(14, value);
    }

    /**
     * Getter for <code>sugarcrm_4_12.sc_contractsclassgroup.sc_servicessupergroups_id_c</code>.
     */
    public String getScServicessupergroupsIdC() {
        return (String) get(14);
    }

    /**
     * Setter for <code>sugarcrm_4_12.sc_contractsclassgroup.sc_servicegroups_id_c</code>.
     */
    public void setScServicegroupsIdC(String value) {
        set(15, value);
    }

    /**
     * Getter for <code>sugarcrm_4_12.sc_contractsclassgroup.sc_servicegroups_id_c</code>.
     */
    public String getScServicegroupsIdC() {
        return (String) get(15);
    }

    /**
     * Setter for <code>sugarcrm_4_12.sc_contractsclassgroup.area_cover</code>.
     */
    public void setAreaCover(Byte value) {
        set(16, value);
    }

    /**
     * Getter for <code>sugarcrm_4_12.sc_contractsclassgroup.area_cover</code>.
     */
    public Byte getAreaCover() {
        return (Byte) get(16);
    }

    /**
     * Setter for <code>sugarcrm_4_12.sc_contractsclassgroup.network_cover</code>.
     */
    public void setNetworkCover(Byte value) {
        set(17, value);
    }

    /**
     * Getter for <code>sugarcrm_4_12.sc_contractsclassgroup.network_cover</code>.
     */
    public Byte getNetworkCover() {
        return (Byte) get(17);
    }

    /**
     * Setter for <code>sugarcrm_4_12.sc_contractsclassgroup.max_val_limit</code>.
     */
    public void setMaxValLimit(Integer value) {
        set(18, value);
    }

    /**
     * Getter for <code>sugarcrm_4_12.sc_contractsclassgroup.max_val_limit</code>.
     */
    public Integer getMaxValLimit() {
        return (Integer) get(18);
    }

    /**
     * Setter for <code>sugarcrm_4_12.sc_contractsclassgroup.max_price_limit</code>.
     */
    public void setMaxPriceLimit(Integer value) {
        set(19, value);
    }

    /**
     * Getter for <code>sugarcrm_4_12.sc_contractsclassgroup.max_price_limit</code>.
     */
    public Integer getMaxPriceLimit() {
        return (Integer) get(19);
    }

    /**
     * Setter for <code>sugarcrm_4_12.sc_contractsclassgroup.remarks</code>.
     */
    public void setRemarks(String value) {
        set(20, value);
    }

    /**
     * Getter for <code>sugarcrm_4_12.sc_contractsclassgroup.remarks</code>.
     */
    public String getRemarks() {
        return (String) get(20);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record21 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row21<Integer, String, Timestamp, Timestamp, String, String, String, Byte, String, Integer, String, String, Integer, String, String, String, Byte, Byte, Integer, Integer, String> fieldsRow() {
        return (Row21) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row21<Integer, String, Timestamp, Timestamp, String, String, String, Byte, String, Integer, String, String, Integer, String, String, String, Byte, Byte, Integer, Integer, String> valuesRow() {
        return (Row21) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return ScContractsclassgroup.SC_CONTRACTSCLASSGROUP.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return ScContractsclassgroup.SC_CONTRACTSCLASSGROUP.NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field3() {
        return ScContractsclassgroup.SC_CONTRACTSCLASSGROUP.DATE_ENTERED;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field4() {
        return ScContractsclassgroup.SC_CONTRACTSCLASSGROUP.DATE_MODIFIED;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return ScContractsclassgroup.SC_CONTRACTSCLASSGROUP.MODIFIED_USER_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return ScContractsclassgroup.SC_CONTRACTSCLASSGROUP.CREATED_BY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field7() {
        return ScContractsclassgroup.SC_CONTRACTSCLASSGROUP.DESCRIPTION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Byte> field8() {
        return ScContractsclassgroup.SC_CONTRACTSCLASSGROUP.DELETED;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field9() {
        return ScContractsclassgroup.SC_CONTRACTSCLASSGROUP.ASSIGNED_USER_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field10() {
        return ScContractsclassgroup.SC_CONTRACTSCLASSGROUP.CMID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field11() {
        return ScContractsclassgroup.SC_CONTRACTSCLASSGROUP.SC_CONTRACTS_CLASSES_ID_C;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field12() {
        return ScContractsclassgroup.SC_CONTRACTSCLASSGROUP.SC_COMPANIES_ID_C;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field13() {
        return ScContractsclassgroup.SC_CONTRACTSCLASSGROUP.CONTRACT_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field14() {
        return ScContractsclassgroup.SC_CONTRACTSCLASSGROUP.SC_CLASSES_ID_C;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field15() {
        return ScContractsclassgroup.SC_CONTRACTSCLASSGROUP.SC_SERVICESSUPERGROUPS_ID_C;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field16() {
        return ScContractsclassgroup.SC_CONTRACTSCLASSGROUP.SC_SERVICEGROUPS_ID_C;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Byte> field17() {
        return ScContractsclassgroup.SC_CONTRACTSCLASSGROUP.AREA_COVER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Byte> field18() {
        return ScContractsclassgroup.SC_CONTRACTSCLASSGROUP.NETWORK_COVER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field19() {
        return ScContractsclassgroup.SC_CONTRACTSCLASSGROUP.MAX_VAL_LIMIT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field20() {
        return ScContractsclassgroup.SC_CONTRACTSCLASSGROUP.MAX_PRICE_LIMIT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field21() {
        return ScContractsclassgroup.SC_CONTRACTSCLASSGROUP.REMARKS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value3() {
        return getDateEntered();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value4() {
        return getDateModified();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getModifiedUserId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getCreatedBy();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value7() {
        return getDescription();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte value8() {
        return getDeleted();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value9() {
        return getAssignedUserId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value10() {
        return getCmid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value11() {
        return getScContractsClassesIdC();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value12() {
        return getScCompaniesIdC();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value13() {
        return getContractId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value14() {
        return getScClassesIdC();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value15() {
        return getScServicessupergroupsIdC();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value16() {
        return getScServicegroupsIdC();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte value17() {
        return getAreaCover();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte value18() {
        return getNetworkCover();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value19() {
        return getMaxValLimit();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value20() {
        return getMaxPriceLimit();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value21() {
        return getRemarks();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ScContractsclassgroupRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ScContractsclassgroupRecord value2(String value) {
        setName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ScContractsclassgroupRecord value3(Timestamp value) {
        setDateEntered(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ScContractsclassgroupRecord value4(Timestamp value) {
        setDateModified(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ScContractsclassgroupRecord value5(String value) {
        setModifiedUserId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ScContractsclassgroupRecord value6(String value) {
        setCreatedBy(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ScContractsclassgroupRecord value7(String value) {
        setDescription(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ScContractsclassgroupRecord value8(Byte value) {
        setDeleted(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ScContractsclassgroupRecord value9(String value) {
        setAssignedUserId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ScContractsclassgroupRecord value10(Integer value) {
        setCmid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ScContractsclassgroupRecord value11(String value) {
        setScContractsClassesIdC(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ScContractsclassgroupRecord value12(String value) {
        setScCompaniesIdC(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ScContractsclassgroupRecord value13(Integer value) {
        setContractId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ScContractsclassgroupRecord value14(String value) {
        setScClassesIdC(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ScContractsclassgroupRecord value15(String value) {
        setScServicessupergroupsIdC(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ScContractsclassgroupRecord value16(String value) {
        setScServicegroupsIdC(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ScContractsclassgroupRecord value17(Byte value) {
        setAreaCover(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ScContractsclassgroupRecord value18(Byte value) {
        setNetworkCover(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ScContractsclassgroupRecord value19(Integer value) {
        setMaxValLimit(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ScContractsclassgroupRecord value20(Integer value) {
        setMaxPriceLimit(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ScContractsclassgroupRecord value21(String value) {
        setRemarks(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ScContractsclassgroupRecord values(Integer value1, String value2, Timestamp value3, Timestamp value4, String value5, String value6, String value7, Byte value8, String value9, Integer value10, String value11, String value12, Integer value13, String value14, String value15, String value16, Byte value17, Byte value18, Integer value19, Integer value20, String value21) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        value14(value14);
        value15(value15);
        value16(value16);
        value17(value17);
        value18(value18);
        value19(value19);
        value20(value20);
        value21(value21);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ScContractsclassgroupRecord
     */
    public ScContractsclassgroupRecord() {
        super(ScContractsclassgroup.SC_CONTRACTSCLASSGROUP);
    }

    /**
     * Create a detached, initialised ScContractsclassgroupRecord
     */
    public ScContractsclassgroupRecord(Integer id, String name, Timestamp dateEntered, Timestamp dateModified, String modifiedUserId, String createdBy, String description, Byte deleted, String assignedUserId, Integer cmid, String scContractsClassesIdC, String scCompaniesIdC, Integer contractId, String scClassesIdC, String scServicessupergroupsIdC, String scServicegroupsIdC, Byte areaCover, Byte networkCover, Integer maxValLimit, Integer maxPriceLimit, String remarks) {
        super(ScContractsclassgroup.SC_CONTRACTSCLASSGROUP);

        set(0, id);
        set(1, name);
        set(2, dateEntered);
        set(3, dateModified);
        set(4, modifiedUserId);
        set(5, createdBy);
        set(6, description);
        set(7, deleted);
        set(8, assignedUserId);
        set(9, cmid);
        set(10, scContractsClassesIdC);
        set(11, scCompaniesIdC);
        set(12, contractId);
        set(13, scClassesIdC);
        set(14, scServicessupergroupsIdC);
        set(15, scServicegroupsIdC);
        set(16, areaCover);
        set(17, networkCover);
        set(18, maxValLimit);
        set(19, maxPriceLimit);
        set(20, remarks);
    }
}
