/*
 * This file is generated by jOOQ.
*/
package com.sms.sis.db.tables.records;


import com.sms.sis.db.tables.ScContractsClassesScPatientsC;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ScContractsClassesScPatientsCRecord extends UpdatableRecordImpl<ScContractsClassesScPatientsCRecord> implements Record5<String, Timestamp, Byte, Integer, String> {

    private static final long serialVersionUID = -1572122492;

    /**
     * Setter for <code>sugarcrm_4_12.sc_contracts_classes_sc_patients_c.id</code>.
     */
    public void setId(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>sugarcrm_4_12.sc_contracts_classes_sc_patients_c.id</code>.
     */
    public String getId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>sugarcrm_4_12.sc_contracts_classes_sc_patients_c.date_modified</code>.
     */
    public void setDateModified(Timestamp value) {
        set(1, value);
    }

    /**
     * Getter for <code>sugarcrm_4_12.sc_contracts_classes_sc_patients_c.date_modified</code>.
     */
    public Timestamp getDateModified() {
        return (Timestamp) get(1);
    }

    /**
     * Setter for <code>sugarcrm_4_12.sc_contracts_classes_sc_patients_c.deleted</code>.
     */
    public void setDeleted(Byte value) {
        set(2, value);
    }

    /**
     * Getter for <code>sugarcrm_4_12.sc_contracts_classes_sc_patients_c.deleted</code>.
     */
    public Byte getDeleted() {
        return (Byte) get(2);
    }

    /**
     * Setter for <code>sugarcrm_4_12.sc_contracts_classes_sc_patients_c.sc_contracts_classes_sc_patientssc_contracts_classes_ida</code>.
     */
    public void setScContractsClassesScPatientsscContractsClassesIda(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>sugarcrm_4_12.sc_contracts_classes_sc_patients_c.sc_contracts_classes_sc_patientssc_contracts_classes_ida</code>.
     */
    public Integer getScContractsClassesScPatientsscContractsClassesIda() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>sugarcrm_4_12.sc_contracts_classes_sc_patients_c.sc_contracts_classes_sc_patientssc_patients_idb</code>.
     */
    public void setScContractsClassesScPatientsscPatientsIdb(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>sugarcrm_4_12.sc_contracts_classes_sc_patients_c.sc_contracts_classes_sc_patientssc_patients_idb</code>.
     */
    public String getScContractsClassesScPatientsscPatientsIdb() {
        return (String) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record2<Integer, String> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<String, Timestamp, Byte, Integer, String> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<String, Timestamp, Byte, Integer, String> valuesRow() {
        return (Row5) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field1() {
        return ScContractsClassesScPatientsC.SC_CONTRACTS_CLASSES_SC_PATIENTS_C.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field2() {
        return ScContractsClassesScPatientsC.SC_CONTRACTS_CLASSES_SC_PATIENTS_C.DATE_MODIFIED;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Byte> field3() {
        return ScContractsClassesScPatientsC.SC_CONTRACTS_CLASSES_SC_PATIENTS_C.DELETED;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field4() {
        return ScContractsClassesScPatientsC.SC_CONTRACTS_CLASSES_SC_PATIENTS_C.SC_CONTRACTS_CLASSES_SC_PATIENTSSC_CONTRACTS_CLASSES_IDA;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return ScContractsClassesScPatientsC.SC_CONTRACTS_CLASSES_SC_PATIENTS_C.SC_CONTRACTS_CLASSES_SC_PATIENTSSC_PATIENTS_IDB;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value2() {
        return getDateModified();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte value3() {
        return getDeleted();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value4() {
        return getScContractsClassesScPatientsscContractsClassesIda();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getScContractsClassesScPatientsscPatientsIdb();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ScContractsClassesScPatientsCRecord value1(String value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ScContractsClassesScPatientsCRecord value2(Timestamp value) {
        setDateModified(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ScContractsClassesScPatientsCRecord value3(Byte value) {
        setDeleted(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ScContractsClassesScPatientsCRecord value4(Integer value) {
        setScContractsClassesScPatientsscContractsClassesIda(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ScContractsClassesScPatientsCRecord value5(String value) {
        setScContractsClassesScPatientsscPatientsIdb(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ScContractsClassesScPatientsCRecord values(String value1, Timestamp value2, Byte value3, Integer value4, String value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ScContractsClassesScPatientsCRecord
     */
    public ScContractsClassesScPatientsCRecord() {
        super(ScContractsClassesScPatientsC.SC_CONTRACTS_CLASSES_SC_PATIENTS_C);
    }

    /**
     * Create a detached, initialised ScContractsClassesScPatientsCRecord
     */
    public ScContractsClassesScPatientsCRecord(String id, Timestamp dateModified, Byte deleted, Integer scContractsClassesScPatientsscContractsClassesIda, String scContractsClassesScPatientsscPatientsIdb) {
        super(ScContractsClassesScPatientsC.SC_CONTRACTS_CLASSES_SC_PATIENTS_C);

        set(0, id);
        set(1, dateModified);
        set(2, deleted);
        set(3, scContractsClassesScPatientsscContractsClassesIda);
        set(4, scContractsClassesScPatientsscPatientsIdb);
    }
}
