/*
 * This file is generated by jOOQ.
*/
package com.sms.sis.db.tables.records;


import com.sms.sis.db.tables.ScDeductionCstm;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Row1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ScDeductionCstmRecord extends UpdatableRecordImpl<ScDeductionCstmRecord> implements Record1<String> {

    private static final long serialVersionUID = -1163831140;

    /**
     * Setter for <code>sugarcrm_4_12.sc_deduction_cstm.id_c</code>.
     */
    public void setIdC(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>sugarcrm_4_12.sc_deduction_cstm.id_c</code>.
     */
    public String getIdC() {
        return (String) get(0);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record1 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row1<String> fieldsRow() {
        return (Row1) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row1<String> valuesRow() {
        return (Row1) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field1() {
        return ScDeductionCstm.SC_DEDUCTION_CSTM.ID_C;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value1() {
        return getIdC();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ScDeductionCstmRecord value1(String value) {
        setIdC(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ScDeductionCstmRecord values(String value1) {
        value1(value1);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ScDeductionCstmRecord
     */
    public ScDeductionCstmRecord() {
        super(ScDeductionCstm.SC_DEDUCTION_CSTM);
    }

    /**
     * Create a detached, initialised ScDeductionCstmRecord
     */
    public ScDeductionCstmRecord(String idC) {
        super(ScDeductionCstm.SC_DEDUCTION_CSTM);

        set(0, idC);
    }
}
