/*
 * This file is generated by jOOQ.
*/
package com.sms.sis.db.tables.records;


import com.sms.sis.db.tables.SsJournalEntry;

import java.math.BigDecimal;
import java.sql.Date;
import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record20;
import org.jooq.Row20;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SsJournalEntryRecord extends UpdatableRecordImpl<SsJournalEntryRecord> implements Record20<String, String, Timestamp, Timestamp, String, String, String, Byte, String, Date, String, BigDecimal, String, Byte, Byte, Integer, Byte, Byte, String, String> {

    private static final long serialVersionUID = -246343127;

    /**
     * Setter for <code>sugarcrm_4_12.ss_journal_entry.id</code>.
     */
    public void setId(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>sugarcrm_4_12.ss_journal_entry.id</code>.
     */
    public String getId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>sugarcrm_4_12.ss_journal_entry.name</code>.
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>sugarcrm_4_12.ss_journal_entry.name</code>.
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>sugarcrm_4_12.ss_journal_entry.date_entered</code>.
     */
    public void setDateEntered(Timestamp value) {
        set(2, value);
    }

    /**
     * Getter for <code>sugarcrm_4_12.ss_journal_entry.date_entered</code>.
     */
    public Timestamp getDateEntered() {
        return (Timestamp) get(2);
    }

    /**
     * Setter for <code>sugarcrm_4_12.ss_journal_entry.date_modified</code>.
     */
    public void setDateModified(Timestamp value) {
        set(3, value);
    }

    /**
     * Getter for <code>sugarcrm_4_12.ss_journal_entry.date_modified</code>.
     */
    public Timestamp getDateModified() {
        return (Timestamp) get(3);
    }

    /**
     * Setter for <code>sugarcrm_4_12.ss_journal_entry.modified_user_id</code>.
     */
    public void setModifiedUserId(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>sugarcrm_4_12.ss_journal_entry.modified_user_id</code>.
     */
    public String getModifiedUserId() {
        return (String) get(4);
    }

    /**
     * Setter for <code>sugarcrm_4_12.ss_journal_entry.created_by</code>.
     */
    public void setCreatedBy(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>sugarcrm_4_12.ss_journal_entry.created_by</code>.
     */
    public String getCreatedBy() {
        return (String) get(5);
    }

    /**
     * Setter for <code>sugarcrm_4_12.ss_journal_entry.description</code>.
     */
    public void setDescription(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>sugarcrm_4_12.ss_journal_entry.description</code>.
     */
    public String getDescription() {
        return (String) get(6);
    }

    /**
     * Setter for <code>sugarcrm_4_12.ss_journal_entry.deleted</code>.
     */
    public void setDeleted(Byte value) {
        set(7, value);
    }

    /**
     * Getter for <code>sugarcrm_4_12.ss_journal_entry.deleted</code>.
     */
    public Byte getDeleted() {
        return (Byte) get(7);
    }

    /**
     * Setter for <code>sugarcrm_4_12.ss_journal_entry.assigned_user_id</code>.
     */
    public void setAssignedUserId(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>sugarcrm_4_12.ss_journal_entry.assigned_user_id</code>.
     */
    public String getAssignedUserId() {
        return (String) get(8);
    }

    /**
     * Setter for <code>sugarcrm_4_12.ss_journal_entry.transaction_date</code>.
     */
    public void setTransactionDate(Date value) {
        set(9, value);
    }

    /**
     * Getter for <code>sugarcrm_4_12.ss_journal_entry.transaction_date</code>.
     */
    public Date getTransactionDate() {
        return (Date) get(9);
    }

    /**
     * Setter for <code>sugarcrm_4_12.ss_journal_entry.memo</code>.
     */
    public void setMemo(String value) {
        set(10, value);
    }

    /**
     * Getter for <code>sugarcrm_4_12.ss_journal_entry.memo</code>.
     */
    public String getMemo() {
        return (String) get(10);
    }

    /**
     * Setter for <code>sugarcrm_4_12.ss_journal_entry.amount</code>.
     */
    public void setAmount(BigDecimal value) {
        set(11, value);
    }

    /**
     * Getter for <code>sugarcrm_4_12.ss_journal_entry.amount</code>.
     */
    public BigDecimal getAmount() {
        return (BigDecimal) get(11);
    }

    /**
     * Setter for <code>sugarcrm_4_12.ss_journal_entry.currency_id</code>.
     */
    public void setCurrencyId(String value) {
        set(12, value);
    }

    /**
     * Getter for <code>sugarcrm_4_12.ss_journal_entry.currency_id</code>.
     */
    public String getCurrencyId() {
        return (String) get(12);
    }

    /**
     * Setter for <code>sugarcrm_4_12.ss_journal_entry.is_closed</code>.
     */
    public void setIsClosed(Byte value) {
        set(13, value);
    }

    /**
     * Getter for <code>sugarcrm_4_12.ss_journal_entry.is_closed</code>.
     */
    public Byte getIsClosed() {
        return (Byte) get(13);
    }

    /**
     * Setter for <code>sugarcrm_4_12.ss_journal_entry.is_processed</code>.
     */
    public void setIsProcessed(Byte value) {
        set(14, value);
    }

    /**
     * Getter for <code>sugarcrm_4_12.ss_journal_entry.is_processed</code>.
     */
    public Byte getIsProcessed() {
        return (Byte) get(14);
    }

    /**
     * Setter for <code>sugarcrm_4_12.ss_journal_entry.transaction_num</code>.
     */
    public void setTransactionNum(Integer value) {
        set(15, value);
    }

    /**
     * Getter for <code>sugarcrm_4_12.ss_journal_entry.transaction_num</code>.
     */
    public Integer getTransactionNum() {
        return (Integer) get(15);
    }

    /**
     * Setter for <code>sugarcrm_4_12.ss_journal_entry.is_automatic</code>.
     */
    public void setIsAutomatic(Byte value) {
        set(16, value);
    }

    /**
     * Getter for <code>sugarcrm_4_12.ss_journal_entry.is_automatic</code>.
     */
    public Byte getIsAutomatic() {
        return (Byte) get(16);
    }

    /**
     * Setter for <code>sugarcrm_4_12.ss_journal_entry.affects_cc</code>.
     */
    public void setAffectsCc(Byte value) {
        set(17, value);
    }

    /**
     * Getter for <code>sugarcrm_4_12.ss_journal_entry.affects_cc</code>.
     */
    public Byte getAffectsCc() {
        return (Byte) get(17);
    }

    /**
     * Setter for <code>sugarcrm_4_12.ss_journal_entry.transaction_type</code>.
     */
    public void setTransactionType(String value) {
        set(18, value);
    }

    /**
     * Getter for <code>sugarcrm_4_12.ss_journal_entry.transaction_type</code>.
     */
    public String getTransactionType() {
        return (String) get(18);
    }

    /**
     * Setter for <code>sugarcrm_4_12.ss_journal_entry.ss_cost_centers_id_c</code>.
     */
    public void setSsCostCentersIdC(String value) {
        set(19, value);
    }

    /**
     * Getter for <code>sugarcrm_4_12.ss_journal_entry.ss_cost_centers_id_c</code>.
     */
    public String getSsCostCentersIdC() {
        return (String) get(19);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record20 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row20<String, String, Timestamp, Timestamp, String, String, String, Byte, String, Date, String, BigDecimal, String, Byte, Byte, Integer, Byte, Byte, String, String> fieldsRow() {
        return (Row20) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row20<String, String, Timestamp, Timestamp, String, String, String, Byte, String, Date, String, BigDecimal, String, Byte, Byte, Integer, Byte, Byte, String, String> valuesRow() {
        return (Row20) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field1() {
        return SsJournalEntry.SS_JOURNAL_ENTRY.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return SsJournalEntry.SS_JOURNAL_ENTRY.NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field3() {
        return SsJournalEntry.SS_JOURNAL_ENTRY.DATE_ENTERED;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field4() {
        return SsJournalEntry.SS_JOURNAL_ENTRY.DATE_MODIFIED;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return SsJournalEntry.SS_JOURNAL_ENTRY.MODIFIED_USER_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return SsJournalEntry.SS_JOURNAL_ENTRY.CREATED_BY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field7() {
        return SsJournalEntry.SS_JOURNAL_ENTRY.DESCRIPTION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Byte> field8() {
        return SsJournalEntry.SS_JOURNAL_ENTRY.DELETED;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field9() {
        return SsJournalEntry.SS_JOURNAL_ENTRY.ASSIGNED_USER_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Date> field10() {
        return SsJournalEntry.SS_JOURNAL_ENTRY.TRANSACTION_DATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field11() {
        return SsJournalEntry.SS_JOURNAL_ENTRY.MEMO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<BigDecimal> field12() {
        return SsJournalEntry.SS_JOURNAL_ENTRY.AMOUNT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field13() {
        return SsJournalEntry.SS_JOURNAL_ENTRY.CURRENCY_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Byte> field14() {
        return SsJournalEntry.SS_JOURNAL_ENTRY.IS_CLOSED;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Byte> field15() {
        return SsJournalEntry.SS_JOURNAL_ENTRY.IS_PROCESSED;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field16() {
        return SsJournalEntry.SS_JOURNAL_ENTRY.TRANSACTION_NUM;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Byte> field17() {
        return SsJournalEntry.SS_JOURNAL_ENTRY.IS_AUTOMATIC;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Byte> field18() {
        return SsJournalEntry.SS_JOURNAL_ENTRY.AFFECTS_CC;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field19() {
        return SsJournalEntry.SS_JOURNAL_ENTRY.TRANSACTION_TYPE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field20() {
        return SsJournalEntry.SS_JOURNAL_ENTRY.SS_COST_CENTERS_ID_C;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value3() {
        return getDateEntered();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value4() {
        return getDateModified();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getModifiedUserId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getCreatedBy();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value7() {
        return getDescription();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte value8() {
        return getDeleted();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value9() {
        return getAssignedUserId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Date value10() {
        return getTransactionDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value11() {
        return getMemo();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal value12() {
        return getAmount();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value13() {
        return getCurrencyId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte value14() {
        return getIsClosed();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte value15() {
        return getIsProcessed();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value16() {
        return getTransactionNum();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte value17() {
        return getIsAutomatic();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte value18() {
        return getAffectsCc();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value19() {
        return getTransactionType();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value20() {
        return getSsCostCentersIdC();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SsJournalEntryRecord value1(String value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SsJournalEntryRecord value2(String value) {
        setName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SsJournalEntryRecord value3(Timestamp value) {
        setDateEntered(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SsJournalEntryRecord value4(Timestamp value) {
        setDateModified(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SsJournalEntryRecord value5(String value) {
        setModifiedUserId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SsJournalEntryRecord value6(String value) {
        setCreatedBy(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SsJournalEntryRecord value7(String value) {
        setDescription(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SsJournalEntryRecord value8(Byte value) {
        setDeleted(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SsJournalEntryRecord value9(String value) {
        setAssignedUserId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SsJournalEntryRecord value10(Date value) {
        setTransactionDate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SsJournalEntryRecord value11(String value) {
        setMemo(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SsJournalEntryRecord value12(BigDecimal value) {
        setAmount(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SsJournalEntryRecord value13(String value) {
        setCurrencyId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SsJournalEntryRecord value14(Byte value) {
        setIsClosed(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SsJournalEntryRecord value15(Byte value) {
        setIsProcessed(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SsJournalEntryRecord value16(Integer value) {
        setTransactionNum(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SsJournalEntryRecord value17(Byte value) {
        setIsAutomatic(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SsJournalEntryRecord value18(Byte value) {
        setAffectsCc(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SsJournalEntryRecord value19(String value) {
        setTransactionType(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SsJournalEntryRecord value20(String value) {
        setSsCostCentersIdC(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SsJournalEntryRecord values(String value1, String value2, Timestamp value3, Timestamp value4, String value5, String value6, String value7, Byte value8, String value9, Date value10, String value11, BigDecimal value12, String value13, Byte value14, Byte value15, Integer value16, Byte value17, Byte value18, String value19, String value20) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        value14(value14);
        value15(value15);
        value16(value16);
        value17(value17);
        value18(value18);
        value19(value19);
        value20(value20);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached SsJournalEntryRecord
     */
    public SsJournalEntryRecord() {
        super(SsJournalEntry.SS_JOURNAL_ENTRY);
    }

    /**
     * Create a detached, initialised SsJournalEntryRecord
     */
    public SsJournalEntryRecord(String id, String name, Timestamp dateEntered, Timestamp dateModified, String modifiedUserId, String createdBy, String description, Byte deleted, String assignedUserId, Date transactionDate, String memo, BigDecimal amount, String currencyId, Byte isClosed, Byte isProcessed, Integer transactionNum, Byte isAutomatic, Byte affectsCc, String transactionType, String ssCostCentersIdC) {
        super(SsJournalEntry.SS_JOURNAL_ENTRY);

        set(0, id);
        set(1, name);
        set(2, dateEntered);
        set(3, dateModified);
        set(4, modifiedUserId);
        set(5, createdBy);
        set(6, description);
        set(7, deleted);
        set(8, assignedUserId);
        set(9, transactionDate);
        set(10, memo);
        set(11, amount);
        set(12, currencyId);
        set(13, isClosed);
        set(14, isProcessed);
        set(15, transactionNum);
        set(16, isAutomatic);
        set(17, affectsCc);
        set(18, transactionType);
        set(19, ssCostCentersIdC);
    }
}
