/*
 * This file is generated by jOOQ.
*/
package com.sms.sis.db.tables.records;


import com.sms.sis.db.tables.TasksCstm;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TasksCstmRecord extends UpdatableRecordImpl<TasksCstmRecord> implements Record3<String, String, String> {

    private static final long serialVersionUID = -1967989796;

    /**
     * Setter for <code>sugarcrm_4_12.tasks_cstm.id_c</code>.
     */
    public void setIdC(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>sugarcrm_4_12.tasks_cstm.id_c</code>.
     */
    public String getIdC() {
        return (String) get(0);
    }

    /**
     * Setter for <code>sugarcrm_4_12.tasks_cstm.approvaltype_c</code>.
     */
    public void setApprovaltypeC(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>sugarcrm_4_12.tasks_cstm.approvaltype_c</code>.
     */
    public String getApprovaltypeC() {
        return (String) get(1);
    }

    /**
     * Setter for <code>sugarcrm_4_12.tasks_cstm.emailid_c</code>.
     */
    public void setEmailidC(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>sugarcrm_4_12.tasks_cstm.emailid_c</code>.
     */
    public String getEmailidC() {
        return (String) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<String, String, String> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<String, String, String> valuesRow() {
        return (Row3) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field1() {
        return TasksCstm.TASKS_CSTM.ID_C;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return TasksCstm.TASKS_CSTM.APPROVALTYPE_C;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return TasksCstm.TASKS_CSTM.EMAILID_C;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value1() {
        return getIdC();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getApprovaltypeC();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getEmailidC();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TasksCstmRecord value1(String value) {
        setIdC(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TasksCstmRecord value2(String value) {
        setApprovaltypeC(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TasksCstmRecord value3(String value) {
        setEmailidC(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TasksCstmRecord values(String value1, String value2, String value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TasksCstmRecord
     */
    public TasksCstmRecord() {
        super(TasksCstm.TASKS_CSTM);
    }

    /**
     * Create a detached, initialised TasksCstmRecord
     */
    public TasksCstmRecord(String idC, String approvaltypeC, String emailidC) {
        super(TasksCstm.TASKS_CSTM);

        set(0, idC);
        set(1, approvaltypeC);
        set(2, emailidC);
    }
}
