/*
 * This file is generated by jOOQ.
*/
package com.sms.sis.db.tables.records;


import com.sms.sis.db.tables.UsersFeeds;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UsersFeedsRecord extends TableRecordImpl<UsersFeedsRecord> implements Record5<String, String, Integer, Timestamp, Byte> {

    private static final long serialVersionUID = 1059500291;

    /**
     * Setter for <code>sugarcrm_4_12.users_feeds.user_id</code>.
     */
    public void setUserId(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>sugarcrm_4_12.users_feeds.user_id</code>.
     */
    public String getUserId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>sugarcrm_4_12.users_feeds.feed_id</code>.
     */
    public void setFeedId(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>sugarcrm_4_12.users_feeds.feed_id</code>.
     */
    public String getFeedId() {
        return (String) get(1);
    }

    /**
     * Setter for <code>sugarcrm_4_12.users_feeds.rank</code>.
     */
    public void setRank(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>sugarcrm_4_12.users_feeds.rank</code>.
     */
    public Integer getRank() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>sugarcrm_4_12.users_feeds.date_modified</code>.
     */
    public void setDateModified(Timestamp value) {
        set(3, value);
    }

    /**
     * Getter for <code>sugarcrm_4_12.users_feeds.date_modified</code>.
     */
    public Timestamp getDateModified() {
        return (Timestamp) get(3);
    }

    /**
     * Setter for <code>sugarcrm_4_12.users_feeds.deleted</code>.
     */
    public void setDeleted(Byte value) {
        set(4, value);
    }

    /**
     * Getter for <code>sugarcrm_4_12.users_feeds.deleted</code>.
     */
    public Byte getDeleted() {
        return (Byte) get(4);
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<String, String, Integer, Timestamp, Byte> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<String, String, Integer, Timestamp, Byte> valuesRow() {
        return (Row5) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field1() {
        return UsersFeeds.USERS_FEEDS.USER_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return UsersFeeds.USERS_FEEDS.FEED_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field3() {
        return UsersFeeds.USERS_FEEDS.RANK;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field4() {
        return UsersFeeds.USERS_FEEDS.DATE_MODIFIED;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Byte> field5() {
        return UsersFeeds.USERS_FEEDS.DELETED;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value1() {
        return getUserId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getFeedId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value3() {
        return getRank();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value4() {
        return getDateModified();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte value5() {
        return getDeleted();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UsersFeedsRecord value1(String value) {
        setUserId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UsersFeedsRecord value2(String value) {
        setFeedId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UsersFeedsRecord value3(Integer value) {
        setRank(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UsersFeedsRecord value4(Timestamp value) {
        setDateModified(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UsersFeedsRecord value5(Byte value) {
        setDeleted(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UsersFeedsRecord values(String value1, String value2, Integer value3, Timestamp value4, Byte value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached UsersFeedsRecord
     */
    public UsersFeedsRecord() {
        super(UsersFeeds.USERS_FEEDS);
    }

    /**
     * Create a detached, initialised UsersFeedsRecord
     */
    public UsersFeedsRecord(String userId, String feedId, Integer rank, Timestamp dateModified, Byte deleted) {
        super(UsersFeeds.USERS_FEEDS);

        set(0, userId);
        set(1, feedId);
        set(2, rank);
        set(3, dateModified);
        set(4, deleted);
    }
}
